### ISSUE TITLE
What is human being?(What is required bone?)

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#10]
結論を先に述べます。標準化と多様性は相反するものですが、VRMとしての人間型とは何か、どこまでボーンがあればよいのか、について明言をして頂きたいです。

　以下に理由を述べます。
[bones of humanoid in VRM spec 0.0](https://vrm.dev/vrm_spec/#%E5%AE%9A%E7%BE%A9%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%83%9C%E3%83%BC%E3%83%B3)

 　VRMはプラットフォームフリーの人間型モデルを記録するフォーマットであることはその存在意義からして間違いないと思います。
　しかしその実態はunityのhumanoidを構成できるよう、またunityのアセット上必要なボーンが存在するように作られた仕様ではないか、と私は感じており、ボーン構造的に腕脚他の本数が平均的な人間を模したアバターのみが読み込めるuniVRM(標準実装)があります。
　しかし、現実(に限りませんが)の人を構成するパーツの数には平均より多いことも、少ないこともあるのは周知の事実かと思います。
　ここで私は、人間型アバターにおいて、自己を表現するときに、物理現実のインポートにせよ精神的自己表現にせよ、現状では**平均的な人間型でないといけないという制約を課している**と言えるのではないか、という**問題提起**をします。
　アーティストがダミーボーンを入れれば解決できる問題でもありますが…　一方でVRMには現実同様に多様性を持たせ、uniVRM他実装に吸収させる(ダミーボーンを自動生成する等)という手もあると思います。
　**そこで**、改めて、標準化と多様性は相反するものですが、現行のままにするという事も含めて、VRMとしての人間型とは何か、について明言をして頂きたいというわけです。

relate: https://github.com/vrm-c/vrm-specification/issues/8#issuecomment-527298136_

**Comment by FMS-Cat** [comment]
かなり過激めな定義とするならば、すべてのボーンはオプショナルであり、どのボーンが必須であるかはアプリケーションが定める、とすることは可能と思います。
単にTポーズができれば良いだけのアプリケーションであれば、どのボーンも必要ありませんし、
逆に手の細かい動きを要求するようなアプリケーションであれば、指のボーンを必須としたいでしょう。

現状のVRMの仕様は、一定のHumanoidの可搬性を保ちつつ、その定義の自由度を高めるために一部がオプショナルとなっている、と推測しますが、
各ボーンがなぜ必要なのかが明解となる説明をする必要がある、というのは自分も同意します。

**Comment by ousttrue** [comment]
TODO: 必須でないボーン例えば UpperChest が無い場合は、`Neck` の親は、`UpperChest` の親に遡る。
