### ISSUE TITLE
[1.0draft] definition of sRGB <-> Linear transformation

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#100]
unityブラックボックスのsRGB<->Linear変換式(ガンマ変換)の明示をお願いいたします。
おおまかに、
https://en.wikipedia.org/wiki/SRGB#Specification_of_the_transformation
なのか、
n^2.2 <-> n(1/2.2)
の２種があると思います。

**Comment by FMS-Cat** [comment]
glTF側の仕様に依存で十分かと思います。
ちなみにglTF側の仕様にも変換式は具体的に明示されていないので、各ツール・フレームワークで標準的な手法を取れば十分かと思います。

**Comment by hiroj** [comment]
同じくglTFの仕様依存で良いと思います、仕様には明記せず実装側で適切な手法を取っていただければよいかと。

**Comment by iCyP** [comment]
承知致しました。
