### ISSUE TITLE
Unlitシェーダーについて提案

### ISSUE THREAD

**Issue by KatanoShingo** [vrm-c/vrm-specification#104]
# 問題
- VRMの一つのアバターでどこへでも行き来できる思想からは、Unlitシェーダーはアプリケーションの世界からはずれてしまうと考えています。  
例：真っ暗な暗いシーンに置いて、アバターが暗くならない  
- Unlitシェーダーによってアプリケーションとの交わりが少なくなってしまっている。  
 # 提案  
- Unlitシェーダーの削除  
- または、Unlitシェーダー選択への非推奨

**Comment by KatanoShingo** [comment]
# 補足
 - Unlitシェーダーを使うことは、モデル側の暗闇でも輝くマテリアルにしたい意思表示だと思います。
- アプリケーション側でマテリアルをオーバーライドする場合意図しない影が落ちてしまう。
- Unlitシェーダーを受け入れるとアプリケーション側の世界感が下がってしまいます。
- Unlitシェーダーのアバターをアプリケーション側ではじいてしまうと、プラットフォーム依存（Unlitシェーダー以外のアバターが必要）になってしまいます。

**Comment by hiroj** [comment]
VRM は Gltf を拡張したフォーマットであるため、Gltf の機能としてUnlitを指定出来る限りはVRM も対応する必要があるという理由でUnlitシェーダーを入れています。
ライティング可能なShaderのみを使用することで、ある程度でもアプリケーションの見た目を統一したいということでしょうか。
Unlitが必要かどうかは他の方のご意見も頂けると助かります。

**Comment by iCyP** [comment]
unlitはVRM固有のものではなく、KHR_materials_unlitとしてマテリアル拡張として存在するので、VRM上で有り無しを議論できるものではないと思います。標準実装ではサポートされている方がベターとみなせると考えます。
　**KHR_materials_unlit対応は 個別アプリケーション側 が、実装するか、標準的挙動から外れて実装しないかを判断し、ユーザに理由を周知し、利用するか判断させるようなものではないかと考えます。** [なお、KHR_(ry)をunlitから勝手にshadedなマテリアルにアップグレードすべきでないともドキュメント](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit#overview)に書かれています。それとは別に、unlitと環境色を乗算するだけのunlit_without_environmentのような単純な拡張をKhronosに提案するのも一つだと思います。
　なお参考までに、unlitを排除しても、MToonの影の出具合を制御するshadeshiftを-1にすれば、リムライトやアウトラインが付くunlitと同義になるので、KHR_material_unlitをVRMとして制限するかの議論だけでは解決しない問題です。

**Comment by hiroj** [comment]
iCyP さんの通り、KHR_materials_unlitはgltfの拡張であるため、VRMはUnlitをサポートし続ける方針になりますので、このissueはいったんclose致します。
