### ISSUE TITLE
KHR_techniques_webgl拡張に対応してほしい

### ISSUE THREAD

**Issue by vyv03354** [vrm-c/vrm-specification#105]
シェーダーの内容はMToonを表すものでなければならないという制限とか、アプリケーションはシェーダーの内容を無視して組み込みのMToonシェーダーを使っていいとか(そもそもWebGLベースの実装とは限りませんし)、VRM拡張側でMToonとみなす`technique`の番号を指定する機能(`{"MToonBase": 0, "MToonOutline": 1}`みたいな)とかが必要だと思いますが、少なくともuniformの受け渡し方法は同じようにしてほしいです。
Ref: #95

**Comment by FMS-Cat** [comment]
MToonについては、VRM1.0以降仕様が固まる `VRMC_materials_mtoon` 拡張がその責務を果たすと思います。
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0_draft

**Comment by vyv03354** [comment]
`KHR_techniques_webgl`拡張の開発は棚上げになっていました。
