### ISSUE TITLE
[1.0draft] Removed some parameters of MToon

### ISSUE THREAD

**Issue by hiroj** [vrm-c/vrm-specification#109]
remove the following parameters
* shadowReceiveMultiplierFactor
* shadowReceiveMultiplierMultiplyTexture
* litAndShadeMixingMultiplierFactor
* litAndShadeMixingMultiplierMultiplyTexture

**Comment by iCyP** [comment]
I think issue & PR should be with reason. 
Because for no one use them, for implementation compatibility, for general rendering performance or others?

**Comment by hiroj** [comment]
MToon Developers rarely used it and decided it was unnecessary.
I will be careful in the future to write the reason for issue.

**Comment by iCyP** [comment]
I understand it. Thank you.
