### ISSUE TITLE
Clarify the relationship between each human bones

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#11]
現状、各ボーンがどのように繋がっているべきかの説明が仕様に存在しません。
UniVRMの実装では、ある一定の規則に従ってボーンを繋げないとエラーを発しますが、
（もちろん常識的に考えれば各ボーンの関係性は自明であるものの、）
その関係性を仕様においても明示的に示す必要があるかと思います。

Related: #10

**Comment by hiroj** [comment]
以下のVRM1.0draftのドキュメント内にボーンの繋がりについての情報を追加しました。
不鮮明な点等ある場合はご意見頂けると助かります。
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E3%83%92%E3%83%A5%E3%83%BC%E3%83%9E%E3%83%8E%E3%82%A4%E3%83%89

**Comment by FMS-Cat** [comment]
素晴らしいです！
