### ISSUE TITLE
#108 の meta.authorsについて

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#113]
このプロパティの状態であると、 モデルおよびそのリソースの権利があいまいになりすぎると思います。またそれは、リソース単体の権利情報や配布元にアクセスできない(別添readme運用になってしまう)のような問題等を引き起こすと考えられます。
　私の提案は基本的に #51 のとおり、個別のリソース毎に記述することです。
　コンソーシアムではどのような議論の結果この仕様を採用しようという結論に至ったのか、明らかにしていただけると議論の手間が省けると思います。

**Comment by hiroj** [comment]
ご意見ありがとうございます、法務委員会の方に問い合わせてみます。

**Comment by iCyP** [comment]
openからひと月なにも回答がありませんが、無回答として閉じて良ければcloseしますのでそのまま放置してください。回答予定があるなら再度openし、回答をお願いします。
