### ISSUE TITLE
Implementation guide about Humanoid

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#12]
UnityにはMecanimという機構があり、現状のVRMは、Humanoidを動かす上では、その実装に強く依存した仕様となっています。
現在、私は [@pixiv/three-vrm](https://github.com/pixiv/three-vrm) というThree.jsでのVRM実装のプロジェクトに参加していますが、
Mecanimのような機構の存在しない環境において、Humanoidをどのように動かすべきかを示す指標を定めたいです。
具体的には、VRM内の `HumanDescription` ・ `HumanLimit` に属するフィールドをどのように取り扱うべきかを明文化したいです。

現状、 @pixiv/three-vrm では、クオータニオンを用いて各ボーンの回転を制御してポーズを付けていますが、
単純なクオータニオンのみを用いて任意のアバターに適したポーズ付けを行うのはなかなか難しいです……

**Comment by FMS-Cat** [comment]
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#humanoid では、humanDescription / humanLimit が廃止になったようですね。
あまりHumanoidについて詳しくないのですが、体格差などを吸収する仕組みが無くなるということでしょうか。

また、 #20 が指摘するように、VRMとしてTポーズを定義することは必要になりますね。
これについては、新たに仕様に明文化がされるようで、とても良いと思います！
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#tpose-specification

**Comment by hiroj** [comment]
humanDescription と humanLimit は、Unity の FBX の設定UIから生成されるHumanIK用のパラメータ（AnimationComponentのIK機能、およびOnAnimatorIKで使う機能のカスタマイズ設定）なのですが、仕様がBlackboxでありUnityのHumanoidIKに対して互換性を持ったパラメータを扱うことが難しいと判断したためいったん廃止とさせていただきました。
ただ Rig や Retargetingを使用したアニメーション機能などは今後の課題になるとは思います。

**Comment by hiroj** [comment]
アニメーションに関してはいったん #118 で取りまとめることにします。
