### ISSUE TITLE
[1.0-draft] We might want to separate the definition of colliders from VRMCSpringBone

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#122]
colliderの定義は将来的にはSpringBone以外でも使われる可能性があるため、もしかしたらSpringBoneの定義からは引き剥がして定義しちゃったほうが良いかもしれないです。

**Comment by hiroj** [comment]
そうですね、コライダの形状だけを記載する拡張に分離することを検討してみます。

**Comment by ousttrue** [comment]
`VRMC_node_spape` という感じの node の extensions にしてみようかと思います。
collider だとは言及せず、mass 等の physics 系のパラメーターは持たないという意思で
この名前にしました。
ひとつのノードに複数のshapeがアタッチされる想定です。

細かいところは作ってみてから考えますが、以下のような形を検討しています。

```json
{
    "shapes": [ // unionの配列を想定
    {
        "sphere": {
            "offset": [0, 0, 0],
            "radius": 1
        }
    },
    {
        "capsule": {
            "offset": [0, 0, 0],
            "radius": 1,
            "tail": [0, 0, 1]
        }
    }
}
```

UniVRM-1.0で使っているProtoBufのJSON入出力実装がうまく適応できるかはやってみないとわからないところです。

`VRMC_springBone` の コライダーが nodeIndex で参照する予定です。
Unityコンポーネントの変更は無しで、シリアライザの変更で対応予定です。

TODO: 実装のPRをこのISSUEに関連付ける

**Comment by ousttrue** [comment]
#142 に実装案を作りました。

VRMC_SpringBone のコライダーで参照するようにしてみました。

**Comment by FMS-Cat** [comment]
> collider だとは言及せず、mass 等の physics 系のパラメーターは持たないという意思で
> この名前にしました。

bounding volumeと混同されることを避けるため、colliderであることは明示しておいた方が良いと考えました。
実際、bounding volumeとcolliderの間には、その形状の作られ方に差異が見受けられると思います。

**Comment by ousttrue** [comment]
なるほど。 `VRMC_node_collider` にしましょうか。
`collider` の中に `shapes` がある形。

**Comment by FMS-Cat** [comment]
https://github.com/vrm-c/vrm-specification/pull/154 で引き続き検討が進んでいます。
