### ISSUE TITLE
[1.0-draft] Removing MToon specs that overlaps with glTF material spec

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#127]
### 概要

`KHR_materials_unlit` では、マテリアルのコア定義で定義されているプロパティについては、そちらを参照するという方針をとっています。
我々の `VRMC_materials_mtoon` についても、同様にマテリアルのコア定義・および `KHR_texture_transform` 拡張でカバーできる範囲のプロパティについては、そちらを参照する方針としたほうが良いと思います。

### 置き換えるパラメータ

- ➖ `/materials/i/extensions/VRMC_materials_mtoon/cullMode`
    - `/materials/i/doubleSided` に置換
        - これまで4通りから指定できたカリングが、表・両面と2通りになるため、自由度が下がるのが悩ましい点です
- ➖`/materials/i/extensions/VRMC_materials_mtoon/renderMode`
    - `/materials/i/alphaMode` に置換
- ➕ `/materials/i/extensions/VRMC_materials_mtoon/zWrite`
    - `renderMode` が消えたことで指定ができなくなる `transparentWithZWrite` を置き換えるものです
    - 本当に要るかをもう一度検討し直す必要はあるかと思います
- ➖ `/materials/i/extensions/VRMC_materials_mtoon/litFactor`
    - `/materials/i/pbrMetallicRoughness/baseColorFactor` に置換
    - `shadeFactor` は残ります
- ➖ `/materials/i/extensions/VRMC_materials_mtoon/litMultiplyTexture`
    - `/materials/i/pbrMetallicRoughness/baseColorTexture` に置換
    - `shadeMultiplyTexture` は残ります
- ➖ `/materials/i/extensions/VRMC_materials_mtoon/cutoutThresholdFactor`
    - `/materials/i/alphaCutoff` に置換
- ➖ `/materials/i/extensions/VRMC_materials_mtoon/normalTexture`
    - `/materials/i/normalTexture/index` に置換
- ➖ `/materials/i/extensions/VRMC_materials_mtoon/normalScaleFactor`
    - `/materials/i/normalTexture/scale` に置換
- ➖ `/materials/i/extensions/VRMC_materials_mtoon/emissionFactor`
    - `/materials/i/emissiveFactor` に置換
- ➖ `/materials/i/extensions/VRMC_materials_mtoon/emissionMultiplyTexture`
    - `/materials/i/emissiveTexture/index` に置換
- ➖ `/materials/i/extensions/VRMC_materials_mtoon/mainTextureLeftBottomOriginOffset`
    - `/materials/i/extensions/KHR_texture_transform/offset` に置換
- ➖ `/materials/i/extensions/VRMC_materials_mtoon/mainTextureLeftBottomOriginScale`
    - `/materials/i/extensions/KHR_texture_transform/scale` に置換

### 余談

- 懸念点として、 `mainTextureLeftBottomOriginOffset` を `KHR_texture_transform` 側に揃えるとして、 `uvAnimationRotationSpeedFactor` で回転するUVアニメーションが、現状のMToonの実装ベースだと `(0.5, 0.5)` 周りに回転するのが、 `KHR_texture_transform/rotation` だと原点周りに回転するのが気になります。
    - いずれにせよ、ここの実装はあまりされていないようですが……
    - のちほど、別途issueを建てます。

**Comment by ousttrue** [comment]
baseColorFactor 等対応関係が明確で、型が同じ(Gltfのバリデーターにひっかからない) ところを取り入れます。

**Comment by FMS-Cat** [comment]
#150 で変更が取り入れられましたのでCloseします。ありがとうございました！
