### ISSUE TITLE
BlendShapePresetのリップシンクを CH、aa、O の3つに

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#148]
https://github.com/vrm-c/vrm-specification/blob/35e9c14cac83d75d528b35b66773dbb2e84385f1/specification/VRMC_vrm-1.0_draft/README.ja.md#%E3%83%AA%E3%83%83%E3%83%97%E3%82%B7%E3%83%B3%E3%82%AFenum

上記について、CH、aa、O の3つのキーからリップシンク用のキーを生成できる (生成する必要がある) ので、プリセットでは5つではなく3つとし、#86 で提案されているプリセットの標準拡張として [Viseme Reference | Oculus Developer Center](https://developer.oculus.com/documentation/unity/audio-ovrlipsync-viseme-reference/) の他の12個を定義するようにしてはどうでしょうか。

名前 | 備考
-- | --
ch | い
aa | あ
o | oh, お

参考: https://github.com/GiveMeAllYourCats/cats-blender-plugin/blob/0.17.0/tools/viseme.py

**Comment by s-iwaki-d** [comment]
こちら技術委員会で議論させていただきましたが、プリセットに関してはいまの量が使い勝手がよいのではないかという結論となりました。拡張に関しては市場にまかせていきたいと思います。
