### ISSUE TITLE
SpringBoneの重複を禁止

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#149]
https://github.com/vrm-c/vrm-specification/blob/35e9c14cac83d75d528b35b66773dbb2e84385f1/specification/VRMC_springBone-1.0_draft/README.ja.md#springbone
一つのボーンが、複数のboneGroup.bonesの影響下に来ることを、仕様として禁止してはどうでしょうか。

現行のバーチャルキャストでは、そのような状態になっているモデルをサポートしなくなっています。

スタジオ関連｜モデルデータの表示がおかしい・崩れます。
https://virtualcast.jp/wiki/doku.php?id=tips:faq:studio_modelcollapse#vrmspringbone_%E3%81%AE%E8%A8%AD%E5%AE%9A%E3%81%8C%E9%96%93%E9%81%95%E3%81%A3%E3%81%A6%E3%81%84%E3%82%8B
> ✔ 良い例
> 揺らしたいボーンのルート要素のみがRootBoneとして設定されている
> ✖ よくない例
> 揺らしたいボーン全てがRootBoneとして設定されてしまっている

関連: #88 SpringBoneに、Exclusions機能をつけて頂けませんでしょうか

**Comment by esperecyan** [comment]
同様の状態のモデルは、UniVRMでもv0.57で未対応扱いになる予定。
https://github.com/vrm-c/UniVRM/issues/474

**Comment by 0b5vr** [comment]
1つのnodeが複数回jointとして登録されるのを明示的に禁止する旨を仕様に追記します。

@ousttrue さん、こちらの作業をお願いします。

**Comment by 0b5vr** [comment]
要旨は #362 で達成されました。
