### ISSUE TITLE
VRMC_springBone.center について

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#155]
現状、SpringBone 毎に個別に、シリアライズ しています。

案としては、

* シリアライズは削除して、実装の設定にする(デフォルトをモデルルートにする)
  * 選択肢は、
    * World
    * VRのラッキング空間のルート
    * モデルのルート

* 残しておいて、SpringBone 毎に個別に設定できる
  * 平行移動したときに髪がなびかなくなる
    * 平行移動したときに当たり判定がスプリングを追い越して暴れるかもしれない(おそらく初速が速いと顕著)
  * SpringBone 毎に違う値を設定している
  * 動きをマイルドにする目的ならシステムで一括指定でよさそう
  * 逆に特定のボーンの動きを動力源にする目的なら存在意義がありえる？
    * 使われている？

**Comment by FMS-Cat** [comment]
1.0において、SpringBoneのcenterのシリアライズは廃止されます。
0.0におけるcenter相当の機構が必要な場合、VRMの実装もしくはアプリケーションが対応を行う必要があります。
