### ISSUE TITLE
[1.0] MToon: Add a section about UV coordinates

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/vrm-specification#157]
tbd

- [ ] glTF仕様側のUV座標系の説明: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#images
    - 基本的にはこれに沿うとよさげ
- [x] UVスクロールについて。どっち向き？
    - Related: https://github.com/pixiv/three-vrm/pull/459
    - 先行事例等あれば助言いただきたいです

**Comment by FMS-Cat** [comment]
UniGLTFの実装では、モデルのインポート時に `TEXCOORD_0` のV軸をひっくり返しているようですね。

https://github.com/vrm-c/UniVRM/blob/12715778f0da7a042f614ff7cb28799e124efddf/Assets/VRM/UniGLTF/Scripts/IO/MeshImporter.cs#L66-L76

Blenderの公式実装も同様のようです。

https://github.com/KhronosGroup/glTF-Blender-IO/blob/6786505ebfda3587f3e735591f7341ec1a5909d3/addons/io_scene_gltf2/blender/imp/gltf2_blender_mesh.py#L496-L499

**Comment by FMS-Cat** [comment]
> UVスクロールについて。どっち向き？

これについて、 #192 で記述を行いました。

**Comment by 0b5vr** [comment]
> glTF仕様側のUV座標系の説明

これについては、とくべつVRM側の仕様で言及する必要はないと判断します。

本issueはクローズします。
