### ISSUE TITLE
[1.0] MToon: Add a figure explains each components

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/vrm-specification#158]
MToonで表現できる「Lit Color」「Shade Color」などの各コンポーネントについて、図でそれぞれが何に相当するかを説明できると良さそうだと思いました。

_Originally posted by @FMS-Cat in https://github.com/vrm-c/vrm-specification/pull/152#discussion_r462236984_

**Comment by Santarh** [comment]
図表よりも、ランバート反射の定義のように、拡散反射モデルの式を定義するほうが良いと思います。

**Comment by FMS-Cat** [comment]
#192 において、ある程度の図を追加しました。
その上で、反射モデルの式というわけではありませんが、疑似コードによる実装例を記述してみました。

**Comment by 0b5vr** [comment]
今後も理解を促進する図が用意でき次第提案を行っていきます。一旦本issueはクローズします。
