### ISSUE TITLE
[1.0] MToon: Add descriptions about Lighting

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/vrm-specification#159]
以下の項目について仕様を記述する

- `ShadingShiftValue`
- `ShadingToonyValue`
- `LightColorAttenuationValue`
- `GiIntensityValue`

**Comment by FMS-Cat** [comment]
#192 で対応しました。 `giIntensityFactor` の項のみまだ十分ではありません。

@Santarh 上記の件について、私もまだ挙動をよく理解できていないため、追記をお願いできますでしょうか？

**Comment by 0b5vr** [comment]
一通り記述が完了しております。クローズします。
