### ISSUE TITLE
BlendShapePresetの「fun」を廃止し「surprised」を追加

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#162]
https://github.com/vrm-c/vrm-specification/blob/a2054dfc4f520536d3a8dbdc204089129ae1782a/specification/VRMC_vrm-1.0_draft/README.ja.md#%E8%A1%A8%E6%83%85enum
BlendShapePresetの表情「joy」「angry」「sorrow」「fun」は、「喜怒哀楽」という四字熟語に当てはめての定義かと思います。しかしながら、「joy」と「fun」は区別があいまいで重複しており、「fun」は余剰のPresetとして使われる場合が多いように思います。

例: [THE SEED ONLINE](https://seed.online/)のプリセットアバター「シードさん」の「fun」
<img src="https://user-images.githubusercontent.com/3625160/89751413-ea94d600-db0a-11ea-9138-aebbe82c2ccb.png" width="200">

VRM-1.0に合わせて「fun」を廃止し、「joy」「angry」「sorrow」と明確に異なる表情として「surprised」の採用を提案いたします。

### カスタムアバターの表情で「surprised」を採用しているアプリケーションの例
- VRChat「mood_happy」「mood_sad」「mood_suprised」「mood_angry」
  https://docs.vrchat.com/docs/animator-parameters#default-av3-aliasing
- CharWebCam「Joy」「Angry」「Sorrow」「Surprise」
  https://github.com/xelloss120/CharWebCam#%E8%A1%A8%E6%83%85%E3%81%AE%E5%AF%BE%E5%BF%9C%E9%96%A2%E4%BF%82

**Comment by FMS-Cat** [comment]
#175 で議論し、funをrelaxedにリネームし、surprisedを追加する方針となりました。こちらのissueはクローズします。
