### ISSUE TITLE
BlendShapePreset の英語名を、形容詞に揃える「joy」→「happy」、「sorrow」→「sad」

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#163]
https://github.com/vrm-c/vrm-specification/blob/a2054dfc4f520536d3a8dbdc204089129ae1782a/specification/VRMC_vrm-1.0_draft/README.ja.md#%E8%A1%A8%E6%83%85enum
BlendShapePresetの表情について、「joy」「sorrow」の文字列を、それぞれ、形容詞かつより一般的でわかりやすい「happy」「sad」へ変更することを提案します。

名前 | 備考
-- | --
happy | うれしい
angry | 怒り
sad | 悲しみ
surprised https://github.com/vrm-c/vrm-specification/issues/162 | 驚き

**Comment by ousttrue** [comment]
#162 を踏まえて喜怒哀楽驚の英語名をここで検討したいと思います。

* 形容詞に揃える
* 英語的に変じゃない感じに

必ずしも日本語のカタカナ英語とニュアンスが同じでないかもしれない・・・

|日本語|英語vrm-0.x|英語vrm-1.0|
|--|--|--|
|喜 うれしい|joy 名詞 喜び| happy 形容詞 嬉しい |
|怒 怒り|angry 形容詞 怒った| angry 形容詞 怒った |
|哀 悲しい|sorrow 名詞 哀愁| sad 形容詞 悲しい |
|楽 楽しい(リラックスした)|fun 名詞 面白味 |relaxed 形容詞 平然たる|
|驚 驚いた||surprised 形容詞 びっくりした |

**Comment by FMS-Cat** [comment]
問題無さそうです！

**Comment by ousttrue** [comment]
変なところを更新していた。改めて、 expression ブランチに同じ内容を更新

**Comment by FMS-Cat** [comment]
#171 で対応ができたようなので、こちらはクローズします。
