### ISSUE TITLE
仕様に書きづらいことをガイドラインとして残したいが、どこが良いでしょうか

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#170]
仕様に書くにはあまりにも冗長すぎるが、でもアーティストやエンドデベロッパには指針として知っておいてほしい情報をまとめる場所が必要だと感じました。
おそらくはUniVRMと同様に、GitHub上にWikiを作って仕様側からリンクを貼る形が良いかなと想像しております。
どこに作るべきか合意が取れた時点で、このissueはcloseします。

**Comment by hiroj** [comment]
1.0用のガイドラインはいったん https://github.com/vrm-c/vrm.dev に追加していく方針にします。

**Comment by FMS-Cat** [comment]
ありがとうございます。当面はvrm.devに対してPRを投げていく形で対応したいと思います。

**Comment by ousttrue** [comment]
https://github.com/vrm-c/UniVRM/wiki

は、

https://vrm.dev/docs/univrm/

に引越ししました。
引越しした旨書いておきます。
サイトの管理が楽だったので実装よりの情報を wiki に書いていました。
github の wiki では量が増えてくると管理しづらいので引越ししました。

記事は、`content ` フォルダ配下のマーダウン形式です。
https://raw.githubusercontent.com/vrm-c/vrm.dev/master/content/ja/docs/univrm/install/univrm_install.md
