### ISSUE TITLE
[1.0] VRM_springBone -> VRM_spring_bone

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#172]
一つだけ拡張の命名においてケースの規則が違うのが気になりました。

**Comment by ousttrue** [comment]
https://github.com/KhronosGroup/glTF/blob/master/extensions/README.md

あたりを見て

`ベンダー_category_name`

* ベンダー: 大文字
* category: lowerCamel ?
* name: lowerCamel ?

になってるのが多いような気がしたのだけど、どうなんだろう

**Comment by FMS-Cat** [comment]
カテゴリなるほど……。そうすると `VRMC_dynamics_spring_bone` もしくは `VRMC_dynamics_springBone` とかが良かったりするんですかね。ますます迷う
個人的には `VRMC_spring_bone` で十分な気がしています……が、たしかにclothとか将来的に入れるとなると、 `VRMC_dynamics_cloth` とかは適切な気がしますね……

**Comment by FMS-Cat** [comment]
一旦このままとすることで合意が取れました。 `spring` と `bone` が分かれると、 `spring` のカテゴリの `bone` なのかと勘違いしそうなため
