### ISSUE TITLE
[VRMC_vrm][1.0draft] Material Priority

### ISSUE THREAD

**Issue by tarepan** [vrm-c/vrm-specification#174]
## Summary
Both Toon and Unlit materials are required, but there is no priority.  
Implementer cannot judge "Which shading model should be used", and it will break **appearance consistency / 見た目の一貫性** across platforms.  
We need material priority information in this spec.  

## Config
spec in master 7f9ae0baf8f1fdc6c3e0850338324dc699eaa3cf

### Current Status
Current VRMC_vrm spec requires two material extensions, `VRMC_materials_mtoon` & `KHR_materials_unlit` as Toon & Unlit shading.  
Both materials are required, and there is no information of **priority**.  
### Expected Problems
Some VRM-loader implementer could implement "unlit-first" shader setup, and other could implement "toon-first".  
This **break appearance consistency / 見た目の一貫性 across platforms, which is core soul of VRM**.  

## Proposal
We can solve this problem with **material priority** description in this spec.  
There could be many solution, so belows are my examples of solution.  

- Approach A: "**Priority: `VRMC_materials_mtoon` >  `KHR_materials_unlit`** in material section
- Approach B: "**unlit is for xxx, so use toon shading model with `VRMC_materials_mtoon` at first**" in "Best practices" section (c.f. [`Best practices` section in `KHR_materials_pbrSpecularGlossiness`](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness#best-practices))  
  

## Comment
Thanks for great specification, I love VRM.  

I personally failed to understand the intent of `KHR_materials_unlit == required`.  
Is it for fallback in VRM-incompatible platform...?

**Comment by FMS-Cat** [comment]
Related discussion: https://github.com/mrdoob/three.js/issues/20709

I'll update with more description tomorrow.

**Comment by FMS-Cat** [comment]
I think we will take the "Approach A", `VRMC_materials_mtoon` takes priority over `KHR_materials_unlit`, using unlit material only as a fallback.
But there are no existing extensions that takes priority before other extensions in any (public) glTF extension so far; Implementation might be difficult a bit.

**Comment by FMS-Cat** [comment]
We are going to make it a specification!
