### ISSUE TITLE
[1.0] meta に require が足りない

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#178]
Title, Author, Version

**Comment by saturday06** [comment]
0.x系では、requireを付ける代わりに[json schemaのdefault](https://json-schema.org/understanding-json-schema/reference/generic.html)を用いてデフォルト値を指定することを提案します。requireを使った方式にしてしまうと、現行のVRM 0.0のデータをシステムがどう扱ってよいのか分からなくなってしまいますが、defaultでデフォルト値を指定することでVRMの仕様バージョンアップ時に自動でそのデフォルトの値で埋めることができます。

ひとまず叩きとして、下記のようなデフォルト値を提案します。英語に詳しい人にレビュー頂きたいです。
| Titleのデフォルト | Authorのデフォルト | Versionのデフォルト |
| --- | --- | --- |
| No name | Unknown | 0.0 |

**Comment by esperecyan** [comment]
関連 https://github.com/vrm-c/vrm-specification/issues/72 JSON Schema において制約を定義する

**Comment by saturday06** [comment]
あるいは、 `0.0` から `0.1(仮)` あるいは `1.0` にバージョンアップする場合に当該項目が空白なら、デフォルト値を入れるという仕様をこのレポジトリの仕様書に記載しておくのでも良いと思いました。

**Comment by saturday06** [comment]
よく見ると `contactInformation` とかもrequiredついて無いので、`0.1(仮)` にする際はこれらにもデフォルト値を指定お願いしたいです。

**Comment by saturday06** [comment]
`contactInformation` は必須にする必要は無いかも。 `licenseName` などは事実上必須だと思うしUniVRMがデータを読むときに自動的に一番厳しい値で埋めるので、それをデフォルトの値として仕様としてしまえればスムーズですね。

**Comment by esperecyan** [comment]
現在のVRM-1.0仕様書草案では、`name`、`version`、`authors` が必須となっていますが、これが空文字列を許容しないという意味なのか、空文字列を許容し他のプロパティ自体が存在しなくても良いという意味なのかは不明瞭です。
https://github.com/vrm-c/vrm-specification/blob/7f9ae0baf8f1fdc6c3e0850338324dc699eaa3cf/specification/VRMC_vrm-1.0_draft/README.ja.md#%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AE%E3%83%A1%E3%82%BF%E6%83%85%E5%A0%B1

JSONスキーマの `required` は空文字列を許容するので、UniVRM-0.61.1の挙動に合わせるなら、プロパティに対する `required` と、文字列に対する `minLength` か `pattern` が必要になります。
https://json-schema.org/understanding-json-schema/reference/string.html

**Comment by FMS-Cat** [comment]
口頭で議論を行いました:

- `title` , `author` について、空文字を許容しないrequiredとする
- 0の仕様については現状維持
- 0から1へのアップデートの際はこれらにデフォルト値を付与する方針とする
    - UniVRMでアップデートを行う際は、optionalのパラメータでデフォルト値を指定できると良さそうです
    - 若干本題から外れますが、Migration Guideをしっかり書いたほうが良さそうだねという話をしました

**Comment by esperecyan** [comment]
`title` (`name`), `version`, `authors` 以外のプロパティについては、プロパティ自体が存在しなくても良いという解釈になりますか。それともプロパティは必須で、空文字列を未指定とみなすという解釈になりますか。

**Comment by ousttrue** [comment]
#184

無ければライセンス的に厳しい方で解釈するということで、
JsonSchema に default 値を指定しました。

**Comment by FMS-Cat** [comment]
`version` はrequireから外しました。
`name` `authors` が必須となります。schema上は空文字を許容する定義になっていますが、空文字を許容しない方針で仕様を記述します。
それ以外のプロパティについては、プロパティ自体が存在しなくてもvalidとして扱います。
VRM 1.0のmetaについては、これでfixの方針です。
closeします。

**Comment by esperecyan** [comment]
@FMS-Cat 必須でないプロパティに対する空文字列や、文字列の配列に空文字列を含めることは許容されるのでしょうか？

例

```json
{
    "authors": ["author", ""],
    "copyrights": ""
}
```

**Comment by esperecyan** [comment]
@FMS-Cat `version` requireのままになってるみたいです。closeされたこのissueにしか情報がないと思うので、漏れないうちに早めに修正(or 完了するまで再open)した方が良いかと思います。
https://github.com/vrm-c/vrm-specification/blob/5c4d1755ec9190f7e0145ad908426307b294e391/specification/VRMC_vrm-1.0_draft/README.md#models-meta-information

**Comment by FMS-Cat** [comment]
リマインドありがとうございます！やらなきゃ

**Comment by FMS-Cat** [comment]
> @FMS-Cat `version` requireのままになってるみたいです。closeされたこのissueにしか情報がないと思うので、漏れないうちに早めに修正(or 完了するまで再open)した方が良いかと思います。
> https://github.com/vrm-c/vrm-specification/blob/5c4d1755ec9190f7e0145ad908426307b294e391/specification/VRMC_vrm-1.0_draft/README.md#models-meta-information

本件、 #201 で着手しました！
