### ISSUE TITLE
SpringBone, The behavior of stiffness and external depends on the length of the bone

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#179]
StiffnessとExternalの挙動は、ボーンの長さに依存します。
つまり、長いボーンと短いボーンで同様の揺れ方をさせようとすると、stiffnessとexternalの大きさをボーンの長さに比例で調整する必要があります。
これは、もしかしたらボーンの長さに関係なく同じstiffness・externalの値にしたら同様の挙動になったほうが好ましかったりしませんか？
Breaking Changeとなるため、むやみに変更しづらい部分ではあります。

実装にすると以下の箇所です:

https://github.com/vrm-c/UniVRM_1_0/blob/3138de1fd98550b9879bc96857e95d468e46f537/Assets/Vrm10/UniVRM10/Components/SpringBone/SpringBoneLogic.cs#L90-L91

**Comment by FMS-Cat** [comment]
口頭で議論をしました。

- FMS_Cat: 実験して出直します
- ousttrue: SpringBoneのデータの持ち方の検討が終わってから見直したいです

**Comment by ousttrue** [comment]
実装上の変更について。

head, tail のペアの作り方を、(bone, children[0]) から (parent, bone) という組の作り方に変えようとしています。

* 途中で枝分かれしても個別に処理できる
* 末端にダミーの tail 追加が不要になる

* bone0(ここにスプリング設定がある)
  * bone00
    * bone000
  * bone01
    * bione010

という木が合った場合に

0
```
(bone0, bone00)
(bone00, bone000)
(bone000, 0.07) # 末端にダミーを追加する
```

1
```
*(bone0, bone00)
*(bone00, bone000)
*(bone000, 0.07) # 末端にダミーを追加する?
*(bone0, bone01)
*(bone01, bone010)
*(bone010, 0.07) # 末端にダミーを追加する?
```

1でも末端へのダミー追加はした方がよさそうか

**Comment by FMS-Cat** [comment]
https://frequent-special-radon.glitch.me

デモを作ってみました。

stiffnessをボーンの長さに応じて乗算した場合、振れ幅とボーンの長さを比例でスケールした際に揺れ方が等しくなるというご利益がありますが、いまひとつそれ以外のご利益は分かりづらいですね。どちらかというと、stiffness値をめちゃくちゃに大きくしなきゃいけないのが面倒そう……
だんだんナシ寄りの気分になってきました。

**Comment by FMS-Cat** [comment]
VRM1.0においても、現状ままとします。クローズ
