### ISSUE TITLE
Where is the origin of LookAt?

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#18]
LookAtを実装するにあたり、注視点への方向を定義するベクトルの始点はどこでしょうか？
Specには

> from the model's head to the target.

と記述されていますが、この `model's head` は具体的には何を表しているでしょうか？

Spec: https://github.com/vrm-c/vrm-specification/tree/master/specification/0.0#eye-control-settings

UniVRMの実装では、頭のボーンが指定されています。
しかし、頭のボーンはおおよそ頭と首のトランジションに属することが多いため、
個人的には、FirstPersonの位置を始点とする定義にするのが適切かと思います。

**Comment by hiroj** [comment]
始点はFirstPersonBoneで指定したボーンの座標とFirstPersonOffsetを足した座標になります（正規化されていることが前提）
Headの座標そのままだと首の付け根あたりになってしまうため、眉間辺りを指定するためにOffsetを設けてあります。

**Comment by FMS-Cat** [comment]
1.0のdraft specでは、

> `HeadBone` (normally it's FirstPersonBone)

と記述がありますが、これは何をHeadBoneと捉えるかを実装に任せるという認識でよろしいでしょうか？

https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#lookat-algorithm

**Comment by hiroj** [comment]
実質 Head以外を設定することはないため、firstPersonBone の項目自体を廃止しても良いのではと考えています。（humanoidによってheadのnodeは分かっているため）
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/vrm-1.0_update.xlsx
こちらの変更点表に少し書いてありました。

**Comment by hiroj** [comment]
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#lookat-algorithm
FirstPersonBoneはHeadBone固定の仕様になり、選択出来ないようになりました
