### ISSUE TITLE
Metaのマイグレーションルールを決める

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#181]
既存のモデルを新しいアプリでロードするために自動でできることが必用。
ダウングレードに関しても、ガイドラインを検討する。
メタの内容が固まってから。

**Comment by FMS-Cat** [comment]
ダウングレードは禁止する気候です。

**Comment by FMS-Cat** [comment]
技術委員会で検討を行った結果、Metaのマイグレーションは禁止する方針となりました。
0.0と1.0ではライセンス形態が大きく異なり、互換性がないと判断したためです。

もし今後アプリケーションが0.0のモデルを使用したい場合、アプリケーションは0.0と1.0双方のMeta情報への対応が必要です（それ以外のマイグレーション機構は実装で提供します）。
もしモデル製作者がモデルを0.0から1.0に変換したい場合、モデルのライセンスをモデル製作者自らが1.0に変更する必要があります（即ち、ユーザの介入を伴わない自動での0.0から1.0への変換は許容しません）。
