### ISSUE TITLE
[1.0] Expressionのneutral、結局どうするんでしたっけ？

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#185]
Issue掘り起こしても見つからなかったのでIssueを建てさせてください。
Neutralについて、消すような消さないような議論が発生したと思いますが、結局どうするんでしたっけ？
以前口頭で議論したのであれば、それはど忘れしています。ごめんなさい。

**Comment by ousttrue** [comment]
`Neutral` は現状、UniVRM ランタイムでは使ってません。

次くらいで、
https://github.com/vrm-c/UniVRM/issues/485
をやる予定です(これも、任意のExpressionをプルダウンで選択できるようにしたらよさそうな気がしました)。

ランタイムにExpression管理が Neutral にクリアするようにするのは、

* 既存のコードの動作が変わる
* コードが煩雑になりそう(LookAt、Blink, LipSinc等が干渉する可能性を考えると筋があまりよろしくない)

で実装してなくて、そのままになっております。

1.0 では消して、
標準の表情はこれっていうのを示したい場合は
`Custom Neutral` などで代替するでいいんでないかと考えております。

**Comment by FMS-Cat** [comment]
https://github.com/vrm-c/UniVRM/issues/485 の議論、なかなか興味深いですね。
1.0でneutralは廃止し、実装側で既存のneutralを用いたアバターについてはNeutralをベイクしてしまえば良さそうと私も思います。

Expression（旧BlendShapeGroup）が何もあたっていない状態とNeutralを分けて管理することに何か意義があり、それを私が見落としていないかが少し不安です。
モーフは1次線形補間でしかないので、Neutralが無くなったところでできなくなることは無いと信じているのですが……
あえて言えば、Expressionの合計値が1を超えるような使い方（AaしながらJoyするケースなど）をしているケースにちゃんと対応ができるかが不安です。
アプリケーション開発者に少しヒアリングをしてみると良いかもしれないですね。

**Comment by ousttrue** [comment]
関連して https://github.com/vrm-c/UniVRM/issues/603

**Comment by FMS-Cat** [comment]
昨日、akiraさんに相談して色々ヒアリングしてみたのですが、
モデラーではないユーザーが、BOOTH等で販売されているアバターに対して、Unity上でNeutralを用いて無表情を作りたいという需要があるようです。

現状のNeutralについて、VRMの実装で特に扱われていないこと、VRMでそれをどう扱うべきかが明記されていないことが問題点でありますので、
Neutralがどのように使われるべきかを明記すれば良いと思います。
で、それは実装上では、アプリケーション側に対応を要求するのではなく、VRMの実装側で吸収すべきだと思います。

具体的には、Neutralおよび感情を表すExpression（Happy・Sadなど）については常にWeightの総和が1.0になるようにmixを行い、
そのmixを行う処理はVRM内に隠蔽するのが良いかなと思いました。

**Comment by ousttrue** [comment]
> Neutralを用いてmorphを組み合わせ、無表情を作りたい

* そのユーザーは VRM化作業自体はやっているので、かわりに bake してもらっても大丈夫な気がします

> VRMの実装側で吸収

* bake した方が楽なので・・・
* VRMBlendShapeProxyが複雑になるのを回避したい #189

そのうえで、Neutral の例を含めたい場合は `Custom Neutral` を使う慣習でよさげな。

**Comment by FMS-Cat** [comment]
一つ明らかにしたいのですが、bakeというのは、Neutralを加算分を何にbakeしていますか？
Neutralのモーフがもとのメッシュに対して加算されるのはイメージできるのですが、
他の表情（HappyやBlinkなど）からは減算されるのでしょうか？
なんとなく、HappyやSadなどの感情を表すExpressionからは減算されると想定しています。
ちなみに、これはUniVRM側で明記されるべき仕様です。

**Comment by FMS-Cat** [comment]
社内でディスカッションを行った結果、やはりNeutralが必要そうという意見に変わってきました。
元はと言えばこの問題の起点は、なぜNeutralが必要かという説明がクリエイター・デベロッパー双方にされていなかったことにあり、
今一度Neutralをベースの顔と別に用意することの有用性を考え、クリエイター・デベロッパー双方に伝えるべきだと思います。

おそらく、本来想定されていた用途は、モデルのベース表情とは別にNeutralを用意し、口パクの際にそれがNeutralと干渉し破綻しないように制御するものであったと想定します。
この使い方であれば、たしかにNeutralの存在意義はあるのではないかと思います。
他になにか本来想定していた用法はありますでしょうか？

また逆に、 vrm-c/UniVRM#485 で議論されているような、体型変化にアサインされるBlendShapeをVRMのBlendShapeProxyで制御するのは、VRMのスコープ外であり、VRMで扱う必要はないと認識しています。

**Comment by ousttrue** [comment]
> 他の表情（HappyやBlinkなど）からは減算されるのでしょうか？

たぶん yes ？ 細かいことは

https://github.com/vrm-c/UniVRM/blob/master/Assets/MeshUtility/Runtime/BoneNormalizer.cs#L359

読んでくだせい。
`0.62.0` までバグってたのですがなおってます。
https://github.com/vrm-c/UniVRM/issues/603

neutral は

> 口パクの際にそれがNeutralと干渉し破綻しないように制御するもの

ということはなくて、 enum 作るときになんとなく作ってます。
結果として VRMBlendShapeProxy には実装がありませんでした。

使っているアプリケーションもあると思いますが、 
その場合は VRMBlendShapeProxy に頼らずに何とかしているはずです。

とすれば、

* `Custom Neutral` で引き続き同じ使い方をする
* bake する

のどちらかで吸収できると考えております。

**Comment by yahagi-day** [comment]
現状、Neutralを使用する主な理由はアバター製作者が設定したデフォルトの表情と別の表情を通常時の表情にしたい時だと思います。
なので表情をBake出来るようになった現状ではNeutralは削除してもいいんじゃないかなと思います。

またNeutral（もしくはCustomNeutral）を残す場合それを通常時の表情と見なしてweightを1にし続けのかがアプリ毎によって違うのは良くないのでVRM側の実装で対応して欲しいです。

**Comment by pixiv-sigepon** [comment]
FMS_Catとディスカッションを行った上で、まとめた上意見を書いてもらっていますが私の方からNeutralの扱いについて補足したいと思います。
Neutralが削除する方向性になっていますが

Neutralは必要です。
なぜ必要か
・元の顔の法線情報などをモデルを製作段階で元の顔は無表情であるのがデータ的に正常な状態を担保できる
（例えば、口をあらかじめ固定の表情で閉じてるような顔をベースにしてしまうと口元の陰影がおかしくなってしまったりします）

・Neutralは、ベース表情とは異なる通常時そのそのキャラのキメ顔である（キメ顔は、通常時の表情として呼び出すものでモデルのベースにするべき表情ではない）

・NeutralをBakeする処理の大本のissueを立てた方が、そもそもNeutralの扱いを間違えており、間違えた扱いからBakeに飛躍してしまっている。
元々のissueを立てた方は、Neutralに胸のサイズの変更に使い。それが全てに適用すると勘違いしていた。
そもそも、BlendshapeProxyの概念の理解が間違っている

この問題の真の点のと正しい解決方法
・クリエイター、デベロッパーにBlendshapeProxyのClipをどう扱うかをVRMという規格のガイドラインとして双方に周知できていないのが最大の問題。
そもそも、喜怒哀楽などのClipはどういう風に扱う思想で用意されたのかが説明不足である。

・また、VRMの規格として用意されたClipをどのように扱うかをデベロッパーに説明なしに委ねすぎて、破綻などの問題がクリエイター、デベロッパー固有に起きている。
そのため、この問題の真の解決はクリエイター、デベロッパーに規格として用意したものの扱い方を周知する、またサンプルを用意すること

・各クリップどのような状態がベストなのか、そしてそれをどう扱えばいいのかがちゃんと双方に伝えられていない状態で、NeutralをBakeする処理はワークアラウンド的処置であり望ましいものでないです。
Neutralとベースを切り分ける重要性はモーションを流し込む前のTポーズと同じような関係性です。

・ベースモデルに、表情付けを行わないほうがいい理由を以前解説したスレッドです。
[](https://twitter.com/m_sigepon/status/963163125225635840)

**Comment by FMS-Cat** [comment]
>> 他の表情（HappyやBlinkなど）からは減算されるのでしょうか？
>
> たぶん yes ？

これだと、瞬きとAを同時にすると、Neutralの減算が2回発生することになってしまいますが、大丈夫でしょうか。

**Comment by ousttrue** [comment]
うーん、わからん・・・

**Comment by FMS-Cat** [comment]
Neutralの名前を、より明示的に用途を示すものに変更すると良いかと思いました。
今BakeしようとしているNeutralは、どちらかというと「Static」、常に1であることを明示的に示す名前であるのが望ましいかと思います。

しげぽんさんのおっしゃっていた口の問題はおそらくまた性質の違う問題だと思いますので、Sil（閉じ口状態）に相当するExpressionを追加するのでも対応できるかもなと思いました。

いずれにせよ、それぞれのExpressionがどのように重複で使われる可能性があるのかを明示すれば良さそうと思います。
たぶん、Neutral+表情+口+瞬き+視線で、それぞれのWeightの合計は基本的には1を超えることは無いのかなと思っています。

**Comment by FMS-Cat** [comment]
口頭で議論を行いました。

- Neutralは残します。
    - コミュニティが積極的に活用すれば、あっても無駄ではないのではないかと思います。
- 具体的な使い方を制約するものではありませんが、以下のような使い方が想定されます:
    - 他の感情系のExpression（HappyやSadなど）と合わせて使うことを想定する
        - ただし感情のSumを1とは制約しない
    - 瞬きや口パクは同時に発生するので、干渉しないようにExpressionsを設定する必要がある
