### ISSUE TITLE
PermissionのxxUssageNameは意図したものでしょうか (usageのtypo?)

### ISSUE THREAD

**Issue by toris-birds** [vrm-c/vrm-specification#19]
[Permission / License information](https://github.com/vrm-c/vrm-specification/tree/master/specification/0.0#permission--license-information) の xxUssageName は、xxUsageName の typo ではありませんか?

該当項目:
json.extensions.VRM.meta.violentUssageName
json.extensions.VRM.meta.sexualUssageName
json.extensions.VRM.meta.commercialUssageName

**Comment by hiroj** [comment]
これらはTypoしているため、VRM1.0のspecで修正予定になります。

**Comment by hiroj** [comment]
以下のVRM1.0draftのschemaにて修正を行いましたのでよろしければご確認ください
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/schema/VRMC_vrm.meta.schema.json
