### ISSUE TITLE
「各種名前の制約」の「ファイル名に使える文字にする」が曖昧

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#190]
VRM-1.0の仕様に以下のようにありますが、「ファイル名に使える文字にする」という制約は曖昧すぎると思います。
https://github.com/vrm-c/vrm-specification/blob/4693e459cbc4e5cc5123d4ebe6d0ab8f930c60df/specification/VRMC_vrm-1.0_draft/README.ja.md#%E5%90%84%E7%A8%AE%E5%90%8D%E5%89%8D%E3%81%AE%E5%88%B6%E7%B4%84
> ## glTF Schema Updates
>
> (中略)
>
> ### 各種名前の制約
> - ユニークにする
> - ファイル名に使える文字にする

「con.png」などは、どのファイルシステムにおいても妥当な名前ですが、Windowsエクスプローラーなどでは扱えません。また、たとえば「.」で始まる文字列は、同じくどこでも妥当な名前ですが、Unityエディタのアセット名には使用できません。
- https://github.com/vrm-c/UniVRM/issues/611 メッシュ名が「.」で始まるとインポートに失敗する

### 関連
- https://github.com/vrm-c/vrm-specification/issues/40 [1.0draft] unsafe chars escape example is imperfect.
- https://github.com/vrm-c/UniVRM_1_0/issues/78 [1.0draft][impliment]make Blendshape files from them belongs to BlendshapeGroup.

**Comment by ousttrue** [comment]
この件、 vrm 仕様側では深入りしないつもりです。

Unity で Asset 化する(ファイル化する) ときに固有の問題で、 VRM フォーマットの関知しないレイヤーだと考えてます。
逆に節を削除してもよいかもしれない。

* 安全でない名前のエスケープ例

も同様。

**Comment by esperecyan** [comment]
自分も仕様から節の削除を支持します。
