### ISSUE TITLE
meta.「authors」「copyrights」「otherPermissionUrl」の統合

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#194]
https://github.com/vrm-c/vrm-specification/blob/4693e459cbc4e5cc5123d4ebe6d0ab8f930c60df/specification/VRMC_vrm-1.0_draft/README.ja.md#%E3%83%A2%E3%83%87%E3%83%AB%E3%81%AE%E3%83%A1%E3%82%BF%E6%83%85%E5%A0%B1
モデルのメタ情報 `extensions.VRMC_vrm.meta` のプロパティ、
- `authors`
- `copyrights`
- `otherPermissionUrl`
は、まとめて示すことが多く、分割して書くのは難しいと思います。

フォーマットの制限がない一つの文字列プロパティへ統合し、適宜改行することを推奨するといった形にはできないでしょうか。

### 関連
https://github.com/vrm-c/vrm-specification/issues/51 [suggestion][1.0draft]著作権者等表示について

**Comment by s-iwaki-d** [comment]
こちら技術委員会で検討させていただきましたが、それぞれの役割・機能が異なるので統合は難しいと結論しました。
AuthorとCopyrightの概念を分離しているのは、モデル作者とキャラクターの著作権者が概念として異なる場面で使い分けることを想定しています
