### ISSUE TITLE
meta.reference (親作品) の廃止

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#195]
作品の親子関係などは、1ファイルで完結した形式であるVRMファイル内で定義するのではなく、ニコニ立体のようにリポジトリ側の機能に任せるのが良いのではないでしょうか。

### 関連
- https://github.com/vrm-c/vrm-specification/issues/194 meta.「authors」「copyrights」「otherPermissionUrl」の統合
- https://github.com/vrm-c/vrm-specification/issues/51 [suggestion][1.0draft]著作権者等表示について

**Comment by s-iwaki-d** [comment]
作品の親子関係をファイルから分離してリポジトリ側の責務とすると、リポジトリ/サービスをまたいだ親子の表現が難しくなってしまいます
