### ISSUE TITLE
Undeclared of "VRM's" T-pose in this repository.

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#20]
このリポジトリにはT-poseの定義がありません。
　また、 [VRM/T-pose](https://vrm.dev/docs/dev/vrm/vrm_tpose/) には、一応の説明がありますがUnity依存なので、VRMとして独立した仕様としてのT-poseの詳細な定義をお願いします。

　基本姿勢、許容されるジョイントの位置関係等、お願いします。
(e.g:upperArmとLowerArmのYZは完全に等しくないといけない{または許容されるずれ}、head->lowerlegのZはXZ面に垂直に一直線に結ばれ(る || る必要はない) 等)

**Comment by hiroj** [comment]
以下のVRM1.0draftのドキュメント内にT-poseの定義情報を追加しました。
不鮮明な点等ある場合はご意見頂けると助かります。
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E3%83%92%E3%83%A5%E3%83%BC%E3%83%9E%E3%83%8E%E3%82%A4%E3%83%89

**Comment by iCyP** [comment]
まず、向きというより、親とのオフセット・位置関係、の方がわかりやすいと思います。(gltfのはジョイントなのでボーンの向きという概念自体混乱すると思います。

[浮動小数点で有効な距離](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E3%83%92%E3%83%A5%E3%83%BC%E3%83%9E%E3%83%8E%E3%82%A4%E3%83%89%E3%82%B9%E3%82%B1%E3%83%AB%E3%83%88%E3%83%B3%E4%BB%95%E6%A7%98)
 - double?float?harf? fixed? 具体的な値を書くべきと思います。

[body](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E8%83%B4enum)
 1.  inverted pelvis の説明について、骨盤に相当するボーンとはつまりspineでしょうか。それともIn between boneを含みますか？
 2. spine について、仙骨の土台部分と解していたのですが、骨盤の上端では腸骨稜がそれにあたると思います。後者なのでしょうか？
 3. chest について、これは胸郭の下端に近しい高さの腰椎という意味でしょうか？それとも内臓あたりでしょうか？
 4. neckについて、頚椎の一番下という意味でしょうか？それとも頚窩から適当に(という表現は良くない)奥行にオフセットした場所という意味でしょうか？

[shoulder](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E8%85%95enum)
　5. つまるところshoulderは鎖骨の付け根という事で良いですか？

[finger](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E6%8C%87enum)
　6. ThumbProximalのY軸に対し ”45度” 開く仕様はなくなりましたか？
　7. ThumbProximalの向きの+Zは逆ではないでしょうか。これでは掌が上を向かざるを得ないと思います。

[正規化](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E6%AD%A3%E8%A6%8F%E5%8C%96%E3%81%AE%E3%82%A2%E3%83%AB%E3%82%B4%E3%83%AA%E3%82%BA%E3%83%A0)
 > skin.root に対しするBoneWeightを付与する

typo?

**Comment by hiroj** [comment]
ドキュメントの方少し修正しました、分かりにくい部分がある場合は再度issueを立ててください。
