### ISSUE TITLE
[1.0, Meta] thumbnailImage

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#200]
thumbnailImageは image でしょうか？ texture でしょうか？

three-vrmでは、0.0においては、textureのつもりで開発を行っていました。

Webアプリケーションなどの画像ファイルが簡単に扱えるプラットフォームにおいては、 image だとテクスチャにする手間を省けて便利かと思います。また、samplerも特に指定する理由は無いため、十分と思います。
一方で、テクスチャ拡張を扱いたい場合向けにtextureで定義しておくと便利だったりするかもしれません。

**Comment by ousttrue** [comment]
0.0 では、 UnityのTexture2Dを追加する的な実装になってました。
エクスポーターがマテリアルのテクスチャーエクスポート関数を流用してたと思います。

1.0 では明確に image でよさそうな気がしますね。
offset + scale とかが設定できても、ややこしいので。

**Comment by FMS-Cat** [comment]
承知しました。ひとまず、いまMetaの仕様を作文していますが、imageで統一して記述してみます。

**Comment by FMS-Cat** [comment]
本件、imageがpngかjpgであることを保証したいので、ここのimageについてはpngかjpgで格納することを仕様としたいです。

**Comment by FMS-Cat** [comment]
この旨を仕様に記述した後、本Issueはクローズします。

**Comment by FMS-Cat** [comment]
現状の `meta.ja.md` に書いてありそうなため、閉じちゃいます。
