### ISSUE TITLE
「各種名前の制約」の「ユニークにする」という制約は強すぎるので削除するかモーフターゲット名に限定したい

### ISSUE THREAD

**Issue by saturday06** [vrm-c/vrm-specification#202]
VRM 0.xの時点ではblendshapeのmaterialbindなど名前を参照していて、そこから安全側に倒してすべての名前をユニークにするという制約が生まれたのだと思います。しかし1.0ではその制約は不要となり、現状の1.0の仕様としては制約が強すぎると思うため削除するかモーフターゲット名の重複のみNGとしたいです。

最近VRMモデルを作って遊ぼうとしていて、Headという名前のボーンとHeadという名前のメッシュを共存させていたら制限に引っかかっていることに気づいてしまいまして。。。

**Comment by FMS-Cat** [comment]
関連するものとして、名前関連の議論は #190, #197 でされていましたね。
「ユニークにする」という制約については、 #197 でもまだ残ったままとなっております。

**Comment by ousttrue** [comment]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E5%90%84%E7%A8%AE%E5%90%8D%E5%89%8D%E3%81%AE%E5%88%B6%E7%B4%84

**Comment by FMS-Cat** [comment]
システムとしては意味を持つ名前はExpressionsのCustomの場合のnameのみとなる。そこだけは重複してほしくないが、それ以外は重複しても仕様的には問題なさそうです。
なので、「各種名前の制約」の節から「ユニークにする」は取っ払い、Expressionの名前についてのみ名前の重複をinvalidとする旨を仕様に追記する方針で対応します。

**Comment by FMS-Cat** [comment]
@saturday06 本issue、現状の仕様文を見た上でclose可能か判断いただきたいです。

**Comment by saturday06** [comment]
確認しました。対応ありがとうございます！
