### ISSUE TITLE
MToonのmatcapにマスク・光源影響を追加したい

### ISSUE THREAD

**Issue by OGOG-Ogura** [vrm-c/vrm-specification#204]
matcapにマスクを適用することで部分的に光沢を加え、服でスパンコールの表現などが可能になります。
現状の仕様では光沢表現をしたい箇所のメッシュを分割し、別のマテリアルを割り当てるという作業が必要になりますが、場合によっては頂点数やマテリアル数が膨れ上がってしまいますのでMaskを適用できるようにしていただきたいです。

Maskの白黒テクスチャにおいて、グレーの部分はスムーズに加算される仕様となれば嬉しいです。

**Comment by FMS-Cat** [comment]
共感できます！

仕様として追加できるかは今後技術委員会で議論してみます。
一旦は、メッシュ・マテリアルを2つ組み合わせて、一方のマテリアルをスパンコールの形状でアルファで抜いてMatCapを適用する方針が適切かと思います。

**Comment by FMS-Cat** [comment]
@Santarh 本議論について、Parametric Rim側にマスクおよび光源影響があることを意識した上で、MatCapにマスクと光源影響を足せないかを議論してみたいです。

**Comment by Santarh** [comment]
MatCap に光源影響が存在しないのは歴史的経緯に依るものなので、あると良いことには同意します！

MatCap は Parametric Rim の上位互換たるもの（正確には、テクスチャがデジタル画像であるため離散化による劣化はある）ものなので、二者は統合してよいと私は思います。

コードで表すなら、次のようにすると良いのではないでしょうか。
```
finalColor += lerp(1, lighting, _LightingMix) * mask * (matcap + parametricRim);
```

パラメタも最小限に抑えられ、かなりシンプルになります。
ただデメリットとしては「MatCap は Emission として、Parametric Rim はライト影響を受けて、どちらも使用する」
場合が表現できなくなるので `VRM 0.x` からの migration ができなくなります。
しかし、このシチュエーションは多くは求められるものではないと考えるので、仕様のシンプルさのために切り捨てて良いのではないかなと考えます。

**Comment by FMS-Cat** [comment]
フィールド名の検討は進んでいませんが、一旦上のSantarhさんの実装を仕様とする方針とします。

**Comment by FMS-Cat** [comment]
#192 で対応。

上のSantarhさんの提案にあるように、 `rimMultiplyTexture` というテクスチャがMatCapに対するRGBのマスクとして作用するような仕様としてみました。

@OGOG-Ogura いかがでしょうか？

**Comment by 0b5vr** [comment]
VRM1.0-beta の時点で、VRM1.0では上記の `rimMultiplyTexture` が利用可能です。クローズします。
