### ISSUE TITLE
右手系Y_UP, -Z_Front を 右手系Y_UP, +Z_Front に変える(Y軸180度回転)

### ISSUE THREAD

**Issue by TokageItLab** [vrm-c/vrm-specification#205]
まず第一に GLTF2 の仕様としては Y UP の右手座標系を用いるという事があります。そもそも右手座標系では + が正面ですが、 VRM は -Z が正面になっており GLTF2 モデルとしては異常です。これは左手座標系の Unity における入出力を最優先した結果、本来であればインポーター及びエクスポーターで座標系を変換すべき所を変換をせずに入出力した結果に他なりません。これにより Unity 外での入出力に混乱が生じたり、既存の GLTF インポータ等を容易に再活用できない(※1)等、統一規格としては大きな欠陥であると同時に GLTF2 の標準性も破壊しかねない仕様であると考えます。

従って全てのデータの座標系を GLTF2 の仕様である Y UP の右手座標系、 +Z フォワードに統一するように変更をすべきであると提言致します。（互換性が完全に破壊されるので、変更するタイミングはメジャーアップデート時しかないと思いますが...）

First of all, GLTF2 uses the right-hand coordinate system of Y-UP as its specification. In the right-hand coordinate system, + is the front, but VRM is facing -Z, which is not compatible with the GLTF2 model. This is a result of focusing only on Unity's left-hand coordinate system input and output, and not on converting the coordinate system. Although the importer and exporter should to be converted the coordinate system, they are not doing it. This causes confusion in input and output outside of Unity, and prevents the reuse of already existing GLTF2 importers(※1), etc., This is a serious flaw as a standard format, and also it may destroy the standardization of GLTF2. 

Therefore, I suggest that the coordinate system of all data should be changed to align with the right-hand coordinate system of Y-UP, +Z forward, which is the specification of GLTF2.

----
※1: VRM をそのまま拡張 GLTF として右手系へインポートした場合、視点設定やコライダのオフセット、アニメーション等も反転し、局所的に別の座標系が混在するという事が起こるので、モデルを 180 度回転させればいいという問題ではなく然るべき変換が必要になります。既存の GLTF インポータが存在する場合において、拡張 GLTF として正しくインポートする事は（インポータに手を加えられる場合か自作以外では）困難なので、現状では VRM は GLTF の皮を被った独自規格と呼ばざるを得ません。

※1: It is not a matter of just rotating the model 180 degrees with the Y-axis. If you import a VRM directly into the right-hand system, the first person viewpoint settings, collider offsets, animations, etc., are also inverted, resulting in a mixture of different coordinate systems in certain parts of the model. At this time, even if we have a GLTF importer, we cannot import as extended GLTF correctly, so currently VRM is just faking GLTF.

**Comment by Santarh** [comment]
たしかに VRM の Humanoid モデルのデータは -Z の方向を向くように配置がなされます。
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#mesh-normalization

しかしデータを解釈する座標系としては glTF に準じると規定されているため、 +Y Up の右手座標系になっています。
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#model-normalization

これは現状の VRM 0.x の Unity 実装である UniVRM の具体的な実装でも同様で、
glTF の仕様としては問題のない形になっているかと思います。
（実際に VRM ファイルを glTF ファイルとして一般のビューワで読み込んだときに、ポリゴンの裏表が反転したりといった問題は起きていないはずです。）
https://github.com/vrm-c/UniVRM/blob/master/Assets/UniGLTF/Runtime/UniGLTF/IO/MeshExporter.cs#L31

データを解釈する座標系に対する関心と、データの中身がどうあるべきかに対する関心は分けるべきです。
前者は VRM は問題がないので、この Issue では後者だけを取り扱うと良いのではないでしょうか。

**Comment by TokageItLab** [comment]
いいえ、書いてある通りそのような単純な問題ではありません。 Humanoid モデルの顔の正面方向が +Z 軸になるように180度回転をさせたとしても、その他のパラメータの座標系は右手系と左手系で反転されて読み込まれます。例えば、右手系では + が手前であるにも関わらず、コライダのオフセットは -Z を手前と解釈する必要があります。
議題としては、「 VRM が用いる全てのデータの座標系を GLTF 規格である Y UP 右手系の  +Z がモデルの正面となるように定義をし直した上で、 UniVRM の インポーターとエクスポーター で正しく座標変換を行うようにする」です。

**Comment by Santarh** [comment]
はい、たしかに SpringBone の collider に使われる座標系は昔の考慮漏れで Unity の左手系 Y Up 座標系になっています。
この collider の座標系の問題は修正されるべき問題だと私も思いますし、過去にも議題に上がっていました。

しかしその collider の座標系の問題と Humanoid モデルの顔の正面方向がどこを向いているかという問題は排他です。
メッシュのデータの座標系は glTF の座標系に準拠していますし、Humanoid のモデルの顔の正面方向は VRM 1.0 の spec に明確に -Z だと定義されています。
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#coordinate-units

そして VRM 1.0 としては VRM の座標系は glTF の座標系と準じると規定されています。
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#mesh-normalization

したがってこの Issue の議題である「全ての座標系がGLTF2の規格に沿っていない」は collider の座標系の問題に対する提起としては著しい誇張表現だと考えます。

つまり、あなたが提起するべき議題は以下の点になるのではないでしょうか。
- Humanoid モデルの顔の正面方向は glTF の座標系が定める正面方向の +Z に揃えるべき
- SpringBone のパラメタなどの座標系パラメタは厳密に VRM の定義に準じるという記述を加えるべき

ひとつわかりにくい点があるとすれば、現在の UniVRM は VRM 0.x としての実装であり、vrm-specification は VRM を正式なバージョンとして publish するための VRM 1.0 としての定義仕様であるという点です。
したがって現在のところ VRM 0.x である UniVRM 実装には VRM 1.0 としての理想が実装できていない部分があります。

**Comment by TokageItLab** [comment]
SpringBone の Collider だけでなく、 FirstPersonBoneOffset などにつきましても GLTF へ Unity の値が x y z 全ての軸に対してそのまま持ち込まれてしまっている（座標系が反転している）ように見えます。

> SpringBone のパラメタなどの座標系パラメタは厳密に VRM の定義に準じる
GLTF へ左手座標系を持ち込むという事でしょうか

**Comment by Santarh** [comment]
統括の２点には私も同意します。
目的とする理想の形は、あなたも私も同じ考えだとおそらく思います…！
glTF 座標系にすべてが準じるべきという目的の形には私も同意します。
提案の粒度が大きすぎるので、問題を分けて考えたいのです。

> GLTF へ左手座標系を持ち込むのを許容せよ、という事でしょうか。

いいえ、私の意見は glTF に準じた右手系座標にするように提案するほうが良いだろうということです。
現在 VRM 1.0 の定義としては glTF の右手系座標に準じるという規定 [1] があります。
ただ、すべての座標系パラメタがそれに準じるとは明示的に定義されてはいないとも思います。
したがって、すべての座標系パラメタは明示的に「glTF に準じる」と書く提案をするのがよさそうという意見です。

>  Unity と GLTF (OpenGL) 上では YZ 軸を揃えた場合に X 軸が反転するのは自明(※1)なので、モデルと同様に変換をすべきです。

最終的な理想の形態として「モデルもパラメタもすべて glTF に準じる」を達成したときの UniVRM での具体的な変換手段として、X 軸反転には同意します。

Unity とは切り離された、VRM 1.0 の仕様としての提案はこういった形になるのではないでしょうか。

- Humanoid モデルの顔の正面方向は GLTF の座標系が定める正面方向の +Z に揃えるべき
- SpringBone collider などの拡張における座標系パラメタは glTF の座標系に準じ、Humanoid モデルと対応するべき

---
[1] https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#coordinate-units

**Comment by TokageItLab** [comment]
ご賛同頂きありがとうございます、その２点で問題ありません。 GLTF の拡張である以上、プラットフォーム間の互換性のためにはすべての座標系は GLTF 座標系に準じるべきであると確信しております。これらは互換性を強く破壊するトピックですので、早い段階での解決が必要であると思い、強めの意見を出させて頂きました。

Issue のタイトルの方は上記２点の趣旨が分かりやすいように変更して頂いて構いません。ご検討の程よろしくお願いいたします。

**Comment by ousttrue** [comment]
`RightHanded -> Y-UP, -Z-Front` => `RightHanded -> Y-UP, Z-Front`

<img src=https://github.com/KhronosGroup/glTF/raw/master/specification/2.0/figures/coordinate-system.png>

**Comment by FMS-Cat** [comment]
以上の議論を踏まえて、

- 座標系を誤って格納している箇所はすべて右手系Y-upで統一する
- VRMの向きは+Z向きとする

方針で1.0の仕様を整えます。

**Comment by ousttrue** [comment]
仕様を更新済みです。
