### ISSUE TITLE
UnityのVRM/MToonのアウトラインマスクの設定項目がわかりづらい

### ISSUE THREAD

**Issue by VCRamen** [vrm-c/vrm-specification#206]
現状ですと、OutlineのWidth項目がマスク画像の設定箇所になっているので、見ただけではわからない。

一応Wikiにアウトラインマスクの説明は記載されてはいます
https://virtualcast.jp/wiki/unity/shader/mtoonreference#outline

![outline](https://user-images.githubusercontent.com/71374442/104309222-2a764400-5515-11eb-9fb8-c9f11de100bc.png)

**Comment by Santarh** [comment]
要望ありがとうございます。
こちらの問題は UniVRM/MToon の Docs 不足（つまり説明不足）だと感じられるのでそちらでどうにかしたいです。

UI の方はこのままが良いと考えます。
なぜかというと、このテクスチャは正確にはマスクテクスチャではなく、上位互換である輪郭線の幅を制御するテクスチャです。
マスクテクスチャは「輪郭線を出さない/出す」の２値でしか制御できませんが、このテクスチャは「輪郭線の幅を 0 から指定値まで、画素値の 256 段階」で制御できます。
したがって Width の項目としてこのテクスチャが存在するのは適切だと考えます。

**Comment by FMS-Cat** [comment]
ひとまず、仕様には関連がなさそうなため、閉じてしまいます。
