### ISSUE TITLE
[1.0] Weight of expression morph targets

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#209]
[0.0 - 1.0] でしょうか、 [0.0 - 100.0] でしょうか？
Unity的には100.0が最大値になると思いますが、glTF的には `node.weight` および `mesh.weight` が[0.0 - 1.0]のようなので、1.0が良いかと思います（仕様には明言されていませんでしたが、実装を見る限りそのようです 😅）。
いずれにせよ、仕様にはどちらであるかを示すべきと思います。

**Comment by ousttrue** [comment]
`VRM-1.0` では、 `1.0` にするつもりでした。
どこかに書いたような気がするのですが、漏れているかもしれない・・・

**Comment by FMS-Cat** [comment]
もう書いてあります！
