### ISSUE TITLE
[1.0] Some arrays should have "minItems": 1

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#215]
すべての空になる場合省略できる配列は `"minItems": 1` を持っていたほうが良さそうです。
1.0がほぼほぼfixになった段階で見直しをしたいです。
See: https://github.com/KhronosGroup/glTF/blob/7bb3f391c76ce62fe2dd7891da9747b6828c8ab1/specification/2.0/schema/glTF.schema.json#L15

**Comment by esperecyan** [comment]
似た問題であるため、こちらにコメントいたします。

仕様書において「必須」のプロパティは「空文字列を許容しない」という判断が行われました。
https://github.com/vrm-c/vrm-specification/issues/178#issuecomment-708997930

> すべての空になる場合省略できる配列は "minItems": 1 を持っていたほうが良さそうです。

こちらは「配列が空の場合省略しなければならない」という意味かと思いますが、必須でないプロパティに対する空文字列はどうなるでしょうか。また、単純に `minItems` だけであれば、それが文字列の配列であれば空文字列を持つことができます。

また、必須の文字列プロパティに対する空白文字の扱いはどうなるでしょうか。UniVRM-0.66.0では空白 (U+0020) を含めればエクスポートできますが、たとえばTHE SEED ONLINEはVRM-0.0における meta.title が空白文字の場合、必須プロパティが欠けているとしてエラーを出します。

個人的な考えでは、あらゆる部分で空文字列を禁止 (`minLength` を指定) して一貫性をとり、空白文字についてはそういった文字種について考慮しだすと切りがないので特別扱いしない (値に空白文字のみを含む必須プロパティの存在を認める) のが妥当ではないかと考えています。

### 関連
https://github.com/vrm-c/vrm-specification/issues/72 JSON Schema において制約を定義する

**Comment by FMS-Cat** [comment]
JSON Schemaでは `minLength` が使えるのですね！完全に見落としてました。Authorsなど、明確に空文字ではならない理由があるプロパティ群について、適用をしたいと思います。

**Comment by FMS-Cat** [comment]
> また、必須の文字列プロパティに対する空白文字の扱いはどうなるでしょうか。UniVRM-0.66.0では空白 (U+0020) を含めればエクスポートできますが、たとえばTHE SEED ONLINEはVRM-0.0における meta.title が空白文字の場合、必須プロパティが欠けているとしてエラーを出します。
> 
> 個人的な考えでは、あらゆる部分で空文字列を禁止 (minLength を指定) して一貫性をとり、空白文字についてはそういった文字種について考慮しだすと切りがないので特別扱いしない (値に空白文字のみを含む必須プロパティの存在を認める) のが妥当ではないかと考えています。

私も個人的にはesperecyanさんと同意見です。
