### ISSUE TITLE
[0.0] Validation inconsistency in vrm.humanoid.bone.axisLength

### ISSUE THREAD

**Issue by infosia** [vrm-c/vrm-specification#216]
`vrm.humanoid.bone.schema` の `axisLength` について、[スキーマ定義では `minimum` 等は設定されていない](https://github.com/vrm-c/vrm-specification/blob/master/specification/0.0/schema/vrm.humanoid.bone.schema.json#L63)ようですが [UniVRM の実装では 0 をエクスポートしない](https://github.com/vrm-c/UniVRM/blob/2c190c39d9d50bdb4d40387690c47f1fb6184523/Assets/VRM/Runtime/Format/VRMSerializer.g.cs#L235)ようにしているようですので、実質 `minimum = 0, exclusiveMinimum = true` ということに思えます。[glTF_VRM_Humanoid の定義](https://github.com/vrm-c/UniVRM/blob/1be98538481fc3aed796193c6fee175697c65939/Assets/VRM/Runtime/Format/glTF_VRM_Humanoid.cs#L162)では `minimum = 0, exclusiveMinimum = true` 設定されています。VRM 内で axisLength=0 と明示的に設定してあったケースでも SEED ONLINE などでモデルは問題なく動作はしていたようには思います。Unity 内でどのように処理されているかは存じません。どちらかに合わせることは可能ですか？（0.0 schema は今でもメンテされていますか？）

**Comment by saturday06** [comment]
その定義にするとaxisLength=0のVRMがinvalidになるという非互換が発生するので、変更するならばVRMのspecVersionを0.0から0.1などにバージョンアップをするのも一緒にお願いします。

**Comment by ousttrue** [comment]
0.0 schema の更新はしない方針です。

humanoidBones 周りで使っていない項目はまとめて廃止予定です。

https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/spec_changed.md

の表にまとまっています。

開発当初に項目の要不要が分からなかったため、
unity の humanoid avatar に関連する型をそのままダンプしていた名残です。
運用した結果、 humanoid bone とノードの対応付け以外のシリアライズは不要と分かりました。

* Unity の humanoid の詳細がブラックボックスなので他の実装で効果を再現することができない
* Unity の Animator コンポーネントの設定(IK機能など)で、そもそも VRM に入れる意図が無い
 
などです。

**Comment by infosia** [comment]
ご確認ありがとうございます。0.0 schema はこれ以上更新しない旨が [README](https://github.com/vrm-c/vrm-specification/blob/master/specification/0.0/README.ja.md) 等に書いてあるとより良いかもしれません。本件はクローズします。
