### ISSUE TITLE
meta.reference (親作品) を配列に

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#220]
親作品はNoteへ記述されているように複数存在し得ます。
https://github.com/vrm-c/vrm-specification/blob/f66c018ab54bab5e799e790c5b091adcac7b3209/specification/VRMC_vrm-1.0_draft/README.md#models-meta-information

特にURLを1つの親作品に付き1つ記述し、複数のURLを記述するような場合、記述方法を明確に定める (配列にする) ようにした方が、記述しやすくプログラムから扱いやすいものになると考えます。

**Comment by FMS-Cat** [comment]
実はschema上では `master` でも既にそうなっています！
仕様の文章が追いついていなくて申し訳ありません。
現在、文章の方も #201 で更新しようとしていますので、しばらくお待ちください。
