### ISSUE TITLE
meta.otherPermissionUrl を複数行文字列に

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#222]
アバターは複数のライセンスが混合していることが多いですが、それらを単一のURLで表すのは現実的でないと考えます。

それらのライセンスを記した文書をどこかへホストし、そのURLを張るということもできますが、アバターごとにそういった作業を行うのは煩雑で、またリンク切れの問題が起きる箇所が増えます。

また、アバターの利用者側がライセンスを確認しやすくなり、より目を通しやすくなるという利点もあるかと思います。

### 関連
https://github.com/vrm-c/vrm-specification/issues/51 [suggestion][1.0draft]著作権者等表示について

**Comment by s-iwaki-d** [comment]
独自ライセンスを設定しやすくする、というのは言い換えると独自ライセンスを設定する人が増えることになり
結果として利用者側のライセンス判断が難しくなる（簡単な判定が事実上不可能になる）未来を招くことを危惧しています

VRMとしてはできるだけ「アバター作者が独自ライセンスを策定しなくとも、まあこれでいいかと思える最大公約数としての基盤ライセンス」を定義して、皆にそちらを使っていただく形に寄せたほうが全体的によりよい未来になると考えます。
そのため独自ライセンスを定義したい人には一定のハードル、この場合はライセンスを記した文書をホストしURLを発行する、という手間、を設けたいと考えています。
