### ISSUE TITLE
VRMC_vrm-1.0_draft/README.md の章立てを変える

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#223]
はじめに、シーングラフ全体を表現せずルートに配置されたスキニングモデル一体を決まった様式で格納する件について記述。

# T-Pose 正規化概説

* ヒューマンボーン: T-Poseを定義するためのノードとボーンの対応
* T-Pose: 同じモーションを使うための同じ基準ポーズ
* ノードから回転・拡大縮小を除去する: バインド行列との組み合わせでノード位置が見た目と異なる場合があり、それを回避しないとプログラムから扱うことが難しくなる

# GLTF の自由度を制限する

* GLTF のサブセット

* 単一のルートノード
* Z+向き #205
* ノードから回転・拡大縮小を除去する => メッシュとバインド行列への要求

```
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 1, 0]
[x, y, z, 1]
```

# GLTFに無い情報を拡張する
* VRM 拡張

**Comment by FMS-Cat** [comment]
> 単一のルートノード

これは、#71 を加味しての制約でしょうか？
一応、GLTFのルートレベルに相当するノードの群を、1つのルートノードとなるものに格納することで対処が可能と思っております。
Three.js GLTFLoaderにおいて、glTFのシーン全体（ `gltf.scene` ）は、1つのルートレベルの `THREE.Group` （ `THREE.Object3D` とほぼ同義、要はノード）に格納されて読み込まれています。

> Z+向き #205

これですが、glTFの仕様に存在する推奨事項をより強調した上で強制となる仕様とするという認識で良いでしょうか？

**Comment by ousttrue** [comment]
## 単一のルートノード

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/scene.schema.json

nodes が array でマルチルートになってしまうことを防止する意図でした。
VRM-0.X から継続したものです。
UniVRM は、scene はノード化せずに root からノードを構築する仕様でした。
scene を root の empty であると見なす仕様に変更することは可能です。
(root が TRS を持たない、meshがついていない、などの前提を置くことが可能なので)

## Z+向き

glTF はシーングラフを表現するので中身によっては前という概念が自明でないとは思います。
VRM はヒューマノイドが入っているので前が自明です。
VRM-0 は、X+ が右になるように決めました。

* デフォルトのカメラ位置がそうなっているアプリが多い
* VRのアバターとして使うのに便利な背中無きにした
 
VRM-1 は、Z+ が前になるように決めました( #205 )。
どっち向きでも決まっていることが重要です。
Importer が用途に応じて座標変換する能力を持っているとよいと思います。
正規化済みが前提の場合、UP軸での９０度回転は比較的簡単です。

**Comment by TokageItLab** [comment]
座標系の話をむし返すようで悪いのですが VRM-0 が -Z を向いているのは UniGLTF で座標変換が正しく行われていない故の結果論なのではないかと感じております。同じく UniGLTF を用いている VCI においても VRM-0 同様 GL 座標系になっていません。

> VRのアバターとして使うのに便利な背中向きにした

Unity で読み込んだ際には背中を向かないのでこれは正しくないのではないでしょうか。例え背中を向いていたとしても例えば LookAt 処理等は基本的に前方となるローカル軸をターゲットに向ける事が多いので便利だとは思えません。

ここで議論する問題ではないかもしれませんが、 KhronosGroup 公式の実装である UnityGLTF  と UniGLTF で座標系の変換が異なっているという問題があります。
https://github.com/KhronosGroup/UnityGLTF

UnityGLTF では X 軸反転を行っていますが、 UniGLTF では Z 軸反転を行った後に、外部的に Y 軸で 180 度回転しているように見受けられ、その外部的な回転を失った時に結果として Z 軸が反転してしまっているのではないでしょうか。こちらの件に関しましては本来であれば UniGLTF へ issue を立て、 VCI に対しても座標系の修正を行って欲しいところではありますが、 UniGLTF が UniVRM に統合されたようなので...。

間違いを追求するわけではないのですが、「どっち向きでも決まっていることが重要です」というのは根拠に乏しく、「 glTF の拡張である以上 glTF の推奨する +Z 向きにする」と改めて名言した方が今後 VRM のような glTF 拡張の物が出てくる時に同じような座標系の混乱を防止する事ができると考えます。

**Comment by infosia** [comment]
#742 にも書きましたが glTF のドキュメントには `The front of a glTF asset faces +Z` と記載されています。[Coordinate System and Units](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#coordinate-system-and-units) なので glTF で +Z を向いている方がアセットの正面です。
