### ISSUE TITLE
[1.0] Property keys of LookAt might be too redundant

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#225]
LookAtのproperty keysについて、現状頭に `lookAt` がついている物が多いですが、冗長なので消してしまって良いと思っています。

See: https://github.com/vrm-c/vrm-specification/blob/068254bdf1ca0fb8473487073c82164cb97432d0/specification/VRMC_vrm-1.0_draft/schema/VRMC_vrm.lookAt.schema.json

**Comment by FMS-Cat** [comment]
firstPersonの `firstPersonType` についても同様かな？

https://github.com/vrm-c/vrm-specification/blob/068254bdf1ca0fb8473487073c82164cb97432d0/specification/VRMC_vrm-1.0_draft/schema/VRMC_vrm.firstPerson.meshAnnotation.schema.json#L10

**Comment by FMS-Cat** [comment]
口頭で議論を行いました。 `lookAt` ・ `firstPerson` ともに、冗長なフィールド名を削ります。

**Comment by FMS-Cat** [comment]
@ousttrue 実際リネームしようとしてみたのですが、 `horizontalInner` 等について、すこし名前が十分に説明できていない気がしてきました。`rangeHorizontalInner` とか `rangeMapHorizontalInner` とかにすると丁寧になりますが、いかがいたしましょう……

**Comment by ousttrue** [comment]
range 的な値に関するものと、horizontalInner , outer, などの対象に関するものを組み合わせた適当な名前でお願いします。
コード生成するし、Editor 補完も効くと期待できるので、少々長い名前でもよいと思います。

**Comment by FMS-Cat** [comment]
#239 がmergedなので閉じちゃいます
