### ISSUE TITLE
[1.0] VertexBuffer attributes restrictions for no reason

### ISSUE THREAD

**Issue by infosia** [vrm-c/vrm-specification#227]
1.0 draft [VertexBuffer Attributes section](https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#vertexbuffer-restrictions) stated following:

> Given an input mesh, each primitive comprised by different buffers is prohibited
>  * Each primitive must have the same attributes

In addition to this, VertexBuffer Layout in following section shows that VRM requires each attributes stored in same order.

Why? 
Does this a glTF spec requirement?

**Comment by ousttrue** [comment]
よし、削ろう

**Comment by FMS-Cat** [comment]
実装マターなのは理解できているのですが、

- どういう理由でこの一文って入っていたんでしたっけ？
- なにか関連して仕様に対してnon-normativeでも書いておくとご利益がありそうなことはありますかね？

**Comment by ousttrue** [comment]
#191 に関連して、頂点バッファを共有しない方の記述が残っていました。

* gltfの Primitive がいわゆる Submesh に期待されることをものではない(むしろ Mesh[] 的)であるため、Primitiveを連結してMeshを作るときにいろんなケースが発生し得る。(法線の有無、MorphTargetの内容が不揃いなど)
* glTF 頂点情報が、頂点バッファのレイアウトも表現できるようにしていているため、意味的に同じものをいろんな表現ができる。planar / interleaved  / UniVRM-0.X のバッファ共有方式

というあたりが原因で、頂点バッファの表現がいろいろなパターンがありえます。
で、 UniVRM-0.X では頂点バッファを共有する方式をとっていてそれの説明を書こうとしていました。
共有バッファ方式を捨てる時点で、頂点の順番が変わりうるので見た目が同じになれば好きにしてよいだろうと。
スキニングより後ろの工程の問題になるので、Importerごとに多少違う処理をしても問題無いであろうということで。

Texcoord 2番目以降が使えないのは、
UniVRM が採用している、UnityのStandardにその能力が無いのでそれに引っ張られております。

**Comment by FMS-Cat** [comment]
承知しました。ありがとうございます。

ちなみにThree.jsもTexcoordの1番目はreserved、2番目以降は扱う能力がありません。

**Comment by FMS-Cat** [comment]
#229 で対応済みです。
