### ISSUE TITLE
How do I transfer animation between VRM models with different physiques

### ISSUE THREAD

**Issue by emadurandal** [vrm-c/vrm-specification#23]
お世話になります。

現在、自作のライブラリにて、ボーン構造の異なるVRMモデルの間で、アニメーションの流し込みの処理を作っております。

ボーン構造の違いの解決には、json.extensions.VRM.humanoidの対応情報を見てマッピングさせおり、動作自体は確認しました。

しかしながら、頭身が近いモデル同士であればよいのですが、頭身が大きく違うモデル間でアニメーション情報の流し込みをした場合、望ましくない結果になってしまいます。

（例えば、頭身が高いモデルのボーンアニメーション情報を、頭身が低いモデルに流し込んだ場合、流し込み先の頭身が低いモデルが、通常より異様に頭身が引き伸ばされてアニメーションしてしまう）

一般的に、このようなケースではどういった対策が考えられるでしょうか？
個人的には、各ボーンについて、humanoidの標準的な体格との実際のボーンの位置差分情報をVRMに付加すれば解決しそうに思うのですが、いかがでしょうか？

もし、解決策がこうした付随情報の付加しかないのであれば、ぜひ今後のVRMの追加機能としてご検討をいただければ幸いです。

**Comment by emadurandal** [comment]
自前の実装の方で、転送するアニメーションアトリビュートをQuaternionだけにし、translationについては腰骨のみにすることで、頭身が元のモデルの影響を受けてしまうことは回避でき、満足の行く結果が得られました。
実質解決してしまったので、本Issueの意義は薄れてしまったのですが、一応こういったアニメーションリターゲッティング周りの応用について、VRMでは今後どのように考えていらっしゃるのか伺ってみたいと思います。

**Comment by FMS-Cat** [comment]
VRMのhumanoidおよび各humanBonesには、体格の違いを吸収するために筋肉の可動域を記述できるhumanDescription・humanLimitと呼ばれるプロパティ群が存在します。
ただ、Unityの実装に強く依存する値が入っているため、これを独自に解釈して利用するのはとてもむずかしいのが現状です。
これについて、可搬性に優れたオープンな実装を定義できればよいのですが……

**Comment by FMS-Cat** [comment]
Related: #12

**Comment by emadurandal** [comment]
なるほど、ご回答ありがとうございます。
今の所私としても何か有益な提案もできそうにないため、本件はクローズとさせていただきます。

ありがとうございました。
