### ISSUE TITLE
[1.0] コアの仕様文、コンポーネントごとに分けますか？

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#232]

**Comment by ousttrue** [comment]
メタは `Meta.md` などに分離したい感じです。
他のものに関しては項目同士の参照があったりするので、記述順などに意味があります。
メタは独立したテキスト情報の固まりになるので別れていても読みやすさに悪影響は無いと思います。
担当する人に、このファイルを頼むという分業ができやすいと思います。

**Comment by ousttrue** [comment]
@FMS-Cat 

それと、この部分の `Contributors` ちゃんと書いた方がよいのではないかと思いました。

**Comment by ousttrue** [comment]
#201

**Comment by FMS-Cat** [comment]
@ousttrue どういう基準で書くべきかが定まっていなかったため！申し訳ございません。

**Comment by ousttrue** [comment]
🙏
非技術系だけどメタに関しては書くべきことがある人が直接メタの記述に参加してほしいなーという。
長大で Markdown 書式がいっぱいの README.md から分離されている方がやりやすいんではないかという目論見です。
