### ISSUE TITLE
[1.0] expressions ignoreXXXをカスタムで追加できない

### ISSUE THREAD

**Issue by infosia** [vrm-c/vrm-specification#233]
#4 ですが、以下の点が気になりました。当該 issue はクローズされているので新規に追加します。

> BlendshapeProxyが拡張できる仕様に対して、瞬き、視線、口パクのみに対して排他仕様を追加するのがちょっと気になりました。仕様的には、ignoreBlink、ignoreLookAt、ignoreMouthの固有パラメーターとするのではなくそれらに追加して指定する汎用的なパラメーターとなる方が良いかなと思います。

現状 1.0 の expressions だと排他仕様の追加が ignoreXXX プロパティの追加なしには不可能な仕様になっていると理解しています。今後、排他制御したいパーツが出てくるたびにスキーマの変更が必要になりますか？

```js
{
  "name": "Joy",
  "presetName": "joy",
  "binds": [
    {
      "mesh": 0,
      "index": 0,
      "weight": 1.0
    }
  ],
  "ignoreMouth": true,
  "ignoreBlink": true,
  "ignoreXXX01": true, // スキーマに追加??
  "ignoreXXX02": true, // スキーマに追加??
  "ignoreXXX03": true, // スキーマに追加??
  "ignoreXXX04": true, // スキーマに追加??
},

```

上記のような仕様ではなく expression にカテゴリを設定できるようにしてそれを動的にフィルタできるような仕様にできませんか？具体的には以下のような仕様は可能ですか？

例えば以下のような expression があったとして

- `A`  は口が動く
- `Blink` は目が動く
- Joy は顔全体が動くので目と口の動きをフィルタしたい

（`categories` `ignroes` の命名は一例です 名前はなんでもいいです）

```js
{
  "name": "A",
  "presetName": "a",
  "binds": [
    {
      "mesh": 1,
      "index": 0,
      "weight":1.0 
    }
  ],
  "categories": ["Mouth"]
},
{
  "name": "Blink",
  "presetName": "blink",
  "binds": [
    {
      "mesh": 2,
      "index": 0,
      "weight":1.0 
    }
  ],
  "categories": ["Eye"]
},

{
  "name": "Joy",
  "presetName": "joy",
  "binds": [
    {
      "mesh": 0,
      "index": 0,
      "weight": 1.0
    }
  ],
  "ignores": [ "Mouth", "Eye" ]
},
```

この場合 expression に `categories` でカテゴリを宣言して `ignores` プロパティでそのカテゴリに属する expression を無効化するというようなイメージです。このような仕様だとユーザが動的にカスタムフィルタを追加することができますし実装もそれほど難しいものではない気がします。カテゴリは単なる文字列なのですが VRM として `Mouth` や `Eye` などはプリセット扱いにするようなイメージです。

上記、現状 VRM 1.0 仕様を眺めていて思いついた仕様ですので何か抜けがあるかもしれませんが 排他制御のパーツ追加ができない現状の仕様が気になったので案として俎上に上げさせて頂きます。

**Comment by FMS-Cat** [comment]
元issueを提案したしげぽんさんと議論をして、排他カテゴリをmouth・blink・lookAt以外に設ける必要性は無いという結論になりました。

mouth・blink・lookAtで対象となる表情群については、アプリケーションからプロシージャルに制御され得るため、これらのオーバーライド設定が有効ですが、
これ以外に対してオーバーライド設定があることに価値を感じません。

**Comment by FMS-Cat** [comment]
技術委員会で検討を行い、本issueに対する対応は行わない方針としました。
理由は上に述べたとおりです。
