### ISSUE TITLE
VMRC_collider_node の仕様だとマイグレーションできない例がある

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#236]
例

```
NodeX
 SphereA
 SphereB
```

とあるときに

```
SpringA
  Colliders -> NodeX.SphereA

SpringB
  Colliders -> NodeX.SphereB
```

というような参照を表現できないことがわかりました。
(別のSpringが、同じノードの別のColliderを参照したい場合)

https://github.com/vrm-c/UniVRM/pull/870#discussion_r613112274

解決するために `VRMC_node_collider` の独立をとりやめて以下のようにしようかと思います。

```json
// VMRC_springBone
{
  "colliderGropus": [
       {
          node: nodeIndex,
          colliders: [
             // VRMC_node_collider の内容
          ]
       }
   ],
   "springs": [
       "colliders": [
          // ここを nodeIndex から 上記 colliderGropus の index に変更する
       ]
    ]
}
```

**Comment by ousttrue** [comment]
@FMS-Cat どうでしょうかー

**Comment by FMS-Cat** [comment]
コライダーを別拡張にするご利益に対して、同じノードの別コライダーを参照できるようにすることのご利益が薄いと感じました。本当にやりたければ、別のノードとしてそれぞれ定義するのが良いかなと思っていました。

**Comment by FMS-Cat** [comment]
実際にどのようなモデルでこの需要が発生しているかを聞いてみたいです。もし、この使い方の需要が十分に高いのであれば、吟味する価値があると思います。

マイグレーションのやり方としては、ある単一のnodeに属する複数のcolliderGroupがあった場合に、そのnode自体には直接colliderを付与せず、子nodeを追加してそこにcolliderを付与するような方針になると思います。

お、スプリングボーン側で指定していた `node` がその子孫ノードのコライダーからも作用を受けるのかを議論していなかった気がする……

**Comment by FMS-Cat** [comment]
私が提案した手法の短所は、nodeの数が増えるため、nodeのトランスフォームの計算が高コストな環境の場合は苦しいかもしれない点です。ですが、これはそこまで問題にならないのではないかと推測しています。

**Comment by Santarh** [comment]
実例としては、美少女モデルといった顔まわりの破綻が許されないモデルに多いです。

前提として、VRM の SpringBone は発散（物理爆発状態）が起きにくいことを優先し、そのトレードオフとして貫通しやすい計算定義になっています。
したがって、たとえば前髪や横髪など、貫通が特に許されない部位は入念にコライダを設定することになると思います。
その際、前髪や横髪と衝突する ColliderGroup を同じひとつのものにしようと思うと、前髪と横髪どちらにもフィットする ColliderGroup を調整するのはかなりシビアです。
なぜなら前述の通り VRM の SpringBone は貫通しやすい計算定義のため、結局、SpringBone ごとに ColliderGroup を作って調整せざるを得ないし、そうしても計算量としては増えないからです。

**Comment by Santarh** [comment]
いま述べた例のように、ColliderGroup およびそれが内包する Collider は、あくまで「特定の SpringBone に対して最適化したもの」にならざるを得ません。
つまりコライダは、アバターの身体形状にフィットしているとも限りません。

したがって、SpringBone の ColliderGroup / Collider を別の用途に転用することにメリットが有るというのは、少々懐疑的に感じます。

**Comment by FMS-Cat** [comment]
なるほど、解説ありがとうございます。それはなかなかSpringBone特有のシチュエーションっぽいですね。

それを考慮すると、そもそも `node_collider` はやはりすこし汎用的すぎる名前かもしれないと再認識しました。だんだんSpringBone側の拡張にコライダーを戻すのが妥当な気がしてきました。次回の定例で改めて方針の認識合わせをして決定としましょう（もう少し時間が欲しい）。

**Comment by FMS-Cat** [comment]
5日間寝かせましたが、統合する方針から意見が変わらなかったので、統合したいと思います。
#237 のレビュー始めます！

**Comment by FMS-Cat** [comment]
#237 がmergedなので閉じちゃいます
