### ISSUE TITLE
[suggestion] Add smooth normal shading extension

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#24]
gltfで容量削減を考えたとき、法線属性の削除を検討することができます。
　そこでgltfの仕様を見ると、法線属性がない時はフラットノーマルを計算すべき(=フラットシェーディングすべきと私は解しています)、となっています。
[>Implementation note: When normals are not specified, client implementations should calculate flat normals.](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes)
　しかし、VRMが人型アバター専用仕様である点を考えると、法線計算はスムーズシェーディングの方が都合がよい場合が多いのではないかと私は考えます。ただし、メカ系などを考えるとフラットシェーディングの方が都合がよい場合も考えられます。
　ここで、[KHR_materials_unlit](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_unlit/README.md#extending-materials)のような、法線属性がない時の法線計算方法をスムーズシェーディングフラグの拡張を作ることを私は提案します。

e.g:下記の様にextensionsに記述にしたときにはスムーズシェーディングすべきという事です。逆に、NORMAL属性の記述がなく、拡張の宣言もない場合はgltfの仕様に従い、フラットシェーディングにすべきという事になります。
```
{
    "meshes": [
        {
            "primitives": [
                {
                    "attributes": {
                        "POSITION": 0,
                        "TEXCOORD_0": 1
                    },
                    "indices": 3,
                    "material": 0,
                    "extensions": {
                         "VRM_PRIMITIVE_NORMAL_SMOOTH": {}
                     }
                }
            ]
        }
    ]
}
```
参考 :[stackexchange:programmatically-generating-vertex-normals](https://computergraphics.stackexchange.com/questions/4031/programmatically-generating-vertex-normals)

**Comment by hiroj** [comment]
法線情報を削って容量を節約する案としては良いと思いました。
実装側にスムーズシェーディングとフラットシェーディングの対応が要求されるため、頂点法線ベースのエンジンを使用している場合はimport時に頂点分割が必要になりそうですね。

**Comment by hiroj** [comment]
Unityなどのゲームエンジンの場合はフラットシェーディング専用のシェーダを用意するなどが必須になってしまうためいったんv1.0では対応しない方針にします、フラットシェーディング導入に対して強い要望がある場合は再度検討致します。
