### ISSUE TITLE
[1.0] Expressionsの範囲外の値について、挙動を仕様化しておきたい

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#240]
各Expressionの値が[0-1]から外れた場合の挙動を仕様にしておきたいです。具体的には、clampとするのが自然かなと思いました。

社内でディスカッションをした結果、以下のようなご利益が考えられることがわかりました:

- アーティストが意図した範囲内でしか表情を動かすことができないため、アーティストの表現を尊重できる
- 実行環境によっては、モーフ値を[0-1]から飛び出して制御することができないこともあるようなので、挙動を揃える意味で有効
    - Unity 2018.x 以前は、BlendShapeのWeightが[0-100]でクランプされていたようです

一方で懸念としては、以下が考えられます:

- マイナス方向や1を飛び越えて制御されることを想定したExpressionsを実装することができなくなる
    - モデルをランタイムで表情として制御する上ではこの用法は考慮しなくて問題ないかなと思います。

**Comment by Santarh** [comment]
クランプする、で良いと思います。

他の理由を述べるなら、クランプしない場合 Override まわりの仕様の整合性が取れなくなるので、クランプするで良いと思います。

ただ、そもそもウェイトの取りうる値は [0, 1] である、という定義で自明かなとも思います。

**Comment by ousttrue** [comment]
TODO: JsonSchemaに現れないランタイム値。Readmeに作文

* Expression の入力値 [0, 1]
* MorphTargetBind の解決後の値Weight [0, 1]

**Comment by FMS-Cat** [comment]
自明に見えても、大きなコミュニティで誰がどのような使い方をするかわからないため、事前に塞いでおけるものは明示的に塞いでおきたいという思想が自分は若干強めです……。
とりあえず、追記してPRを出させていただきます！
