### ISSUE TITLE
[1.0] MToon の ShadingToony を制御する Texture を追加する

### ISSUE THREAD

**Issue by Santarh** [vrm-c/vrm-specification#256]
ShadingToony をテクスチャで制御できる `shadingToonyTexture` を追加する。
技術委員会で議論済み。（ですよね？）

この際、どの RGB チャンネルを参照するのか要検討。

既存のリニアパラメタ系テクスチャのチャンネル割当は
- R : `shadingShiftTexture`
- G : `outlineWidthMultiplyTexture`
- B : `uvAnimationMaskTexture`

個人的には、`uvAnimationMaskTexture` は A チャンネルにしてしまってもいいのかなと思います。
`uvAnimationMaskTexture` はほかのテクスチャに比べれば使用頻度が低く、かつ、 グラデーションに意味を持たないため、圧縮による質の低下にも耐えうると考えます。

もしくは `uvAnimationMaskTexture` も使いたいなら別のテクスチャにする、ということで RGB のどれかにするか、でしょうか。

**Comment by FMS-Cat** [comment]
失礼しました、本Issue気づいておりませんでした！

RGBチャンネルに関する議論については、アルファをマスクにアサインするのに以下の懸念があることが挙がっていたと思います。

- 白黒のマスクが利用できない（利便性の面）
- アルファが0の画素に対してRGBが正しく記録されない（画像フォーマットの面）

これらの懸念が問題ないようであれば、アルファを含めてマスクを記録して良いと思います。
もしくは、シェーディング系とそれ以外で利用するテクスチャを別にする選択も良いと思います。

**Comment by Santarh** [comment]
アルファチャンネルにアサインするのはできる限り避けたい、というのは同意します。
どうしてもアサインする必要があるなら消去法で `uvAnimationMaskTexture` だろう、程度です。

`shadingToonyTexture` の意義自体は、グラデーションを持つことで表現力をあげられること、そして複数マテリアルの結合を容易にすること、かなと思われます。

ただし、単一の VRM モデルにおいて Toony の値はそう変わりうるのか？という懸念はあります。

**Comment by FMS-Cat** [comment]
> ただし、単一の VRM モデルにおいて Toony の値はそう変わりうるのか？という懸念はあります。

この観点について、私の社内でも議論を行いましたが、やはり他のプロパティに対して有意性が微妙そうという結論になりました…… 😩

**Comment by Santarh** [comment]
なるほど。ありがとうございます。

となるとメリットは vrmc_materials_mtoon のマテリアルの結合能力を上げる、程度ですかね……

デメリットが無ければもうちょっと考えてもいいかなと思いましたが、実際デメリットがある（4チャンネル目のテクスチャになる）ので、この Issue はこれで終わりにしようと思います！
