### ISSUE TITLE
英語の表現揺れの精査

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/vrm-specification#259]
Depends on #268 

`prohibit` / `prohibited` ・ `scale` / `scaling` などなど、気になる表記揺れが多いです。誰に聞くのが正解なんだろう

**Comment by norio** [comment]
https://github.com/vrm-c/vrm-specification/pull/266
https://github.com/vrm-c/vrm-specification/pull/267

**Comment by ousttrue** [comment]
#268 で作業します。
