### ISSUE TITLE
Humanoid外のボーン名にHumanoidボーン名と一致する物を付けないという制約が欲しい

### ISSUE THREAD

**Issue by TokageItLab** [vrm-c/vrm-specification#263]
VRM 0.x において glTF ノードとしてのボーン名は保持して辞書で VRM の定義する Humanoid ボーン名と対応付けるという形式をとっていますが、ボーンアニメーションを行う各種アプリケーションにおいては「モデルのボーン名」と「アニメーションさせる際に指定するボーン名」を完全に対応させる必要があるケースが存在します。(※1)

上記のような環境でアニメーションを共有したい場合を考慮すると、インポートの際に元のボーン名を VRM Humanoid ボーン名に置き換える処理が必要になります(※2)が、Humanoid 外のボーンに Humanoid ボーン名と一致する物があると名前の重複が発生してしまいます。

なので題のように制約を増やすか、もしくは辞書を作らずにエクスポート時にボーン名を VRM Humanoid ボーン名にしてしまってもいいのではないかと考えております。

後者に関しては破壊的になってしまいますが...VRM が Humanoid ボーン名を定義している以上、元のボーン名に関してはデータとしての価値は薄いとも思われますので、元の名前を保持するメリット（ミラーリングの予測等に使う？）と、 glTF としてのインポートした時の扱いやすさ・エクスポート時のバリデーションの容易さを比較して考えると、ここは破壊的でも問題ないのではないかと思っております。

----
※1: Unity のようにボーンアニメーション用に別名のパラメータを持っている環境の方が特殊だと思っております。

※2: アニメーション側でリネームを行うとすればモデルごとに全てのアニメーション内のボーン指定を変換する必要性が出てきます。また、アプリケーション側で独自に内部のボーン名を決めるとなるとそれ用の制約が発生し、VRM の中でもまた規格がバラバラになってしまいます。

**Comment by FMS-Cat** [comment]
インポート時にNodeのリネームを行えば問題ないかと思いました。
例えば、Three.jsのGLTFLoaderには、重複する名前のボーンをユニークにする処理が入っています:
https://github.com/mrdoob/three.js/issues/15087

GLTFに対して新たな制約を設ける必要性を疑問に感じましたが、なぜこの解決手法にたどり着きましたか？

**Comment by TokageItLab** [comment]
例えば Godot だと glTF ボーン名の重複時に連番を付けますが、VRM A に Hips という名前の翼のボーンがあり、VRM B にHips という名前の翼のボーンと Hips 1 という尻尾のボーンがあったとして、Humanoid Bone にリネームを行った場合 VRM A では Hips 1 が翼になり VRM B では Hips 1 は尻尾を指し示すのではないかという事を危惧しました。

VRM というよりは glTF 拡張として見た場合が大きいですが、例えばこの時翼にカスタムアニメーションを入れたいとして、A と B で翼のアニメーションが共有できなくなります。

つまりは、Humanoid 外のボーンの暗黙的なリネームを事前に防止したいという考えとなります。

**Comment by FMS-Cat** [comment]
需要は理解しましたが、glTFをインポートする際に、アプリケーションの需要に応じて、VRMのHumanoidおよびglTFで元々付与されていたボーン名を参照した上で、適切にリネームを行うことを期待したいです。

**Comment by FMS-Cat** [comment]
例えば、複数のモデルでアニメーションの共有が必要となる場合に、モデル内のノード名をHumanoidに即したものにリネームするというユーティリティ関数を、VRMの各実装に用意しておくのは良いかもしれないです。

**Comment by TokageItLab** [comment]
> VRMの各実装に

アプリケーションごとにリネーム処理が異なる場合にまたアプリケーションごと新たな制約が生まれそうですが...

いずれこの辺りがマナーみたいになってきそうなのを危惧しています

**Comment by FMS-Cat** [comment]
> アプリケーションごとにリネーム処理が異なる場合、アプリケーションごとに個別のHumanoid外ボーンの命名規則が生まれそうですが...（VRM 内での規格分裂問題）
>
>この辺りがいずれ「制約でもないが避けるべき」というような所謂マナーみたいなあやふやな状態になりそうなのを危惧しています

この点に関しては、リネーム前の各nodeのnameの情報を利用してアプリケーション側で回避してほしいです。
ただし、この実装がどの程度の難易度であるかは吟味が必要です。それ次第では、「Humanoidのボーン名と同じ名前を持ったノード名は避ける」という旨をnon-normativeに記す可能性はあります。
次回の技術委員会で検討します。

**Comment by TokageItLab** [comment]
補足的にHumanoid外のボーンを暗黙的にリネームした場合に起こりうるケースを書いておきます

モデルA(Original)
腰: Koshi, 翼: Spine を持つ

1. モデル A(Original) をアプリに VRM として読み込む
2. モデル A(VRM) で「腰: Spine」「翼: Spine 1」となるリネームがアプリ発生

3. モデル A(Original) の「翼: Spine」を外部アプリでアニメーションさせ、**アニメーションを含めるために glTF として出力**

4. モデル A(glTF) をアプリに glTF として読み込む
5. モデル A(glTF) ではリネームが発生しない
6. モデル A(glTF) の翼アニメーションをモデル A(VRM) の翼に適用しようとする
7.  モデル A(glTF) の翼のアニメーションがモデル A(VRM)の腰をアニメーションさせてしまう

**Comment by infosia** [comment]
本件、 glTF のエリアでの破壊的変更には反対です。アプリケーション側で処理するか、必要であれば extension のエリアを使用すべきと考えます。 #214 で主張しているように、VRM の仕様を決める際のポリシーとして "オリジナルのデータを破壊するのではなく、そうすることが自明な場合やどうしても避けられない場合を除き、VRM に必要な情報は glTF の extension に格納するべき" という点を明記することができれば本件のようなケースで判断に迷うことは少なくなると思っています。

**Comment by FMS-Cat** [comment]
技術委員会で検討を行いました。

non-normativeな記述を追加することを検討しましたが、以下の理由により、本問題に対する対応は行わないこととします。

- 実際どのような問題が発生するかの説明が難しいため
- nameは本来glTFとしてはアニメーションの用途を想定したフィールドではないため

リネーム前の名前のマッピングを用いてコンフリクトしない値とする実装は困難ではないと思いますので、その方針での対応をお願いしたいです。
