### ISSUE TITLE
1.0 清書

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/vrm-specification#268]
おおまかにタスク化。
英文チェックの前に、チェックされる元になる英文を日本語から作成するべし。

# VRMC_vrm-1.0_draft
* [ ] VRMC_vrm-1.0 draft外し

README
* [x] jsonschema fix
* [x] README.md #269 #271
* [x] README 英文ベース作成 #281
* [ ] README 英文チェック

meta
* [x] meta @FMS-Cat #276
* [ ] meta 英文チェック

humanoid
* [x] humanoid @ousttrue #269 #272
* [x] humanoid 英文ベース作成 #282
* [ ] humanoid 英文チェック

expression
* [x] expression @ousttrue  #273
* [x] expression 英文ベース作成 #283
* [ ] expression 英文チェック

lookAt
* [x] lookAt @ousttrue #274
* [x] lookAt 英文ベース作成 #284
* [ ] lookAt 英文チェック

firstPerson
* [x] firstPerson @ousttrue 
* [x] firstPerson 英文ベース作成 #285
* [ ] firstPerson 英文チェック

# VRMC_springBone-1.0_draft
* [x] VRMC_springBone-1.0 draft外し
* [x] jsonschema fix
* [x] README.md @ousttrue #277 
* [x] README 英文ベース作成 #286
* [ ] README 英文チェック

# VRMC_node_constraint-1.0_draft

* [ ] jsonschema fix #262
* [ ] README.md @FMS-Cat 
* [ ] README 英文ベース作成
* [ ] README 英文チェック

# VRMC_materials_mtoon-1.0_draft

* [ ] jsonschema fix
* [x] #306
    * [ ] #252
    * [x] #270
    * [ ] #293
    * [ ] #294
* [ ] README 英文ベース作成
* [ ] README 英文チェック

# VRMC_materials_hdr_emissiveMutiplier-1.0_draft
* [x] VRMC_materials_hdr_emissiveMultiplier-1.0 draft外し
* [x] jsonschema fix #280
* [x] README.md #280
* [x] README 英文ベース作成 #287
* [ ] README 英文チェック

# アルゴリズムやロジックの解説

図説・数式(画像)、疑似コードによる説明。英文化等の進行が遅くなるのでこちらに隔離します。
内容的に英文チェック無しで、たぶん大丈夫。

* [ ] SpringBone 慣性ロジック解説
* [ ] SpringBone 衝突ロジック解説
* [ ] Constraint Position/Rotation 解説
* [ ] Constraint Aim 解説
* [ ] LookAt ロジック解説
* [ ] FirstPerson Autoロジック解説
* [x] Humanoid 回転・スケールの除去ロジック解説
* [ ]  Expression Override ロジック解説
* [ ]  Expression MorphTargetBind ロジック解説
* [ ]  Expression MaterialColorBind ロジック解説
* [ ]  Expression TextureTransformBind ロジック解説

**Comment by ousttrue** [comment]
おおまかにタスク化しました。
各項に PR を投げていこうと思います。

@FMS-Cat

**Comment by FMS-Cat** [comment]
ありがとうございます！

**Comment by 0b5vr** [comment]
本issueは機能してないので、一旦closeします。
