### ISSUE TITLE
[1.0] Change implementation of rim lighting in vrmc_materials_mtoon

### ISSUE THREAD

**Issue by Santarh** [vrm-c/vrm-specification#270]
`vrmc_materials_mtoon` の Rim Lighting に関して計算式の変更提案、およびそれに付随するプロパティ名変更の提案です。

主旨
- `parametricRimColorFactor` を `rimMultiplyTexture` に対応する色と定義し、 Parametric Rim だけではなく Matcap の色も変更できるようにする
- `parametricRimColorFactor` を `rimColorFactor` に rename
- `rimMultiplyTexture` を `rimColorTexture` に rename

現在 `parametricRimColorFactor` は Parametric Rim に作用します。
一方で Matcap には作用せず、若干不便です。

また、組になる Texture はありません。
glTF や MToon の定義において、色の Factor は Texture と組になっていることが多い (ex. `baseColorFactor` `shadeColorFactor` )です。

これらから、次の計算式への変更を提案します。

```
let matcap: ColorRGB = texture( matcapTexture, matcapUv ).rgb
let parametricRim: Number = pow( saturate( 1.0 - dot( N, V ) + parametricRimLiftFactor ), parametricRimFresnelPowerFactor )
let rimLightingFactor: Number = lerp( ColorRGB( 1.0, 1.0, 1.0 ), lightColor, rimLightingMixFactor )

let rim: colorRGB = (matcap + parametricRim.rrr) * rimColorTexture * rimColorFactor * rimLightingFactor
```

**Comment by FMS-Cat** [comment]
確かに、 `parametricRimColorFactor` をパラメトリックリムのみに絞る理由はなさそうです。良いです！

**Comment by FMS-Cat** [comment]
手元で実装を行ってみています。
`parametricRimColorFactor` をmatcapにも反映させる場合ですが、パラメトリックリムを使わずにmatCapのみを使いたい場合に対応できないかもしれないです。

**Comment by FMS-Cat** [comment]
> 手元で実装を行ってみています。
> `parametricRimColorFactor` をmatcapにも反映させる場合ですが、パラメトリックリムを使わずにmatCapのみを使いたい場合に対応できないかもしれないです。

これに対応するため、matcap用に新たにプロパティを追加する方針としたいと思います。
現在、プロパティ名を検討中です。

**Comment by FMS-Cat** [comment]
プロパティ名について、 `matcapFactor` とします。
プロパティを追加するPRを作成します。
