### ISSUE TITLE
[suggestion][1.0draft] about materialvaluebind value name.

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#31]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#materialvaluebind
I suggest to change materialValues[*].material to materialValues[*].（material）index.

for easy to read.

**Comment by hiroj** [comment]
This is in accordance with the specification method of gltf.
https://github.com/KhronosGroup/glTF/blob/c50a7b3c18bf272ef23ddbeddc0d158b839483d4/specification/2.0/schema/mesh.primitive.schema.json#L21

**Comment by iCyP** [comment]
I understand it. 
Thank you for reply.
This is not necessary.
