### ISSUE TITLE
インストールできない

### ISSUE THREAD

**Issue by YusukeMasuda36** [vrm-c/vrm-specification#312]
●環境
windows10 21H1
unity 2019.4.13
https://github.com/keijiro/KlakNDI
UniVRM v0.78.0

KlanNDIにUniVRMをインストールを行っていますがメニューバーに表示が出ずにUniVRMの正常なインストールができません。
対処法ご教授頂けないでしょうか

**Comment by FMS-Cat** [comment]
Duplicate of https://github.com/vrm-c/UniVRM/issues/1097

こちらはVRM仕様のissueとなりますので、UniVRMレポジトリ側で議論をお願いします。
