### ISSUE TITLE
Is the `VRMC_vrm` still a large specification about entire VRM?

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#32]
In our VRM 1.0, I heard the identifier for the extension seems to be going to be `VRMC_vrm`,
Is there any plan to separate each component of VRM?

For example, spring bone is very easy to separate from `VRMC_vrm` since it has no dependency on other VRM components.
Honestly, I want to separate all the components regardless of each dependency though.

If we can do that, it is an excellent opportunity to have at least partial support of VRM on each platform or environment since they don't have to implement entire VRM specs.

**Comment by hiroj** [comment]
The springbone and constraint are very independent and can be separated from VRMCVrm.
The other parameters are interdependent or essential information (meta, humanoid) as VRM, so it is necessary to consider whether it is better to separate everything.

**Comment by hiroj** [comment]
https://github.com/vrm-c/vrm-specification/tree/master/specification
Springbone and Constraint extensions are separated.

**Comment by hiroj** [comment]
ConstraintとSpringBoneは別拡張に分離されることになったのでこのissueはcloseします
