### ISSUE TITLE
[MToon] Also use alpha value of _ShadeColor for transparency

### ISSUE THREAD

**Issue by blzq** [vrm-c/vrm-specification#324]
Only the RGB value of `ShadeColor` is used to determine the shaded colour while the alpha value is taken from the lit `_Color`. However in some situations using the alpha value of the `_ShadeColor` for transparency can be useful. For example, if eye highlights are created as an object, this would allow the highlights to become invisible in shade or shadow.

**Comment by 0b5vr** [comment]
技術委員会内で議論を行いました。

alphaの挙動について、glTFで定められた挙動より必要以上に逸脱をしたくないという見解に落ち着きました。
また、このような仕様の例を他に知らないこと・ラスタライザ実装以外のケアが難しいこと・glTF標準のマテリアルへのフォールバックも難しいなどが、他の懸念事項として上がります。

> For example, if eye highlights are created as an object, this would allow the highlights to become invisible in shade or shadow.

本例につきましては、baseColorTextureとshadeColorTexture間でハイライトの出し分けを行う（＝ハイライトを焼き込む）ことで解決はできませんか？

**Comment by blzq** [comment]
なるほどです。glTFのスペックについてあまり詳しくないけど、他の要件を満たすのほうが重要と見られます。

本例について、本来の考えはよりリアルなハイライトのために、ハイライトの位置を固定したい（目と共に動きたくない）と思っていました。それでもまあ、ハイライトをオブジェクトとして作ったところでリアルは既にアウトですね。
