### ISSUE TITLE
Please add the ability to set matcaps to multiply

### ISSUE THREAD

**Issue by Octuplex** [vrm-c/vrm-specification#325]
When the matcap is set to additive, any toon matcaps will severely wash the model out. I imagine adding another mixing option for matcaps would be lightweight and relatively simple to do.

Multiply
![ua52TMQtJw](https://user-images.githubusercontent.com/45321166/129644796-89b05a49-0199-4943-8560-0a246581db0f.gif)
Additive
![szuddTmES1](https://user-images.githubusercontent.com/45321166/129644816-aa19a583-8960-4030-bd7c-d5d387011835.gif)

**Comment by 0b5vr** [comment]
ping @Santarh 

MatcapおよびParametric Rimに加算および乗算を切り替えるスイッチもしくはスライダーを付与する方針となりそうですが、
他のトゥーンマテリアル実装を参考にしつつ、本当に必要かを吟味すると思います。

**Comment by Santarh** [comment]
English follows Japanese.

MatCap 相当のビュー座標系テクスチャマッピング情報を乗算すれば表現の幅が広がる、ということは理解します。

しかしユーザパラメータによって計算ロジックが変更される手法は、シェーダという実装手段の上においては負荷の高いものだと考えます。
なぜなら実装上、次のどちらかの手段を取らざるを得ないからです。
1. シェーダ実装を増やす (ex. preprocessor による shader variant )
2. どちらのパラメタを選んでいたとしても、乗算・加算どちらも計算を行う

1. の場合は実装の保守上の負荷、および実行プラットフォーム上のシェーダ数の大幅な増加が問題となります。
2. の場合は実行上の負荷の増加が問題となります。

同じ理由で断念したパラメータは過去にもありました。
したがって残念ではありますが、自分としては否定的です。

I agree that multiplying the texture mapping using the view coordinate system (MatCap) extends expression.

However, I think that the method of changing the calculation logic by user parameters is a heavy load on the shader implementation.
Specifically, we must adopt one of the following two methods.

1. Increase shader implementation (ex. the shader variants by using preprocessor)
2. Calculate both multiplication and addition methods.

In case of 1, it will be a problem of software maintainance, and increase shader implementation extremely.
In case of 2, it will be increasing execution load.

In the past, there were parameters that were abandoned for similar reasons.
So, unfortunately, I'm negative about this feature addition.

**Comment by 0b5vr** [comment]
技術委員会内でも議論をしました。
上でさんたーさんが述べている通り、ロジックの追加を伴う仕様変更を十分な確信度なしに行うのは難しいため、本件は断念します。
