### ISSUE TITLE
VRM Public Licenseについての質問および改善案

### ISSUE THREAD

**Issue by yakumo-proj** [vrm-c/vrm-specification#326]
https://vrm.dev/licenses/1.0/

おそらくVRM-1.0公開に先駆けて、モデラーさんが許可して欲しい基本ルールを文書化したものだと思われますが
いくつか気になる点がありますので、問題提起させていただきます。

# 第２条の "無償" ないしは"royalty-free" の不統一について

どういう意味で「無償」なのかなと、素朴な疑問です。
第１条のほか規約全体の趣旨と、英語版の表記がroyalty-freeとなっているのを鑑みて、意図するところは、ライセンサーはライセンシーに対して、イニシャルフィー（事前料金）を支払わせてもよいと思われます。
（逆にイニシャルフィーも含めて無償であることを意図するならCreative Commonsとの違いがよくわかりません）

事前料金の支払いが定められている使用許諾契約の成立は基本的に
・ライセンシーが料金を支払い使用許諾契約に同意する（順不同）
・ライセンサーはライセンシーの著作物の使用を許諾する
の双務契約となります。

実用上は使用許諾契約内容を先に示してBOOTHなどの販売ページでは「使用許諾契約を読んだうえで購入してください」
などの運用になっているかと思います。

データが無償ならライセンシーに何を購入させてるんですかって話になるので、第２条の「無償」表記は明らかな誤りになりますね。
「三千円払えば10連ガチャが無償で引ける」の無償（これは皮肉で言ってますよ）の意味であれば、明らかにライセンサー・ライセンシー間の齟齬をうむので再検討いただきたいのですが。

* 指摘通り有償での使用許諾契約を想定するならばの話ですが、消費者契約法や景品表示法の規定により、販売者たるライセンサー側は、社会通念上わかりやすい言葉で、正確かつ明確に契約内容を事前明示する義務を負います(8/12追記)

# 「誤解を避けるために記すと〜」がという表現が多用されているわりに理解しづらい

たとえば第３条の禁止表現規定については、どこの国の何法何条何項に基づいて禁止すると言っているのかわかりませんが、アメリカ合衆国連邦法では「宗教目的表現又は政治目的表現」は禁止できないという解釈が支配的かと思われます。

* VRMパブリックライセンスには「日本法に準拠し、第一審の専属的合意管轄裁判所を〇〇地方裁判所とする」などの記載もないですから、VRChatなどの海外のサービスの利用者が違反を行なった場合、現地の裁判管轄になります。その際に法律の違いが問題となります。
日本の著作権法において「宗教目的表現又は政治目的表現」を拒否するのは著作者人格権に根拠づけられますが、米国著作権法には著作者人格権の概念自体がなく、かつ米国が政治的・宗教的主張も含めて表現の自由を重んじる国であることをライセンサーおよび規約策定者は考慮に入れておくべきで、DMCA申立等によって使用停止を訴えても失当となりかねません。(8/12追記)

もっとも、ライセンサーが法律の根拠なく規約本文あるいは独自の附帯条項によって義務の加重や権利の制限ができないことは第7条の「誤解を避けるために記すと〜」で言及されているからという解釈もしようがありますが、知財法の専門職や勉強している人以外はなかなかわからないと思います。

なんとなく英文契約書ベースで起案して日本語に翻訳したっぽい雰囲気を感じますが、専門知識が前提にないと理解できないような文章であるなら共通の利用規約を提案する意味も薄れると思います。

（いずれにしろroyalty-free＝無償という誤訳はいただけない）

**Comment by s-iwaki-d** [comment]
ご意見として承りました。確認させていただいたのですが、

1. クリエイティブ・コモンズも「無償」及び「royalty-free」の各表現を使っており、VRMパブリックライセンスでもそれを踏襲したものです。なお、この「ロイヤリティなし」というのは、元来、ご指摘の「イニシャルフィー」もなしの意味です。
2. VRMパブリックライセンスを利用するある国において何らかの強行法規（当事者の合意によっても適用を排除できない法令等）が適用される場合、いかなるライセンス規定を設けても当該強行法規に従うものとされ、準拠法を定めてもそれは同じなのですが、適用法令により許容される限度でライセンス規定は有効であるということを、念のためうたっておくという趣旨です。

とのことで、致命的な問題ではないとのことで逐次変更はせずいったんこのままとさせていただきます。
ありがとうございます、今後参考にさせていただきます。
