### ISSUE TITLE
VRM1.0-beta以降のアップデートをまとめておきます

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/vrm-specification#327]
実装に特に強く影響するアップデートについて、太字にしてあります。

- #322: isBinaryのしきい値がgreater than 0から0.5 or greaterになりました。
- #328: `allowAntisocialOrHateUsage` が仕様文の表から抜け落ちていたため、これを追加しました。
- #331: MToon, `KHR_materials_unlit` より `VRMC_materials_mtoon` が優先される旨を追記しました。
- #332: Meta, `allowRedistribution` の初期値がテーブルから抜け落ちていたため、これを追加しました。
- #334: Expressions, MaterialColorBindの `targetValue` について、4つ目の値が宛先にない場合は無視する旨を記述しました。
- #341: **エクスポート時のボーンのトランスフォーム正規化についての仕様を削除しました。**
    - また、Tポーズに関連するドキュメントをhumanoidのドキュメントから分離しました。
- #345: MToonのschemaにおいて、 `required` フィールドに誤りがあったため、これを修正しました。
- #346: Expressionsのschemaにおいて、 `neutral` プリセットが抜けていたため、これを修正しました。
- #349: `firstPerson.meshAnnotations` 指定が存在しない場合のフォールバックについて、仕様内で言及しました。
- #350: `meta.licenseUrl` が期待する値について、仕様内で明示的に言及しました。
- #353: `VRMC_springBone` について、 `specVersion` プロパティが必須になっていなかったため、これを必須としました。
- #354: VRMのコンポーネントの実行順序について、仕様の解釈に直接影響しない文言修正を行いました。
- #360: **Humanoidボーンに対して、スケールとして正の値のみを許容する仕様としました。**
- #363: SpringBoneについて、Implementation noteをより詳細に追記しました。
- #364: LookAtの基準位置について、ドキュメントを追記しました。
- #366: LookAtのrangeMapについて、一部ドキュメントに誤ってradianと単位が表記されていた箇所をdegreeに修正しました。
- #369: **`VRMC_node_constraint` 拡張を `1.0-beta` に昇格しました。**
- #372: SpringBoneのリファレンス実装の修正を行いました。
- #374: **SpringBoneの `center` プロパティを再導入しました。**
- #375: **`VRMC_materials_hdr_emissiveMultiplier` をアーカイブしました。**
    - 後継として、 `KHR_materials_emissive_strength` を用いることが推奨されます。
- #379, #381: **親指のボーン名について、より人体構造に基づいた名前 Metacarpal -> Proximal -> Distal に変更を行いました。**
- #378: VRM T-poseについて、定義を一新しました。
- #383: **SpringBoneの `center` は、そのSpringBoneの0番目のJointもしくはその祖先である必要があるという制約を追加しました。**
- #386: LookAt仕様について、内容をわかりやすくしました。要旨は変わりません。
- #387: サンプルモデル `Seed-san.vrm` を追加しました。
- #388: 仕様内タイポの修正です。
- #389: shoulderの親がupperChestでなくchestと表記されている箇所を修正しました。
- #390: コンストレイント内、staleな仕様であるmodel spaceに関する言及が残っていたため、これを消しました。
- #391: **MToonのemissiveTextureについて、UV Animationをするように仕様を変更しました。**
- #392: **MToonのOutlineについて、Lighting Mixに寄与するファクタを変更しました（emissiveとrim lightingを加味）。**
- #394: **ExpressionsのMaterialColorTypeに `matcapColor` を追加しました。MToonの `matcapFactor` に対応します。**
- #398: **MToonの `matcapFactor` のデフォルト値を `[1, 1, 1]` から `[0, 0, 0]` に変更しました。**
- #399: springBoneのcollidersについて、半径にminimum制約を追加しました。
- #401: lookAtのrangeMapについて、スキーマにminimum/maximum制約を追加しました。
- #402: MToonのスキーマについて、minimum/maximum制約を追加しました。
- #403: ExpressionsのSchema内、 `isBinary` の説明が古かったため、これを修正しました。

以下はConstraint (1.0-draft) に関係する変更ですが、一応併記しておきます:

<details>
<summary>staleな変更</summary>

- #342: Constraintから、Rotation, Local to Local以外の仕様を一回取りました。
- #343: Constraintのドキュメントがschemaと乖離していたため、これを修正しました。
- #352: Constraintの `freezeAxes` プロパティを `axes` にリネームしました。
</details>

- #355: Constraintの仕様を大幅に改訂しました。
- #365: AimConstraintの `aimAxis` の値 `+X` , `-X` , `+Y` ... をシンボル名フレンドリーな `PositiveX` , `NegativeX` , `PositiveY` ... に変更しました。
- #368: RollConstraintの擬似コードを修正しました。

**Comment by FujiSunflower** [comment]
VRMをユーザー利用している方がGithubを知らない可能性がありますので、[VRMコンソーシアム](https://twitter.com/vrm_pr)でも告知すると良いかもしれません。[このまま問題が見つからなければ正式版として発効の予定](https://www.youtube.com/watch?v=u-9y3nsKdhw)があるそうですので、告知は大事かと思われます。

**Comment by magurosan** [comment]
「黒船」たるVRM対抗フォーマットがMeta社あたりから出るかもしれない時期に悠長に議論を重ねて1.0の策定を先延ばしにしたら良いというものではありません。1.0をまずリリースしてから次に向けての方針を決めては？

**Comment by s-iwaki-d** [comment]
みなさまご意見ありがとうございます
VRM 1.0についてはほぼ固まってきており、「まずリリース」のフェーズに入っていると考えています。ここからのさらなる機能拡張や大幅な変更は想定しておりません。
ドキュメントの不備に対しては認識しており、現在必要なドキュメントの洗い出しを進めております。
実行環境については次回リリースからUniVRMのサンプルビューアのビルドも同時に公開していくことを検討しております。
こういった技術仕様外のドキュメントやテスト環境などについては課題として今後改善していきますのでよろしくお願いいたします。

**Comment by 0b5vr** [comment]
VRM1.0正式版のリリースに伴い、本issueはクローズします。
