### ISSUE TITLE
[1.0draft] what about Material VRM/unlitZwriteTransparent?

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#33]
It uses materialPropaterty.
But not define in this repository.
Deprecated?

**Comment by hiroj** [comment]
transparentWithZWrite can be specified in MToon but not in other (Unlit and Standerd).
https://github.com/vrm-c/vrm-specification/blob/67d875a72174fa22bc01f80e7b2c6f070b583836/specification/VRMC_materials_mtoon-1.0_draft/schema/VRMC_materials_mtoon.schema.json#L18

**Comment by iCyP** [comment]
Does it means ** in 1.0** ?
uniVRM0.53 has shader of VRM/unlitZwriteTransparent
![コメント 2019-12-03 015904](https://user-images.githubusercontent.com/3232308/69979010-cd1d6e80-1570-11ea-8d04-7565b9f5ab9e.png)

**Comment by ousttrue** [comment]
UniVRMに入っていたVRM/unlitZwriteTransparentシェーダーは、VRM-1.0 の仕様には入りません。
独自に追加するシェーダーは、MToonだけとなります。
MToon のRenderingType に TransparentWithZWrite したものが同様の動作をします(通常のTransparentは深度バッファを更新しない)
