### ISSUE TITLE
urlLicense

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#336]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0-beta/meta.ja.md#metalicenseurl-

具体的な URLに対する言及

* https://vrm.dev/licenses/1.0/
* https://vrm.dev/licenses/1.0/en/

の使い分けについて。

**Comment by 0b5vr** [comment]
固定値として `https://vrm.dev/licenses/1.0/` を認める旨を仕様ドキュメントに追記します。
