### ISSUE TITLE
Eyebrow Threshold Lessened From Beta To Stable Build

### ISSUE THREAD

**Issue by RadicalEdward2** [vrm-c/vrm-specification#339]
I recently converted my model from beta to the newest stable build and noticed that the eyebrow motions are so drastically reduced that they're barely noticeable in models exported from the current stable build. I'm not sure if the same applies for new models made in the current build but, regardless, I'm probably going to stick to the beta version until the problem is resolved because the decreased brow tracking severely limits the amount of character facial expressions.
![vroid brow before](https://user-images.githubusercontent.com/25542788/143478116-36649c4e-1d30-42b8-a65f-a6243ca718d0.jpg)
![vroid brow after](https://user-images.githubusercontent.com/25542788/143478114-9000a411-4429-4f18-add3-d10616b72306.jpg)

**Comment by TokageItLab** [comment]
@RadicalEdward2 Isn't this issue a VRoid issue and not a VRM issue? I guess, you are misreading VRoid 1.0 and VRM 1.0. There is no relationship between them directly.

**Comment by RadicalEdward2** [comment]
@TokageItLab oh okay. I wasn't sure if this was the github for Vroid. But if it still sort of relates to VRMs, would you by any chance know how I could fix the issue? I've experimented with tweaking models in unity, would it be possible to do something through that?

**Comment by TokageItLab** [comment]
@RadicalEdward2 I apologize if I failed to convey the meaning. This issue is a VRoid issue, not a VRM issue, so I think it is appropriate way that this issue be closed.
