### ISSUE TITLE
[1.0] Unhandled "required" property in mtoon schema

### ISSUE THREAD

**Issue by infosia** [vrm-c/vrm-specification#340]
I think I found unhandled `required` property in [VRMC_materials_mtoon.schema.json](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json#L156).

```json
"required": [
    "version"
]
```

I think this was meant to be `specVersion`.

**Comment by 0b5vr** [comment]
wow! That's correct. I will fix this
