### ISSUE TITLE
Constraints, source space might need "Local Space (Owner Orientation)" like Blender does

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/vrm-specification#347]
コンストレイントの検証中に気になった点をissueにしておきます。

以下のモデルをツイストボーンの検証用に作成したのですが:

[blender-vrm-bone-with-twist-bones.zip](https://github.com/vrm-c/vrm-specification/files/7922717/blender-vrm-bone-with-twist-bones.zip)

ツイストボーンのSourceとDestinationの回転軸が異なる場合に、現状のLocalの仕様だと回転が正しく作用されないことがわかりました。

以下は、 `LeftFoot` をSourceとし、 `LeftLowerLeg` 以下のツイストボーン（`LeftLowerLeg` と同じ回転軸）に回転を伝搬しようとした場合の図です:

https://user-images.githubusercontent.com/7824814/150723894-67f67bee-b9c0-4548-ad95-416a99d09cf2.mp4

回転が想定するツイストボーンの動きよりも弱く伝搬しています。

対照に、以下は `LeftLowerLeg` をSourceとし、 `LeftUpperLeg` 以下のツイストボーン（`LeftUpperLeg` と同じ回転軸）に回転を伝搬しようとした場合です:

https://user-images.githubusercontent.com/7824814/150724057-8f181015-0d94-4d8c-8e19-862ddd9e5148.mp4

Blenderにおいても動揺の問題が発生しますが、Blenderにおいては「Local Space (Owner Orientation)」というスペースを適用することで、本問題を解消することができます:

![image](https://user-images.githubusercontent.com/7824814/150724133-dd26cd19-6686-4e31-b0ad-cc26d2028b24.png)

これは、Sourceの回転をDestinationの回転軸で再評価して適用するという設定であり、このようなSourceとDestinationの回転軸が異なる場合に有用に働くことがあります。

この機能がVRMのコンストレイントの仕様にも盛り込まれていると良いのではないかと思いました。

以下に、「Local Space (Owner Orientation)」を適用した状態の当該モデルのblendファイルを添付しておきます。

[blender-vrm-bone-with-twist-bones.zip](https://github.com/vrm-c/vrm-specification/files/7922745/blender-vrm-bone-with-twist-bones.zip)

**Comment by 0b5vr** [comment]
トカゲさんと話をして、「Local with Parent」というスペースのほうがよりフレキシブルな設定ができる可能性があるというディスカッションをしました。

**Comment by TokageItLab** [comment]
このような斜めのボーンに対しては Owner Orientation が Blender 3.0 で追加されるまでは Local with Parent と参照用の補助ボーンを用いて解決するのが一般的であったように考えております。ただし、それらの挙動はある程度互換性があるものの完全には一致しなさそうで、どちらにも使い道があるように思えます。

VRM Constraint が Source Offset (Target Offset ?) を持つのであれば、それは Local with Parent に代替しうると考えられるので、目下必要なのは Owner Orientation だと思っております。

**Comment by 0b5vr** [comment]
Dumped TrackというのはVRMにおいては以前Aim Constraint (World-World) として定義されていたものですね。これってコンストレイントを適用する順番も重要になるってことですよね。難しい……

**Comment by 0b5vr** [comment]
技術委員会内でデモを見つつ確認をし、一旦1.0では現状通りLocal to Localのみ仕様とする方針になりました。
引き続き、検証に必要なサンプル数が少ない状態ですので、検証に参加いただける方を歓迎します。

**Comment by 0b5vr** [comment]
Constraintの仕様のアップデートによりclosingします。
