### ISSUE TITLE
[1.0] Spec of first person, describe about cases when meshes are not annotated

### ISSUE THREAD

**Issue by 0b5vr** [vrm-c/vrm-specification#348]
FirstPersonの仕様について、メッシュがannotation内で指定されていなかった場合にどうすべきかを仕様に盛り込んでおくと良さそうです。
加えて、 `firstPerson` 自体が存在しなかった場合についても決めておきたいです。

おそらく、全部Autoにフォールバックという仕様で良いかな？と思っていますが、いかがでしょう。

**Comment by ousttrue** [comment]
UniVRM-0.X の挙動がまさに auto にフォールバックで、それがいいと思います。

**Comment by 0b5vr** [comment]
了解です！書いてPR出します。
