### ISSUE TITLE
[suggestion][1.0draft][MToon] color factor

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#35]
I want litFactor, shadeFactor and colors propaties name end with *color.
何の値か全体的に分かりにくいです。

**Comment by hiroj** [comment]
以下を参考にFactorで統一しましたが、分かりにくいのは確かなのでcolor値は*Colorに変更したいと思います。
https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md#extending-materials

**Comment by hiroj** [comment]
GltfがFactorで統一されていたため表記はFactorのままにします。
