### ISSUE TITLE
Lit Shader support?

### ISSUE THREAD

**Issue by alienself** [vrm-c/vrm-specification#357]
Hi there,

I would like to know if there are any plans to support Lit shaders. 
It seems like the current format is heavily bias toward anime avatars using toon shading.
What happens if I want my avatar to be influenced by light?

Thanks!

**Comment by 0b5vr** [comment]
You can use PBR material that glTF supports in VRM.

for VRM 0.0,

You can set `USE_GLTF_SHADERS` to `/extensions/VRM/materialProperties/{i}/shader` to use materials that glTF supports.

for VRM1.0,

if you don't use `VRMC_materials_mtoon` extension to a material that would be assumed as an ordinary glTF PBR shader.
