### ISSUE TITLE
Compatibility with Creative Commons licenses

### ISSUE THREAD

**Issue by mrxz** [vrm-c/vrm-specification#358]
I'm looking into using the VRM format (1.0-beta) in one of my projects for avatars. To better understand the specification I've forked the glTF-validator and added support for `VRMC_vrm` and `VRMC_springBone` ([vrm-validator](https://vrm-validator.fern.solutions/)). I couldn't find many sample files, so I'm currently creating some VRM files for testing purposes. My goal is to release these sample files, but the way licensing is handled in the specification seems limiting.

If I understand correctly, the `licenseUrl` is a required property and may only have the value "https://vrm.dev/licenses/1.0/". This means that all valid VRM files fall under the VRM Public License. However, my idea was to release the sample files under public domain (CC0) or possibly CC-BY-SA 4.0. This doesn't seem possible at the moment.

My question is:

1. Can a VRM file be licensed under a different license than the VRM Public License? If so, how should this be indicated in `VRMC_vrm.meta`?
2. If not, can the VRM Public License be expanded to specifically be compatible with (some of the) CC licenses? Depending on the license settings, the VRM Public License already seems to allow many of the same things the Creative Commons licenses would.

**Comment by s-iwaki-d** [comment]
You can create VRM files under a different license than the VRM Public License. The licenseUrl in VRMC_vrm.meta should still be "https://vrm.dev/licenses/1.0/".
Your own license is set in VRMC_vrm.meta.otherLicenseUrl.
Please read Section 2(a)(4) and 2(a)(5) of the VRM Public License Document.
Thanks,

**Comment by mrxz** [comment]
Thanks, though I'm not sure those two sections actually resolve the issue. Section 2(a)(4) does indeed allow additional license terms to be specified. But section 2(a)(5) only covers the case where _Exceptions and Limitations_ apply to "Copyright and Similar Rights" (essentially the exceptions to these rights embedded in the law depending on the relevant country and usage of the work).

I do believe this works for CC0, as it isn't strictly a license, but waivers the copyright. So there is an actual _exception_ to copyright in that case, meaning section 2(a)(5) applies.
But this doesn't work for many other licenses, including CC-BY-SA 4.0. These don't form an exception to copyright (or similar rights), but provide a license for people to use the copyrighted material. As such, I don't believe section 2(a)(5) would be in effect.

I'm not a lawyer, so perhaps I'm missing something. Regardless, I do believe the VRM Public License would benefit from a more explicit section regarding using alternative licenses.

**Comment by s-iwaki-d** [comment]
Sorry, my erroneous response caused your confusion.
2(a)(1)(E) and 2(a)(4) allow licensors to establish their own licenses; 2(a)(5) indicates a limitation on rights under the law, which is different from this context.
