### ISSUE TITLE
[1.0draft]Is VRMC_materials_mtoon.renderQueueOffsetNumber really needs parameter?

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#36]
It was called renderQueue before in materialPropaties.
It don't have explanations.
It looks automaticaly decided by uniVRM. 

Is VRMC_materials_mtoon.renderQueueOffsetNumber really needs parameter?
I want to remove it.

**Comment by hiroj** [comment]
renderQueueOffsetNumber is an MToon function that controls the rendering order by specifying an offset to the automatically set renderQueue value.
I want to leave as much as possible because it is necessary depending on the situation.

**Comment by iCyP** [comment]
I understand it is very Deep specification and it has necessary in severe situation. (In particular it uses in game engines for enterprise movie).
Then, it needs more detailed documentation(limitation of number and normally number width) or more simple value(like renderQueuePriority : ["ground","normal","overwrite"] etc...) for end users. 

However, I think this specification.( It have problem about where does it locate.)
```
 renderingOrder : [ material_index ]
```
It shows rendering order as list.

**Comment by iCyP** [comment]
参考: https://github.com/Santarh/MToon/issues/17
 Opaque -> 2000
 Cutout -> 2450
 TransparentZWrite -> [2501～2550] (default: 2501)
 Transparent -> [2951～3000] (default: 3000)
らしいです。

**Comment by hiroj** [comment]
This parameter is used and will continue in v1.0.
