### ISSUE TITLE
lookAt の LookAtRangeMap.outputScale の単位

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#361]
Degree と Radian 記述が混在している。
どっちかに統一。

`Degree`
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0-beta/schema/VRMC_vrm.lookAt.rangeMap.schema.json

`Radian`
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0-beta/lookAt.ja.md

**Comment by 0b5vr** [comment]
うわ！全然気づきませんでした。

VRM0と同じ挙動・UnityのUIでも頻出であるdegreeで良いと思います。

**Comment by 0b5vr** [comment]
Resolved @ #361
