### ISSUE TITLE
[1.0draft]unupdated document about 視線制御

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#38]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E6%B0%B4%E5%B9%B3%E5%86%85%E5%A4%96%E5%9E%82%E7%9B%B4%E4%B8%8A%E4%B8%8B

更新エクセルを見る限り、xRange,yRange、はそれぞれinputMaxValue,outputScaleに変更になったはずではないでしょうか？

**Comment by hiroj** [comment]
ドキュメントの方を修正致します。
