### ISSUE TITLE
[1.0]親指のボーン名を metacarpal, proximal, distal に変更する

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#380]
関連ドキュメントを更新する

- [ ] https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0-beta/humanoid.md
- [ ] https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0-beta/humanoid.ja.md

**Comment by 0b5vr** [comment]
要旨は達成されました。
