### ISSUE TITLE
[1.0draft] collider rotation value kinds.

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#39]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#collider

I think uniVRM will show on inspector by radians. 
Radians is not easy to read by human. 
I want Rotation value to be Euler-degree.

**Comment by iCyP** [comment]
In addition, From degree units should be unificationed.
So, change lookAt's degree units too.

**Comment by hiroj** [comment]
Using glff reference, the angles are unified to radians.
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#coordinate-system-and-units
> All angles are in radians.

**Comment by iCyP** [comment]
I understand.
Sorry for inconvenience.
