### ISSUE TITLE
[1.0draft] unsafe chars escape example is imperfect.

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#40]
[escape example](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E5%90%8D%E5%89%8D%E3%81%AE%E3%82%A8%E3%82%B9%E3%82%B1%E3%83%BC%E3%83%97%E4%BE%8B) is imperfect.
There isn't think about (改行 easy to injection) \n \r , Null char(\x00) and so on.

I escaping chars as below.
https://github.com/iCyP/VRM_IMPORTER_for_Blender2_8/blob/master/importer/vrm_load.py#L125-L131

**Comment by ousttrue** [comment]
I want to avoid names that are problematic on Windows with respect to naming conventions.
If I can avoid the Windows file path problem, there is no problem with other operating systems.
Application specific issues are supposed to be handled by the importer.

* case sensitive
* escape as unicode encoding

Sinlge chars
```py
    unsafe_chars = {
             0: '\x00', 1: '\x01', 2: '\x02', 3: '\x03', 4: '\x04', 5: '\x05', 6: '\x06', 7: '\x07', 8: '\x08', 9: '\t', 10: '\n',\
             11: '\x0b', 12: '\x0c', 13: '\r', 14: '\x0e', 15: '\x0f', 16: '\x10', 17: '\x11', 18: '\x12', 19: '\x13', 20: '\x14',\
             21: '\x15', 22: '\x16', 23: '\x17', 24: '\x18', 25: '\x19', 26: '\x1a', 27: '\x1b', 28: '\x1c', 29: '\x1d', 30: '\x1e',\
             31: '\x1f', 34: '"', 42: '*', 47: '/', 58: ':', 60: '<', 62: '>', 63: '?', 92: '\\', 124: '|'
             } 
```

Reserved symbol
```
Do not use the following reserved names for the name of a file:
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.
```

suffix
```
Do not end a file or directory name with a space or a period.
```

When the importer creates a file, the end of the name may not be restricted because it can be assumed that an extension is added to the name.

**Comment by iCyP** [comment]
e.g.: https://ascii.jp/elem/000/001/786/1786156/
Windows has filename flag of case sensitive or not. And, default is **no case sensitive** by above. (e.g. in default :  c:\HOGE\AAA.x = c:\hoge\aaa.x ) 
Then, I think limitation of  :case insensitive: - :unique names:  is necessary.

AND do you remember **file path length limit** on windows? Be carefully. https://github.com/vrm-c/UniVRM/issues/153

**BUT** I think if uniVRM uses to create files that is independent by object name, this spec (case semsitivity )is not necessary. 
And it can be, because VRM is **finalized** file format (now, I believe,).  (e.g.: blendshape name belong to blendshapeGroup's target name of 'JOY' will be 'JOY_1,JOY_2, and JOY_3' or bake to one blendshape.  (these are very violence spec...) *Many referenced blendshapes name needs more discussion.)

BTW, do you have experience of [unity on linux](https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256/)?  Will it be no support? If it have support, linux filenames will be issued.

**Comment by ousttrue** [comment]
I revised my first summary comment a little.

And more,

* length limit(unicode char count) 260

>  linux filenames

I don't know well.
Is there anything other than `/` `;` and pipe related '>' '<' '|' ?

> blendshape name belong to blendshapeGroup's target name of 'JOY' will be 'JOY_1,JOY_2, and JOY_3' or bake to one blendshape

ここ、意味がよく分からないです。

**Comment by ousttrue** [comment]
|   | 0    | 1    | 2      | 3      | 4 | 5      | 6          | 7        |
|:--|:-----|:-----|:-------|:-------|:--|:-------|:-----------|:---------|
| 0 | (X0) | (X0) | space  | 0      | @ | P      | back quote | p        |
| 1 | (X0) | (X0) | !      | 1      | A | Q      | a          | q        |
| 2 | (X0) | (X0) | "      | 2      | B | R      | b          | r        |
| 3 | (X0) | (X0) | #      | 3      | C | S      | c          | s        |
| 4 | (X0) | (X0) | $      | 4      | D | T      | d          | t        |
| 5 | (X0) | (X0) | %      | 5      | E | U      | e          | u        |
| 6 | (X0) | (X0) | &      | 6      | F | V      | f          | v        |
| 7 | (X0) | (X0) | '      | 7      | G | W      | g          | w        |
| 8 | (X0) | (X0) | (      | 8      | H | X      | h          | x        |
| 9 | (X0) | (X0) | )      | 9      | I | Y      | i          | y        |
| A | (X0) | (X0) | * (X2) | : (X1) | J | Z      | j          | z        |
| B | (X0) | (X0) | +      | ;      | K | [      | k          | {        |
| C | (X0) | (X0) | ,      | < (X2) | L | \ (X1) | l          | pipe(X2) |
| D | (X0) | (X0) | -      | =      | M | ]      | m          | }        |
| E | (X0) | (X0) | .      | > (X2) | N | ^ | n          | ~        |
| F | (X0) | (X0) | / (X1) | ? (X2) | O | _      | o          | (X0)     |

* X0: 禁止 制御文字
* X1: 禁止 パスの区切り文字、ドライブ区切り
* X2: 禁止 シェルで意味がある(glob, pipe)

ASCIIの禁止を整理しました。
quote(single, double, back)は特に問題なさそう。

**Comment by iCyP** [comment]
私もファイル名の長さを５０までと(適当に)リミットして名前を変更しています。
as https://github.com/iCyP/VRM_IMPORTER_for_Blender2_8/blob/master/importer/vrm_load.py#L163-L165

Linuxファイル名： \0 とかは絶対ダメとか、"."から始まると隠しフォルダになるとか...
https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits 
https://en.wikipedia.org/wiki/Filename#Comparison%20of%20filename%20limitations
が参考になりそうです。下の方が読みやすい？

Blendshapeについて具体的に言うと、BlendshapeGroupに含まれるblendshapeの名前をそれぞれ全部属性+indexに置換してしまうという案です。
例えば 、
```
    {
        "name": "A",
        "presetName": "a",
        "binds": [
            {
                "mesh": "0",
                "index": "2",
                "weight": 1.0
            },           {
                "mesh": "0",
                "index": "9",
                "weight": 1.0
            }
        ],
        "materialValues": [],
        "isBinary": false
    },
```
のような場合、 mesh : 0 のindex : 2のもののモーフターゲットの名前を(primitives.extras.target_namesを無視して)JOY_0、9のものをJOY_1として(blendshapegroupの配列のインデックス順に命名して)unity ediorでファイル名として扱うということです。
　もしくはgroup内ののモーフターゲットをすべて合成したモーフターゲットをエクスポート時に生成して、それを使うのはどうか、ということです。
　ただし、一つのモーフターゲットを複数のblendshapegroupに使われたとき(例えば、”a”,"i","u","e","o"がすべて口を開いているだけの一つのモーフターゲットを指している場合等)どうするかは考えないといけない、また、再編集したい人には困るという問題があります。

**Comment by saturday06** [comment]
WindowsのMAX_PATH制限の回避のために64文字制限をする場合は「😀」とか「𩸽」とかのサロゲートペアの文字が、文字数としては一文字だけどデータとしてはアルファベットとか平仮名の二倍(4バイト)使っていることにも気を付ける必要があると思いました。Windows APIがMAX_PATHの260文字制限をする場合は文字数ではなく `MAX_PATH * sizeof(wchar_t)` での換算なのでもろにその制限が効いてくる。

**Comment by ousttrue** [comment]
> BlendshapeGroupに含まれるblendshapeの名前をそれぞれ全部属性+indexに置換してしまうという案

別Issueにお願いします。

> WindowsのMAX_PATH制限の回避

どんなフォルダに展開されるか予測不可能なので、 `無限に長い文字列を避ける` を目的にしてます。最終的な責任は、Windows上でファイルに展開するプログラムが負うことになります。
とりあえず目安として、実装の楽な ucs2 の配列長 もしくは、unicode のコードポイント数(少し実装が面倒) で 64 にしようとしています。

**Comment by ousttrue** [comment]
* \0 Ascii表で除去済み
* "." で始まる。bash の ls などの実装の問題なので、"/" を避ける等に比べると弱いような気もします。

致命的なやつだけ避けたいです。

* そもそも作れなくてエラーになる
* 作れるが、操作できなかったり、エスケープが必要になる

**Comment by iCyP** [comment]
>別issueへ
　そもそもはdocumentationの問題で、仕様上は何が入ってきてもおかしくないので、こういう対策をしておきなさいの例示が不足している、という話をしたかった(仕様で長さや名前を制限するのは逆にそれを突かれたときに死ぬので意味がない)を思い出しました……のでuniVRMの方に建てました。

**Comment by ousttrue** [comment]
問題が出るのは UniVRM が Editorロード時にアセットを名前でライトするという動きをするためで、
UniVRM でもアセットを書き込まない Runtimeロードでは特に問題はありません。
なので、 VRM フォーマットとしてはファイル名としての名前は気にしない(必要であれば適当にリネームするなど実装が対応する)ということにしました。
