### ISSUE TITLE
[1.0draft] firstPersonBoneOffsetについて

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#41]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#%E4%B8%80%E4%BA%BA%E7%A7%B0

私は専門外なのですが、首からヘッドセットの位置は人によって違うと思う（本当に？問題になるほど？という疑念はありますが…）ので、首を縦横に振るなどでヘッドセットの回転半径からオフセットを推定させるキャリブレーションを行うことにした方が良い結果を得られると思うのですが、どうなのでしょうか。（それならこのプロパティを廃止できるのではと考えます？

**Comment by sh-akira** [comment]
これについて、
ヘッドボーンからのヘッドセット(トラッカー)への位置offsetです
となっていますが、目線の位置を設定するもの(頭が大きいモデル等で目の高さや前後位置がかわるため)と思っていましたが、
HMDの位置ということで正しいんでしょうか。
そもそもHMDの位置だとしたらトラッカーの位置とはまた違うので説明が間違っていないでしょうか。

**Comment by ousttrue** [comment]
現状について説明します。

firstPersonBoneOffsetはHMDの位置設定として始まりました。
後からできたlookAtが基準位置に同じ項目を流用しています。

lookAtの基準点であることがわかる名前の方がわかりやすいとおもいます。
検討中です。

**Comment by ousttrue** [comment]
意見を参考にして、

* firstPerson.firstPersonBoneOffset を lookAt.offsetFromHeadBone に変更しました
* firstPerson.firstPersonBone が HeadBone 以外ありえなくて自明であろうということで削除することにしました

> 首からヘッドセットの位置は人によって違うと思う

HMDのだいたいの位置として初期位置の参考に lookAt.offsetFromHeadBone を使うことをお勧めしております。自由に実装して問題ありません。
