### ISSUE TITLE
[animation] JsonSchema とサンプルデータで食い違い発見

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#426]
#425 に関連して

サンプルデータでは、階層が `root/extensions/VRMC_vrm_animation/humanoid/humanBones/head`
となっているのに対して、
JsonSchema では `root/extensions/VRMC_vrm_animation/humanoid/head` となっているようです。
どちらにしましょう。

**Comment by 0b5vr** [comment]
なるほど！VRM仕様に合わせること・将来的なhumanoidの拡張性を見ると、 `/extensions/VRMC_vrm_animation/humanoid/humanBones/head` のほうが良さそうですね。
JSON Schemaを修正します。
