### ISSUE TITLE
[1.0draft] BlendShapeにおけるマテリアルバインドの変更可能な値について

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#43]
[materialbind](https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#materialvaluebind)
color, uvScale, uvOffset以外の変更はできなくなる（shadecolor、shadeshift等)のはイケてないと思うのですがこれら3つのみに限定したのはなにか理由があってのことでしょうか？
　なければmtoon系プロパティを全体的にサポートされている方が良いと思います。

**Comment by ousttrue** [comment]
理由は、

* VRMC_materials_mtoon 仕様がまだ固まり切っていない(プロパティ名とか構成名が変わるかもしれない)
* Materialの任意のプロパティを指定する方法を思案中(relativeなJsonPath ?)
* UniVRM-0.XXではGUIで3項目に制限していたので、任意項を変更可能にすると拡張になる

となります。
GLTFの

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/animation.channel.target.schema.json

が進化して任意のMaterialプロパティを指し示す方法ができるとよいのですが。
VRM-1.0では、任意項目への拡張をやめておく考えです。

**Comment by iCyP** [comment]
つまり先に決めるものが決まってないので最低限決まっているもののみの状態という事ですね。
ただ、GUIで3項目に制限というのは初耳です、0.53ではわりと色々設定できるようですが・・・

**Comment by ousttrue** [comment]
![material_props](https://user-images.githubusercontent.com/68057/70301802-bca21800-183e-11ea-9c6a-7b1c784b3224.jpg)

変更内容に間違いがありました。
修正します。

* color(mainColorを意図していた) => Color型のプロパティ個別
  * MToonの場合が対象に
    * _Color
    * _ShaderColor
    * _RimColor
    * _EmissionColor
    * _OutlineColor
  * Unlit
    * _Color
  * Standard(PBR)
    * _Color
    * _EmissionColor

* テクスチャごとに個別の UV 変化を許容していた => すべてのUVを参照するテクスチャの Offset, Scale を共通にする

**Comment by hiroj** [comment]
"title": "MaterialValueTypes",
      "type": "string",
      "enum": [
        "color",
        "shadeColor",
        "rimColor",
        "emissionColor",
        "outlineColor",
        "uvScale",
        "uvOffset"
      ]
    },
0.xで指定出来ていた項目を追加してみました、個別のテクスチャを操作可能にするかどうかは検討する必要があると思います。

**Comment by FMS-Cat** [comment]
MToonにしかないパラメータ群が本仕様に含まれている点が気になりましたので、
MToon独自の値について、拡張を用いてcolorの選択肢が広げられるような定義とすることが可能かを検討します。

**Comment by ousttrue** [comment]
TODO: enumの各項目がGltf上のどの項目に該当するのか明示する(baseColorなど)

**Comment by FMS-Cat** [comment]
先ほど口頭で述べた、MToonも `baseColorFactor` を見に行けばよいのでは？というのは、こちらで話題に挙げております: https://github.com/vrm-c/vrm-specification/issues/127

**Comment by FMS-Cat** [comment]
> enum の各項目とMaterialのJsonでの対応項目

こちらをPRにした上でこちらのissueはCloseさせていただきます
