### ISSUE TITLE
[VRMA] lookat の値について

### ISSUE THREAD

**Issue by ousttrue** [vrm-c/vrm-specification#435]
２パターンありそうな気がします。

* 注視点の移動値
* Yaw, Pitch の直接値

どうやって値を生成するかとも関連していて、生成してから相互に変換するのは面倒なので両方の方式を許容したいような気がします。

**Comment by ousttrue** [comment]
注視点はモデル座標系でアニメーションを解決するので、
頭が移動したり回転したりすると同時に、Yaw, Pitch が機械的に等速運動するような場合に
Yaw, Pitch で記録する方がかなり楽になる。
逆もまた然りで、両方できた方が便利。

ここで、注視点を頭の子ノードにする手が考えられますが、
#437 の非ヒューマノイドボーンのアニメーション問題が浮上してくるかもしれない。
組み合わせの複雑さを軽減したい。

**Comment by 0b5vr** [comment]
Yaw-pitchを収録する方針で議論が帰着・使用にも反映済み。閉じます。
