### ISSUE TITLE
"Aim" node constraint is defined as roll

### ISSUE THREAD

**Issue by aaronfranke** [vrm-c/vrm-specification#441]
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_node_constraint-1.0#aim-constraint

> Aim Constraint
> 
> **Roll** Constraint constrains a rotation of a destination to make it aim towards a source.
> 
> The **Roll** Constraint is intended to be used for the following purposes:
> 
> **Roll** Constraint assumes hierarchies like following for example:

I put in bold some of the words that are wrong. I would PR a fix for this myself but someone familiar with the spec should look over the whole section to check if everything else is correct.

**Comment by 0b5vr** [comment]
@aaronfranke 
Yes, it seems to be a typo indeed, thank you for pointing this out! Would you make a PR?
