### ISSUE TITLE
VRMC_springBone_extended_collider-1.0はドラフト仕様ですか？

### ISSUE THREAD

**Issue by FujiSunflower** [vrm-c/vrm-specification#469]
VRMC_springBone_extended_collider-1.0は検討中の草案でしょうか？
それともmasterブランチにマージされているのでいずれ追加するのは決定済みでしょうか？
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_springBone_extended_collider-1.0/README.ja.md

追加が決定済みだった場合、アプリケーション開発者での差異への対処が必要となるかなと思います。
https://vrm.dev/vrm/vrm_about/
> VR でのアバター表現が急速に盛り上がるなか、こういった状況が続くとアプリケーション開発者にとっても、3D モデルクリエイターにとっても二度手間三度手間になってしまいます。 この状況を改善するために
> 
>     「人型のキャラクターやアバター」において
>     細かいモデルデータの差違を吸収・統一し
>     アプリケーション側の取り扱いを簡単にする
> 
> 「VRM」は、このような特徴のある「プラットフォーム非依存の 3D アバターファイルフォーマット」を提案する ものです。

**Comment by FujiSunflower** [comment]
検討中のdraft仕様という返答は頂いたのでCloseしておきます。

**Comment by 0b5vr** [comment]
> VRMC_springBone_extended_colliderに対応していないアプリの場合は書き出し時にフォールバックとして追加された標準のSphere Colliderを読み込むように感じました。Inside Sphere ColliderはVRM 1系での標準のSphere Colliderと真逆の挙動をします。Inside Sphere Colliderの書き出し時にフォールバックとして標準のSphere Colliderが追加されるのなら、アプリによってはVRM作者の想定と真逆の挙動になるかなと思います。フォールバックではなく対応していないアプリでは拡張は無視されるというのが自然かなと思いました。

当該Implementation Noteにあります通り、フォールバックのSphere Colliderは揺れものに対して影響を及ぼさないように原点から遠く離した球コライダーとすることを推奨しています。本当はフォールバック環境においてコライダーを追加しないような挙動ができれば一番良いのですが、それが実現できないため、コライダーを原点から遠く離すことによってコライダーがない状態を擬似的に再現しようとしています。

具体的な例を[仕様内glTF Schema Updatesの冒頭のJSON例](https://github.com/vrm-c/vrm-specification/blob/5fa583bc0e63782e5897880adf7be2ff561b3e94/specification/VRMC_springBone_extended_collider-1.0/README.ja.md#extending-nodes)に記載しています。
この例では、インサイドコライダーに対するフォールバックを半径が0・位置が(0, -10000, 0)となるSphere Colliderとして定義し、擬似的にフォールバック環境でのコライダーを無効化しています。
