### ISSUE TITLE
[suggestion][1.0draft]inverseBindMatrices について

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#48]
省略できませんか？ノードのtranslationから生成できますし、逆にノードのtraslationと矛盾するIBMは実装者を混乱させると思います。

**Comment by ousttrue** [comment]
調べてみました。

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skin
> The index of the accessor containing the floating-point 4x4 inverse-bind matrices. The default is that each matrix is a 4x4 identity matrix, which implies that inverse-bind matrices were pre-applied.

まさかの仕様で、省略したときヒエラルキーから計算するようになっていませんでした。
VRMは、glbとして成立するようにしたいので省略できません。

ただ、正規化済みのVRMであれば

> ノードのtraslationと矛盾するIBM

はVRMとしてはエラーなので、その点ドキュメントに追記します。

* importer: inverseBindMatrices を無視して ノードの translation から算出してもよいこと
* exporter: ノードのtranslationから移動行列を得るべきであること

**Comment by iCyP** [comment]
デフォルトではIBM上はボーンが一点に集中してるような状態なんですかね…
お手数おかけしまして申し訳ありません。
承知いたしました。
