### ISSUE TITLE
READMEとJSON Schemaでデフォルト値が異なっている箇所がある

### ISSUE THREAD

**Issue by ChameleonO2** [vrm-c/vrm-specification#484]
[VRMC_materials_mtoon-1.0](https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0)
について

READMEに書かれているdefault値とJSON Schemaに書かれているdefault値が異なっている箇所があります。
これらについて、それぞれどちらを真として扱えばよろしいでしょうか？

--- 

https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_materials_mtoon-1.0/README.ja.md#parametricrimfresnelpowerfactor

> |                                 | 型          | 説明                      | 必須                    |
> |:--------------------------------|:------------|:--------------------------|:------------------------|
> | parametricRimFresnelPowerFactor | `number`    | パラメトリックリムライトのフレネル係数     | No, 初期値: `5.0`       |

https://github.com/vrm-c/vrm-specification/blob/9e8c886a2043639a3c166eb7cc93526be6313147/specification/VRMC_materials_mtoon-1.0/schema/VRMC_materials_mtoon.schema.json#L100-L105

--- 

https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_materials_mtoon-1.0/README.ja.md#rimLightingMixFactor

> |                                 | 型          | 説明                      | 必須                    |
> |:--------------------------------|:------------|:--------------------------|:------------------------|
>| rimLightingMixFactor            | `number`    | リムライティングの光源からの影響の割合 | No, 初期値: `1.0`       |

https://github.com/vrm-c/vrm-specification/blob/9e8c886a2043639a3c166eb7cc93526be6313147/specification/VRMC_materials_mtoon-1.0/schema/VRMC_materials_mtoon.schema.json#L93-L99

**Comment by 0b5vr** [comment]
報告ありがとうございます！

ドキュメント側が正しいというのが私の見解ですが、一応 @Santarh さんの見解もお伺いしておきたいです。

**Comment by 0b5vr** [comment]
こちら、Santarhさんにも確認取れ、READMEの記述が正しいということなので、その通り修正させていただきます。
