### ISSUE TITLE
glTF形式の、アバターでないオブジェクトデータなどにもライセンスデータを持たせたい

### ISSUE THREAD

**Issue by m-sigepon** [vrm-c/vrm-specification#5]
VRMの仕様に関する議論が分かれたようなのでこちらに移します。
https://github.com/vrm-c/UniVRM/issues/170

例えば、キャラクターに読み込ませるアクセサリや、背景などにもライセンスデータを持ったglTFベースのフォーマットが必要かと思われます。

**Comment by iCyP** [comment]
VCIが発展したものがそれになると見られます。
https://github.com/virtual-cast/VCI
https://virtualcast.jp/wiki/doku.php?id=vci:top

まだ、
＞このライブラリはアルファバージョンで機能の変更があります。 製品に組み込まないでください。Runtimeのエクスポートは未確認です。
ですが。

**Comment by araigumaG** [comment]
さきのリポジトリではglTF本体側で策定が行われている[KHR_XMP拡張](KhronosGroup/glTF#1553)などが案として挙げられていたので[リンク]((vrm-c/UniVRM#167))しておきます。SpokeやSketchfabでの使用を想定しているようで、glTFのノード単位でのライセンス情報を含んだメタデータ付与が可能であるようです。(むしろglTF側がメタデータ関連の語彙を丸投げしそうな勢いに見えます。)

ダブリン・コアの語彙をXMP持ってくる形なので、現在想定されているユース毎の許諾のモデルをそのまま記述する訳にはいかないでしょうが、個人的には[Open Digital Rights Language](https://www.w3.org/TR/odrl-vocab/)等を用いて拡張すれば機械可読に実装できるのではないかと考えています。

**Comment by s-iwaki-d** [comment]
こちらはVRMとはいったん別の議論になるかと存じますのでVRM specのissueとしてはcloseさせていただきます
