### ISSUE TITLE
[1.0draft] Windows special file name like `nul` `nul.foo` may disallowed for material and blendshape name

### ISSUE THREAD

**Issue by saturday06** [vrm-c/vrm-specification#55]
Windows special file name like `nul` `nul.foo` may disallowed for material and blendshape name because microsoft documentation says:

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

> Do not use the following reserved names for the name of a file:
> CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by  an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

> Do not end a file or directory name with a space or a period. 

and 

> https://github.com/vrm-c/vrm-specification/issues/53#issuecomment-560207153 god mode path

**Comment by ousttrue** [comment]
Aggregate name escape related issues.
Duplicate of #40

**Comment by saturday06** [comment]
OK, Thanks.
