### ISSUE TITLE
[1.0draft] Material and blendshape name are case sensitive?

### ISSUE THREAD

**Issue by saturday06** [vrm-c/vrm-specification#56]
Documentation says:

> Make all names unique
> Use characters that can be used for the file name

If that `can be used for the file name` rules is for extracting assets to filesystem. Material and blendshape name must be case sensitive unique.

**Comment by ousttrue** [comment]
Aggregate name escape related issues.
Duplicate of #40

**Comment by saturday06** [comment]
👍
