### ISSUE TITLE
[1.0draft] Colliders: Isn't the `shapeType` redundant?

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#58]
Related: #42 

https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/README.ja.md#collider

仕様には、 `collider.size` には、 `shapeType` がSphereのときは半径・Capsuleのときは半径と長さを格納するとありますが、
`shapeType` によって `collider.size` のフォーマットが違うことに少し気持ち悪さを感じています。

Capsuleについて、長さを0.0とおけばSphereと等価になりますので、
`sphereType` を端折って代理に `length` を独立したパラメタとするのはいかがでしょうか？

**Comment by iCyP** [comment]
パラメタの長さが変わるのは気持ち悪いに同意します。勘は汎用的vec4くらいあれば困らないんじゃないかと囁きます。
　shapeType自体は将来反転Sphireなども入れられるよう拡張性のため、残したほうが良いと思います。

**Comment by FMS-Cat** [comment]
> shapeType自体は将来反転Sphireなども入れられるよう拡張性のため、残したほうが良いと思います。

これについては、v1.0で他の形状を追加する予定があるか否かで意見を変えます。

**Comment by hiroj** [comment]
他の形状を追加する可能性はあると思います。

#122 のようにcolliderがSpringBone以外からも参照される可能性が出てきたこともありshapeTypeは残しておきたいです。
形状によって必要な情報の長さが違うためこのような形になっていますが、もう少し分かりやすい記述等あれば変更いたします。

**Comment by FMS-Cat** [comment]
将来的な拡張性を担保しつつ、JSON Schemaとして記述可能な形に落とし込もうとすると、以下のように、コライダーの形状をキーとし、形状の詳細を `object` に格納する形が適切かなと思いました。
もっとも、将来的に拡張する場合は、ここにさらに `extensions` フィールドを追加するような形が最も適切となると思いますが……

```json
{
    "offset": [ 0.0, 0.0, 0.0 ],
    "rotation": [ 0.0, 0.0, 0.0, 1.0 ],
    "sphere": {
        "radius": 1.0
    }
}
```

```json
{
    "offset": [ 0.0, 0.0, 0.0 ],
    "rotation": [ 0.0, 0.0, 0.0, 1.0 ],
    "capsule": {
        "radius": 1.0,
        "length": 1.0
    }
}
```

**Comment by FMS-Cat** [comment]
#122 のousttrueさんの実装例がいい感じです。このissueは役目を終えたと判断し、閉じさせていただきます。
