### ISSUE TITLE
コンストレイントをサポートしてほしい

### ISSUE THREAD

**Issue by m-sigepon** [vrm-c/vrm-specification#6]
VRMの仕様に関する議論が分かれたようなのでこちらに移します。
https://github.com/vrm-c/UniVRM/issues/50

現在、VRMではSpringBoneによる揺れ物をサポートしていますが
それと同じように、拡張情報としてVRMでコンストレイントをサポートしてほしいです。
すでに、頭部などでLookAtとして特定の部位に対して実装されていると思います。
これを、セカンダリのように任意のジョイントに設定できる機能が欲しいです。
例えば、使いたい場所として体の、肘ボーンや膝ボーンやねじれ防止のツイストボーンをコンストレイントで追従させるというような箇所です。
それ以外にも、衣装の一部を連動させて動かしたいなどにもコンストレイントが可能になるとウェイトのみで処理しないといけない部分の問題が解決します。

サポートしてほしいコンストレイントとしては、Unity標準でサポートされているような以下のコンストレイントになります。
https://docs.unity3d.com/Manual/Constraints.html
・方向コンストレイント（Aim Constraints）
・位置コンストレイント（Position Constraints）
・回転コンストレイント（Rotation Constraints）
・スケールコンストレイント（Scale Constraints）

**Comment by hiroj** [comment]
VRM1.0にてConstraintを追加する予定です。
詳細仕様や実装についてはこれから検討致します。

**Comment by pixiv-sigepon** [comment]
コンストレイントサポートありがとうございます
宜しくお願いいたします。

**Comment by m-sigepon** [comment]
#71 (comment) でコメントしたのですが、コンストレイント制御は動的にアクセスしてその設定を変更できる仕様になっていてほしいです。
例えばアタッチ先などが動的に変更できなどの仕様となります。

**Comment by hiroj** [comment]
VRMとしてはhips以外は移動せず回転しかしないため、回転コンストレイントのみを仕様として組み込むのが良いかなと思うのですが、想定されている用途としては回転のみだと不十分でしょうか？
https://github.com/vrm-c/vrm-specification/issues/71#issuecomment-564394426
こちらのコメントに書いていただいた、武器を持たせたりアタッチ先を動的に変更する等は、VRMの仕様というよりもアプリケーションの実装に任せた方が良いかなと考えています。

**Comment by pixiv-sigepon** [comment]
用途を整理してみたいと思います
以下は、アバターを作る上でほしいコンストレイントになります。
よく使うコンストレイントですね。
■回転コンストレイント（Rotation Constraints）
・肘、膝ボーンなどを、中間位置に向かせるために利用、ねじれ回避ボーンなども
■Look Atコンストレイント
・Tシャツの袖にボーンを設定して肘をターゲットにして向きは追従するけど袖そのものは回転しないのに利用


■位置コンストレイント
例えば、アタッチはアプリケーション毎に実装するというのは分かるのですが、
共通企画としての、位置コンストレイントが欲しいなと感じます。
例えば、Unityの位置コンストレイントを使って鞘を越しにつけたり刀を手に持ったりするアバターがいたとして、それをUE4に持っていったときにそのアバターのコンストレイント情報はVRMに保存できなかったら、コンストレイント情報を復元できません。
UE4でも、同様のコンストレイント情報を元に刀を持たせることができる。
そのために、キャラクターそのものに位置コンストレイントの情報をもたせれるようになっていると、プラットフォームやアプリを跨いだ情報の同期が取れると考えております。
如何でしょうか。

**Comment by FMS-Cat** [comment]
回転・LookAtについて、実現可能性を検討の上、次回再び議論します。
位置・スケールについて、社内で議論した上、次回再び議論します。

**Comment by m-sigepon** [comment]
LookAtについては自分が仕様の確認不足で、Z軸方向固定でしたのでAimコンストレイントに置き換えて頂ければと思います。

**Comment by pixiv-sigepon** [comment]
LookAtコンストレイントは、Z軸固定という仕様を見逃しておりましたので上位互換であるAimコンストレイントに訂正しました。

https://docs.unity3d.com/ja/2018.4/Manual/class-LookAtConstraint.html
>Look At は、Aim Constraint の簡略バージョンです。Aim Constraint では、ソースゲームオブジェクトを照準する軸を選択できますが、Look At Constraint では常に Z 軸です。

**Comment by FMS-Cat** [comment]
スキーマ #144 がマージされました。引き続き、仕様についての議論を #188 で進行しています。
