### ISSUE TITLE
テクスチャ圧縮の検討について

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#63]
手元で試したことを共有します。
リソース：Vroid モデル1体分に含まれるすべてのテクスチャ(png)の一括変換(法線マップ・透過画像も含まれる
試したこと：
 - Xnviewにてjpeg(80%品質)に変換（alpha・法線マップ考慮すべきだがしていない)
 - bmpに変換(alpha同上)
 - TEXCONVにてdds-BC3, BC7に変換
 - KhronosGroup/toktx_toolにてKTX(**2ではない**)に変換
 - ImageMagicを使ってwebpに変換
 - 上記をzip圧縮（7zipを使用

結果　ファイル数：４６

|フォーマット|フォルダサイズ(MB)|zipped(MB)|対応するgltf拡張|
|---|--:|--:|---|
|png(ソース)|20|20|デフォルト|
|jpeg|1.93|1.58|デフォルト|
|BMP|156|17|なし|
|BC3|52|7|MSFT_texture_dds|
|BC7|52|20|MSFT_texture_dds|
|KTX|117|15|なし。2はﾌｫｰﾏｯﾄがDraft13@2019-11-13|
|webp|0.8|0.7|EXT_texture_webp|
|basis|1.6|1.6|まだないっぽい|

~~webpはBlenderで読み込めないのと手元でｶﾞｯとやれるツールが見つけられなかったので無いです（ないです~~ imagemagicを思い出したので追記しましたが、サムネを比べる限り正常に動いているようですが、可逆非可逆込みでオプションがわかってない上にエラー吐いてるのに出たバイナリなのでよくわかりません（でも圧縮率がえぐい）　**でもWebPはBlenderで現状IO出来ないので入れてほしくないです(強願望)**

さらに以下より追記：basis これもコマンドラインやドキュメントのオプションでエラーが出るので無オプションです。
https://github.com/vrm-c/vrm-specification/issues/63#issuecomment-561554384

参考になれば幸いです。
p.s.
 - ktx-tool は https://github.com/KhronosGroup/KTX-Software をビルドします。面倒はvulcanSDKをインストールするくらいでした。(楽でした
 - texconv はここから https://github.com/microsoft/DirectXTex/releases
 - imagemagicはここから　https://imagemagick.org/script/download.php

**Comment by iCyP** [comment]
webPを追記しました

**Comment by m-sigepon** [comment]
圧縮テクスチャは、モバイルでGPUで扱えるフォーマットが重要になると思います。
また、アルファチャンネルを扱えるフォーマットもベースとなると思います。

**Comment by iCyP** [comment]
basisの実行結果を追記しました

**Comment by hiroj** [comment]
返答大変遅くなって申し訳ありません。
詳しく調査して頂きありがとうございます！すごく助かります。
WebPに関してはUnityでもIOが困難なため、MSFT_lod( #74 )と同様にアプリケーションがハブサービスにWebP変換を要求した場合にだけ入手出来るものとし、ユーザが手元の環境でWebPを取り扱うことは考慮しなくて良いかなと思いました。（同様にAndroidであればASTCにするなど）
KTX 2.0 Basis Universalは良さそうですが、まだgltf拡張(KHR_image_ktx2?)が開発中になっているためspec1.0に取り込むのは難しい気がしてます。
https://github.com/KhronosGroup/glTF/blob/master/extensions/README.md

**Comment by FMS-Cat** [comment]
ひとまず、本件はglTF側で進行している・すでに存在する拡張群で解決が可能なトピックとなりますので、VRMのチームで検討すべき事柄ではないかなと思いますが、いかがでしょう。

**Comment by FMS-Cat** [comment]
一旦VRMの仕様としては圧縮テクスチャについて言及をすることはしない方針とします。
