### ISSUE TITLE
[suggestion][1.0draft] more usage steps and kinds.

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#68]
I suggest like this.
```
violentUsageLevel = [Everyone,R12,R15,R17,R18,Mature,Unlimited]
sexialUsageLevel = [Everyone,R12,R15,R17,R18,Mature,Unlimited]
politicalUsage = [Disallow,Allow]
DiscriminationUsage =  [Disallow] 
DisallowedPerformance = Array["Smoking","Sex","Alcohol",etc...]
commercialUsage= [Disallow, AllowPersonalUsing, AllowCompanyUsing,OnlyAllowedByLicence]
```

VRMCでの法務検討の議論がどれだけ進んでいるのかわからないのでとりあえず提案してみます。
商用についてはそのまんまなので説明を割愛します。
レーティングのステップ・その幅は議論を要します（とりあえずCERO(コンシューマゲームのあれ)に合わせてみました、ESRB（北米版のそれ）なども参考になるともいます）。unlimitedは正直過剰かもしれませんが…(モデルモーション両作者に強い影響がありうる)。
DisallowedPerformance(禁止する演技) も上記2組織の表示が参考になると思います。

**Comment by iCyP** [comment]
DisallowedPerformance について、R15,R18、など包括的な制限を定義しても良いかもしれません
```
DisallowedPerformance : ["R18",something]
```
でVRMのR18表現制限で定義された全般と、なにかしら表現を禁じたい特定の行為、といった感じです

**Comment by s-iwaki-d** [comment]
検討しましたが、国によって定義が異なるなど設定する側から見ると使い勝手に難があり
最終的にはVRMパブリック・ライセンス文書 1.0の形とさせていただきました
https://vrm.dev/licenses/1.0/
