### ISSUE TITLE
ルート (Model Space) の位置の標準化 (またはガイドラインの策定)

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#71]
https://github.com/vrm-c/vrm-specification/pull/188#issuecomment-749868654

~~Hips の子孫以外の階層にあるボーンについて、その取り扱いを標準化できませんか。~~

既存のサービスで挙動を確認してみました~~が、Clarieの実装がもっとも直感的に見えました~~。

- [THE SEED ONLINE](https://seed.online/)
    + 旧ビューア
        * 原点に固定？
- [VRoid Hub](https://hub.vroid.com/)
    + 原点に固定
- [バーチャルキャスト](https://virtualcast.jp/) 1.8.2c
    + 一人称視点
        * 位置のみHipsに追従、ただし縦位置は追従せず
    + 三人称視点
        * 原点に固定
- [Clarie](https://biscrat.booth.pm/items/1193414) 0.12.2
    + 位置のみHipsに追従、ただし縦位置は床の高さに追従

確認に使用したVRMファイルを以下に置いています。
https://hub.vroid.com/characters/230301780840982732/models/7639832113922707713

------------------------------------------------------------

<del>
hips の子孫以外のノードにウェイトが載ったメッシュ、または hips の子孫以外にスキニングされていないメッシュがある場合、その挙動は実装依存でそういったメッシュは有用でないため、以下のような制約が必要かと思います。

- 「hipsかその子孫」以外のノードが mesh を持つ場合、skin を持ってはならない
- skin の joints、および skeleton は「hipsかその子孫」でなければならない

問題が起きるVRMファイルの例
https://hub.vroid.com/characters/230301780840982732/models/7639832113922707713
</del>

**Comment by iCyP** [comment]
床基準は飛行できる場合を含めると、問題が生じるかと思います。
よって例えば、背後に何か浮いていたり、コンパニオン的存在がある場合は、然るべきhumanoidボーンの子にすべきであると考えます。

　個人的には not require [root(動かない)->in-between(動かない) ] -> hips->...の一本の樹状構造にVRMのnode hierarchyおよびskinsを制約すべきと考えます。

　また、添付のOuterHipsはscenesの中で親子関係が人モデルと明らかに分かれているものであり、それは原点から動かないのが然るべき状態であり、それを(spring bone以外で)動かす理由はないと考えます。
　逆に動くのは親子関係を無視しています。せめて、すべてのnodeの頂点にrootを組み込まれ、その子として動く挙動をするのが妥当と考えます。

**Comment by esperecyan** [comment]
そもそも現行の仕様で挙動が決定できないような場所へのskinsを許容すべきでないということですね。であれば、hips以下に制限した方が良さそうです。issueを書き替えます。

**Comment by m-sigepon** [comment]
武器を持っている場合など、HumanoidのHip以外に別のWeaponなどの別構造のボーンを同一に持ちさらに、今後コンストレイントが実装されるのを考えるとHIpの子孫以下以外のボーンにスキニングされてるのは十分ありえるケースです。
また今後コンストレイントが実装された場合、それを手にコンストレイントするなどの実装も考えられるため、HIps以下のボーンにのみスキニングが有効なのは現実的ではありません。

**Comment by iCyP** [comment]
私見ですが、 #6 を拝見する限り、Constraintはhumanoid管理外のボーンを 静的 に制御することで、捻りボーンやspring boneの動きの制限などを実現し、アバターのルックを良くするために提案されたものと認識していました。
 しかし、https://github.com/vrm-c/vrm-specification/issues/71#issuecomment-564394426  で仰せる剣の持ち変え・装備／抜刀状態の変更用途等、ユーザのアクションで動的にConstraintを変更できる仕組みを希望されるのであれば、話が変わってくると思うので、その旨 #6 に記載すべきと私は思います。（その仕組みはVCIが担うところであるかなと思いますが・・・
 そして、その採用如何に、https://github.com/vrm-c/vrm-specification/issues/71#issuecomment-564394426 のご指摘は依ると私は考えます。

**Comment by m-sigepon** [comment]
剣は一例ですね。使い方は多岐に渡ると思います。

**Comment by esperecyan** [comment]
初期状態でhips以下のどのボーンにも紐づけられない場合、VRMファイルへ含めるのが適当でないメッシュであることを示唆していると考えられないでしょうか。

一例として挙げられている「キャラ固有のアイテムのようなもの」の場合、アイテムなのでVCIファイルで扱うのが適当で、キャラ固有の部分については、VRMファイル側かVCIファイル側かあるいは別の仕様で関連付けを設定するのが良いのではないかと思います。

**Comment by ousttrue** [comment]
禁止しようかと思ったけど、
constraint と組み合わせるとあってもよいような気もした

* root
  * hips
  * constraint で humanoid を参照する node

👆というような構成。

禁止すると👇を強制することになりそう。

* root
  * hips
    * constraint で humanoid を参照する node

**Comment by esperecyan** [comment]
前者は Constraint spaces の model space のときに問題があるという感じですかね……？

**Comment by FMS-Cat** [comment]
仕様をかなり厳密に定義しないと、曖昧で解釈の難しい仕様となりそうなため、仕様としてこれを定義することは見送ります。
ただ、このような場合がよくあることは把握しておりますので、なんらかガイドラインを示すことを検討したいと思います。
一旦は、このようなモデルはglTFのsceneのルートごと動かすような実装をアプリケーションに要請する方針が良さそうかなと考えておりますが、いかがでしょう。
（VRoid Hubも現状はモデルのルートでなくHipsを動かす実装になっていて申し訳ないです……）

**Comment by esperecyan** [comment]
なるほど。
取り扱いについてガイドラインを示すということであれば、それでもかまわないと思います。

**Comment by esperecyan** [comment]
https://github.com/vrm-c/vrm-specification/pull/188#issuecomment-749868654 を踏まえ、最初のタイトルと内容へ戻しました。

**Comment by TokageItLab** [comment]
#118 のアニメーション定義とも関わりがあると思われますので参照を貼ります。
もしくはルートモーションへの対応について別 issue を立てた方がいいでしょうか。

**Comment by FMS-Cat** [comment]
> #118 のアニメーション定義とも関わりがあると思われますので参照を貼ります。
> もしくはルートモーションへの対応について別 issue を立てた方がいいでしょうか。

ルートモーションについては引き続き #118 で議論しましょう（この案はとても好きです！）。
本issueは引き続き、VRMアプリケーション開発者がルートとHipsの違いを理解できる文書をガイドラインに残すことをゴールとしたいです。

**Comment by 0b5vr** [comment]
VRM仕様に、以下のような文言を追加することを検討しています。

> ### モデル空間
> 
> VRMでは、VRMモデルを構成するglTFシーンの原点から相対にトランスフォームを観測する「モデル空間」を定義します。
> これは、VRMモデルを扱うアプリケーション上のワールド空間とは区別されます。
> 
> モデル空間は、 [`VRMC_node_constraint`](../VRMC_node_constraint-1.0_draft/README.ja.md) 拡張で利用されます。
> 
> > VRMモデルをアプリケーション上で動かす際は、Humanoidで定義するHipsを動かすだけでなく、
> > glTFシーンのルートごとモデルを動かすことにより、モデル空間を尊重することが期待されます。
> > 言い換えれば、モデルのルートが常にワールド空間のルートに留まるような利用は推奨されません。
