### ISSUE TITLE
JSON Schema において制約を定義する

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#72]
VRM-0.0 のスキーマファイルにおいて、すべてのプロパティは任意となっています。
https://github.com/vrm-c/vrm-specification/tree/master/specification/0.0/schema

しかしながら、すでに THE SEED ONLINE や VRoid Hub などのリポジトリでは、`VRC_Meta.meta.version` などのプロパティが存在していることを要求しています ( https://github.com/vrm-c/UniVRM/issues/333 )。また、UniVRM-0.53.0 においてもエディタ上で Export humanoid する場合、`VRC_Meta.meta.title`、`VRC_Meta.meta.author` が空文字列でないことを要求されます。

以上は `VRC_Meta.meta` における実例ですが、ドキュメントで制約について明示されている項目であっても、ドキュメントと JSON Schema を同じ内容にすることで、https://github.com/vrm-c/vrm-specification/issues/8#issuecomment-527298136 でも言及されていますが JSON Schema の有用性が高まると考えます。

**Comment by hiroj** [comment]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/schema/VRMC_vrm.springBone.schema.json
一部項目のdescriptionにrequiredを追記しました、後で内容をrequiredノードに移動させます

**Comment by FMS-Cat** [comment]
本件、glTFのcoreスキーマと同様に、必要な箇所に `required` `minItems` `maxItems` を付与する形で少しずつ進行しております。

**Comment by 0b5vr** [comment]
本件、1.0-betaの時点では十分に制約を設けることができたと認識しています。
ひとまず、本issueはクローズします。
