### ISSUE TITLE
MSFT_lodの扱いについて

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#74]
VRMについての発表資料が見つけづらく、ソースにしづらいものが多いので難儀しているわけです がしかし、MSFT_lodの扱いについて意見があります。

  ユーザが用いるVRMフォーマットにおける、LoD(MSFT_lodの)の積極的な採用について、否定的な意見を申し上げます。LoDとはカメラからの距離に比例しロードするリソースを低負荷なものに切り替えるものである、特にMSFT_lodはLoDリソースをファイルに持たせるものである、という認識のもと話をします。
 では、否定的である理由について、以下3点、LoDクオリティの統一の困難、リソースサイズ、LoD作成の労力とその効果に対する疑問について説明します。

1. ユーザ作成によるLoDにおけるクオリティの均一化が難しいこと
    1. 高負荷時や負荷低減のため設定するLoDで、板になるかハイポリに近いようなものにするかはユーザに委ねられるべきなのか？TSOのポリリダクションのように、ハブサービス側からクライアントに送るときに必要な段階の機械的LoDを作成して送信できるようにし、ユーザーの手元のVRMにLoDは入れないのが順当なのではないかと考えます。（ユーザーはポリリダクションの許可（しなければ使えないサービスもアリ？）・またそのアルゴリズムあたりをサービスアップロード時に決められるような形）
 2. ファイルサイズの増大
      - 要は同じモデルの軽量版／最軽量版のような形で重複してファイルに持つことになるため、LoDを持たないモデルより何かしら必要なリソースを食う。頂点インデックスだけ飛ばして作れば多少マシで不可能でもないが、それで理想的なLoDを作るのはなかなか習得の難しい技術ではないかと感じる。
  3. 例えばLoDが必要なほど大きなマップに、満足できるほどの多数でインスタンシングできないユニークな、特にskinedなモデルが 存在すれば、LoDがあれどもハイスペックPCでもレンダリング負荷に負ける事になるのではないか、よってLoDの作成はユーザのコスパに見あい得るのという疑問。
（特にディスプレイより高FPSを要求するVRの時。（VRChat、Vketの民：VRM-Cの正会員にいらっしゃいますね、その辺詳しいのでは？ マップ形状からして兎にも角にもまずカリングー見せない事による最適化をした、みたいな話を聞いた記憶がありますが。）
       - 別に距離でなく、ロードされている人数、クライアントスペックなど別基準のLoD表示でも、1の問題から効果に私は疑問を持ちます。

以上からユーザが持つVRMにおけるLoD(MSFT_lod)の積極的な採用について、否定的な意見を申し上げます。
どうすべきかというと1.1にある通り、各ハブサービス等による自動LoD作成の実装です。

**Comment by hiroj** [comment]
MSFT_lodに関しては、ユーザーが自身でLOD対応VRMを作るのではなくアプリケーションがハブサービスに対してLOD付きモデルを要求した場合、かつアップロード者がモデルのリダクションを許可している場合に埋め込まれることを想定しています。
なので書いて頂いた1.1項目の通りになります。
UniVRM v1.0のExporterではMSFT_lodを埋め込む対応はしない予定です。

**Comment by iCyP** [comment]
承知いたしました。ご回答ありがとうございます。
