### ISSUE TITLE
[suggestion][1.0draft] Known Implementationのソート順をアルファベット順にする

### ISSUE THREAD

**Issue by saturday06** [vrm-c/vrm-specification#75]
細かいですが、Known Implementationに下記を追加するPull Requestを出そうと思ったのですが、ソート順が不明のためどこに追加して良いかわかりませんでした。アルファベット順でも無く、発表順でも無いように見えます。
https://github.com/kashikacojp/glTF-Maya-Exporter
( https://kashika.co.jp/product/vrmexporter/index.html )

ソート順をアルファベット順にすることを提案します。

**Comment by saturday06** [comment]
検索性ではアルファベット順が良いです。発表順の利点として「名前やURLが変わったときに位置を変更しなくて良い」という点があります。

**Comment by iCyP** [comment]
検索はいまどきctrl-fを使うと思います。どちらかというと何(言語,フレームワークetc...)に対する実装なのか記載があった方が良いかと思いました。
発表順は遡って追加するとアレになるので追加順でも良いのではと思いました。（例えばご提案のプラグインやVRM4U (UE4実装)は結構前からありますけれど、リストにないですし。（けど私Authorでないので掲載しても良いか分からない…

**Comment by saturday06** [comment]
それなら追加された順でい良いのかな？
でもよく考えたら、ここに実装一覧を書いちゃうと、実装一覧に追加するたびに仕様のドキュメントが変更になるので、この表自体を vrm.dev に移動したほうが良いのではと思い始めました。

**Comment by FMS-Cat** [comment]
https://github.com/KhronosGroup/glTF に従うと、適当で良い気がします。

**Comment by hiroj** [comment]
https://vrm.dev/en/vrm_applications/
Known Implementationの内容を↑に移動し、specにはリンクを張る形にしたいと思います。
追加したいものがある場合はvrm.devのほうにPull Requestをお願いいたします。

**Comment by hiroj** [comment]
https://github.com/vrm-c/vrm.dev/pull/48
Plug-in項目にVRM4UとglTF-Maya-Exporterを追加しました。

**Comment by saturday06** [comment]
対応ありがとうございました。クローズで。

ソート順、特に決めないで入れたい順で良いのかなと思い始めました。
