### ISSUE TITLE
[1.0draft] Is MToon cullMode.front necessary?

### ISSUE THREAD

**Issue by iCyP** [vrm-c/vrm-specification#79]
多くのゲームエンジン／webGLエンジンではフロントカリングが実装されており、表示も難無くできるので存在しているのだと思います。しかし、
 - フロントカリングを活用する場面が私には想定できない。（面を反転すれば済む）
   - 表出しないプロパティのアウトラインカリングモードも仕様から消えているので、さらにトリックが無くなっている。
 - DCCツールではフロントカリングがない事があるので、対応に難儀する。
 - [gltfのマテリアル仕様](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#double-sided)にもフロントカリングのオプションはない。
以上より、cullMode.frontの削除を希望します。

**Comment by FMS-Cat** [comment]
glTFにフロントカリングを有効にする項目無いんですね……。少し寂しい。
glTF側のマテリアルの定義を尊重する方針で十分だと思います。

**Comment by hiroj** [comment]
glTFに準拠する形にして、cullMode.frontは削除することにいたします。
