### ISSUE TITLE
A discussion about current `vrm.humanoid.humanBones` (duplicated bones)

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#8]
現在、 `vrm.humanoid.humanBones` フィールドは `array` 型となっていて、
同じ `vrm.humanoid.bone.bone` フィールド（=部位に相当）に相当する `vrm.humanoid.bone` を複数定義することができます。
これは、ある一つの部位に対して複数のボーンをアサインするような使い方を想定しての定義でしょうか？

もしそうでないならば、
`vrm.humanoid.humanBones` フィールドは各ボーン名をキー、 `vrm.humanoid.bone` を値とする `object` として定義されるべきと思います。
または、そのようなデータを許可しないのであれば、その旨を仕様として明示的に示す必要があります。

個人的には、Schemaのデータ構造の健全性を鑑み、該当箇所を `object` とする方が良いと考えています。

**Comment by iCyP** [comment]
上に同じなのですが、
現在
```json
"humanoid": {
    "humanBones": [
        {
            "bone": "hips",
            "node": 1,
            "useDefaultValues": true
        },
        {
            "bone": "spine",
            "node": 2,
            "useDefaultValues": true
        },……
```
となっているところ、
```json
"humanoid": {
    "humanBones": {
        "hips":{
            "node": 1,
            "useDefaultValues": true
        },
        "spine":{
            "node": 2,
            "useDefaultValues": true
        },……
```
となる方が仕様上好ましいと思います。
jsonのパースで弾けるほうが、実装者の懸案事項が減り、負担軽減になると思います。

**Comment by FMS-Cat** [comment]
この際、hipsやheadなど、VRMとして必須とするボーンについては `required` 属性をつけるとよりバリデーションがしやすくなりありがたいです。

**Comment by hiroj** [comment]
VRM1.0draftではhumanBonesのarrayを止めてmapに変更しました。
追加で変更したほうが良い点等あればご意見いただけると助かります。
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_vrm-1.0_draft/schema/VRMC_vrm.humanoid.humanBones.schema.json

**Comment by FMS-Cat** [comment]
良いと思います！
VRMとして要求・定義するボーンについては、仕様（以下URL）を参照すべきという認識でよろしいでしょうか。

https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft#humanoid

**Comment by hiroj** [comment]
必須ボーン等の仕様はドキュメントを参照していただくようお願いいたします。
required として定義するべきかどうかは #10 の議題もあるためいったん保留にします。

**Comment by hiroj** [comment]
1.0ではmapで記載する仕様になりました。
