### ISSUE TITLE
サムネイル「meta.thumbnailImage」は何を意味しているか

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#80]
`extensions.VRMC_vrm.meta.thumbnailImage` について、現在の草案で以下のように記述されています。

https://github.com/vrm-c/vrm-specification/blob/0a050129f24590b02b042f648c4cd6e5b8496dae/specification/VRMC_vrm-1.0_draft/schema/VRMC_vrm.meta.schema.json#L26-L29

現在のUniVRMプロジェクトのTestsフォルダに格納されているVRMファイルの `thumbnailImage` は、 **アバター全体のサムネイル** ではなく **顔写真** のようなものになっており、解像度は512×512ピクセルです。
https://github.com/vrm-c/UniVRM/blob/58e20856e3e6ff454a77b2d356a66dc384eead43/Tests/Models/Alicia_vrm-0.51/AliciaSolid_vrm-0.51.vrm

バーチャルキャストにおいて、`thumbnailImage` は、丸くクリップされユーザーの **アイコン** のような扱いで利用されています。
https://virtualcast.jp/wiki/doku.php?id=virtualcast:operation:tutorial#%E3%82%A2%E3%82%A4%E3%83%86%E3%83%A0%E3%81%AE%E6%8E%B4%E3%81%BF%E6%96%B9

`thumbnailImage` が **アバター全体のサムネイル** を意味するのであれば2048×2048ピクセル程度の解像度は要求されると思いますが、上記のような **顔写真/アイコン** であれば512×512ピクセルで十分かと思います。

また2048×2048ピクセルという解像度では、VRMファイルの容量を大きく増加させてしまうのではないでしょうか。

**Comment by hiroj** [comment]
##### 画像サイズに関して
* 2048×2048では確かにサイズが大きすぎることと、昨今のデバイスの解像度が際限なく大きくなっている現状を踏まえていったん1024x1024をrecommendedとするようにdescriptionを修正します。
##### 用途に関して
* 顔写真/アイコンとして使用されることが想定されているため、それをdescriptionとdocumentationに明記します。
##### その他
* アイコン用途として、正方形であることを必須を必須条件とします。

**Comment by hiroj** [comment]
schemaおよびドキュメントの内容変更完了しました。
