### ISSUE TITLE
UniVRM から vrm-specification へ issue を移動

### ISSUE THREAD

**Issue by esperecyan** [vrm-c/vrm-specification#81]
本リポジトリが作成される前に https://github.com/vrm-c/UniVRM/issues へ投稿された issue で Open になっているもののうち、ざっと見ただけですが、以下は本リポジトリに該当するかと思います。

VRM の仕様に関する issue は、本リポジトリへ移動できませんか。
https://help.github.com/ja/github/managing-your-work-on-github/transferring-an-issue-to-another-repository

https://github.com/vrm-c/UniVRM/issues/18
https://github.com/vrm-c/UniVRM/issues/22
https://github.com/vrm-c/UniVRM/issues/25
https://github.com/vrm-c/UniVRM/issues/35
https://github.com/vrm-c/UniVRM/issues/61
https://github.com/vrm-c/UniVRM/issues/88
https://github.com/vrm-c/UniVRM/issues/90
https://github.com/vrm-c/UniVRM/issues/112
https://github.com/vrm-c/UniVRM/issues/113
https://github.com/vrm-c/UniVRM/issues/125
https://github.com/vrm-c/UniVRM/issues/137
https://github.com/vrm-c/UniVRM/issues/156
https://github.com/vrm-c/UniVRM/issues/167
https://github.com/vrm-c/UniVRM/issues/174
https://github.com/vrm-c/UniVRM/issues/175
https://github.com/vrm-c/UniVRM/issues/211
https://github.com/vrm-c/UniVRM/issues/225

**Comment by hiroj** [comment]
内容を確認してissueをvrm-specificationへ移動させました

**Comment by esperecyan** [comment]
ご対応いただきありがとうございます。
