### ISSUE TITLE
Typo? stiffiness or stiffness

### ISSUE THREAD

**Issue by rdrgn** [vrm-c/vrm-specification#82]
SecondaryAnimationでは`stiffiness`という語が使用されていますが`stiffness`が正しいように思えます。

https://github.com/dwango/UniVRM/blob/c110041088f788e90da96e8331ad4d86d7a5bc8b/Scripts/Format/glTF_VRM_SecondaryAnimation.cs#L36-L40

https://github.com/dwango/UniVRM/blob/c110041088f788e90da96e8331ad4d86d7a5bc8b/Scripts/SpringBone/VRMSpringUtility.cs#L147

https://github.com/dwango/UniVRM/blob/c110041088f788e90da96e8331ad4d86d7a5bc8b/Scripts/SpringBone/VRMSpringUtility.cs#L215

**Comment by hiroj** [comment]
spec v1.0でTypo修正を行います。
合わせてglTF Extension Registry登録をする想定で拡張名をVRMC_vrmに変更予定です。
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft

**Comment by hiroj** [comment]
v1.0でtypo修正が行われているためこのissueはcloseします。
