### ISSUE TITLE
テクスチャの「Aniso Level」が反映されない

### ISSUE THREAD

**Issue by TokumeiDesu** [vrm-c/vrm-specification#84]
OS(Windows10 64bit)
Unityのバージョン(Unity 2018.2.2f1)
UniVRMのバージョン(0.40)

テクスチャの「Aniso Level」を変更してからVRM出力し、そのVRMをUnityで再読み込みさせたところ、
「Aniso Level」が反映されていないようです。
（他のテクスチャの各種設定項目については、確認しておりません）
こちら、反映されるようにして頂けると、非常に助かります。
ご検討の程、宜しくお願い致します。

**Comment by FMS-Cat** [comment]
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#samplers

glTFの仕様では、テクスチャフィルタリングでAnisotropic Filteringを有効化するか否かは実装に委ねられているようです（See: Default Filtering Implementation Note）。
VRMとして特別にAnisotropic Filteringを要求するシチュエーションがなければ、これについてVRMとして仕様を定める必要はないと思います。

**Comment by hiroj** [comment]
VRMの仕様として新たにAniso Levelを書き込むことは一旦しない方針とします。
