### ISSUE TITLE
Suggestion: Reserve glTF extension prefix

### ISSUE THREAD

**Issue by akihikodaki** [vrm-c/vrm-specification#85]
glTF documentation says:
> To request a prefix, submit a [GitHub issue](https://github.com/KhronosGroup/glTF/issues/new) with the name of the requested prefix and the vendor that will be using it. Maintainers, please assign the `extension` label to the issue.

https://github.com/KhronosGroup/glTF/commit/24e2a277dffb1f916136b8a54af440090e8fcc39

So why not submit an issue for `VRM`?

**Comment by hiroj** [comment]
Since management is now a VRM consortium, the extension name will be VRMC_vrm in spec v1.0.
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_vrm-1.0_draft

**Comment by ousttrue** [comment]
https://github.com/KhronosGroup/glTF/issues/1874
