### ISSUE TITLE
BlendShapeProxyのプリセットの標準拡張について

### ISSUE THREAD

**Issue by m2wasabi** [vrm-c/vrm-specification#86]
フェイシャルモーションキャプチャや海外向けリップシンクの対応を考えた場合、
標準仕様のBlendShapeだと定義が少なく思い通りに動かすのは困難です。
そして、独自に拡張した場合、ユーザーモデルで使われることはほとんどないでしょう。

かといって標準仕様を全部入りにしてしまうとモデルのサイズをいたずらに増やしてしまうことになります。

拡張BlendShapeのガイドラインやグループ化可能な辞書があれば、応用しやすくなると思うのですがいかがでしょうか。

ドキュメントサイトにガイドラインを決めて書いてしまうというのもアリだと思います。

参考：
[struct BlendShapeLocation | Apple Developer Document](https://developer.apple.com/documentation/arkit/arfaceanchor/blendshapelocation)
[Viseme Reference Images | Oculus Developers](https://developer.oculus.com/documentation/audiosdk/latest/concepts/audio-ovrlipsync-viseme-reference/)

**Comment by s-iwaki-d** [comment]
BlendShapeに関してはご提案もわかるのですが、現在VRMは
・アプリケーションからの制御しやすさ
・「人の顔」ではないアバターに対しての対応可能性
を考え、アプリケーションからは「顔の形（シェイプ）を制御する」のではなく、「感情を入力」しVRMのレイヤーでその表現とのマッピングを行う、という形をとっています。
これが最適であるという確信があるわけではないのですが、フェイシャルのシェイプ制御についてはしばらく使われ方を注視することとします。
