### ISSUE TITLE
SpringBoneに、Exclusions機能をつけて頂けませんでしょうか

### ISSUE THREAD

**Issue by phioalchemist** [vrm-c/vrm-specification#88]
VRMSpringBoneに、Exclusions機能をつけて頂けませんでしょうか。
私は、巨大な機械のサブアームを装備したアバターを使用しています。
VRMだとRigidbodyとfixed jointを使っての「生身の腕と機械の腕を同期させる機構」が使えないので、代替策としてSpringBoneでサブアームを揺らしているのですが、Exclusionsが無いとサブアームの指先まで一緒に揺れてしまいます。

**Comment by FMS-Cat** [comment]
若干本題から外れますが、UniVRM側のインタフェースが若干煩雑にはなるとは思いますが、SpringBoneはしっかりボーンごとにシリアライズされたデータを持たせたほうが、解釈する側としてはやりやすい気がします。

**Comment by FMS-Cat** [comment]
口頭で議論をしましたが、判断しきれなかったので次回会議までに噛み砕いてこちらにまとめます。

**Comment by ousttrue** [comment]
メモ

## スプリングの各節に個別に設定

* データ表現と設定が煩雑になりそう
* 不正なデータのチェックが必用
* Unityで各節に一個ずつアタッチするのは避けたい(全部同じでいい場合)

## 既存の方法に追加して、変えるところだけオーバーライドする

* [Json]オーバーライドは節ごとの個別設定
* [Json]オーバーライドしない場合は今までとだいたい同じ
* [Unity]オーバーライドするところだけ 追加のコンポーネントをアタッチする

**Comment by ousttrue** [comment]
merge しました
