### ISSUE TITLE
`blendShapeMaster.blendShapeGroups[i].materialValues` ' property name does not match to `materialProperties` one

### ISSUE THREAD

**Issue by FMS-Cat** [vrm-c/vrm-specification#91]
`blendShapeMaster.blendShapeGroups[i].materialValues[j].propertyName` が
`_MainTex_ST` を指しているのに対して、
`materialProperties[i]` には `_MainTex_ST` に該当するプロパティが見つかりませんでした。

おそらく、 `vectorProperties._MainTex` を指しているのではないかと推測しますが、
それぞれプロパティ名が一致するような変更を提案します。

`vectorProperties._MainTex` 側を `_MainTex_ST` に変えていただけると、
同名のテクスチャと名前が衝突せずきれいに収まりそうです。
過去のバージョンとの互換性の面から困難であることは承知しております。

**Comment by hiroj** [comment]
v1.0ではtypesのenumで指定するようにする予定です。types項目に関しては以下のissueで議論されています。
https://github.com/vrm-c/vrm-specification/issues/43

**Comment by hiroj** [comment]
#43で置き換わる予定です
