### ISSUE TITLE
[仕様] KHR_XMP拡張に対応してほしい

### ISSUE THREAD

**Issue by vyv03354** [vrm-c/vrm-specification#93]
https://github.com/KhronosGroup/glTF/pull/1553
採用してほしい理由をいくつかあげます。
* glTFのメタデータを表現する拡張が乱立するのは望ましくない。
* 将来的にVRM非対応のツールにも対応が期待できる。
* VRMではないglTF(たとえばニコニ立体のステージGLBなど)にもライセンスを設定できる。
* asset全体より細かい単位でライセンスを指定できるので、現在VRoidモデルで行われているような、テクスチャーのみ作者が異なるモデルのライセンスも容易に表現できる。

現在プルリクエストが提出されただけなので仕様は今後大幅に変わる可能性がありますし、正式採用はまだ先になりそうですが、逆にVRMの運用を踏まえて要望をKhronosに出すならチャンスは今しかありません。

**Comment by esperecyan** [comment]
メタデータに関するissueへリンクします。

https://github.com/vrm-c/vrm-specification/issues/5 glTF形式の、アバターでないオブジェクトデータなどにもライセンスデータを持たせたい
https://github.com/vrm-c/vrm-specification/issues/7 UniVRMでのライセンスの保護
https://github.com/vrm-c/vrm-specification/issues/51 [suggestion][1.0draft]著作権者等表示について
https://github.com/vrm-c/vrm-specification/issues/66 [suggestion][1.0draft]new meta property about meta.license = Redistribution Prohibited.
https://github.com/vrm-c/vrm-specification/issues/68 [suggestion][1.0draft] more usage steps and kinds.
https://github.com/vrm-c/vrm-specification/issues/80 サムネイル「meta.thumbnailImage」は何を意味しているか

**Comment by iCyP** [comment]
VRM1.0のメタデータとしてKHR_XMPを利用する事にあたって現状の問題点は、
 1.  まだKHR_XMPがドラフトであり、確定していないこと。（もはや大きな変更はないのではないかという妄想はありますが、VRM1.0(正式リリース)に自家でない物のdraft段階のものを乗せるのはあり得ないとも思います。
 2. SPDX[(以前の議論)](https://github.com/vrm-c/vrm-specification/issues/51#issuecomment-562413692) やXMP(adobe主導？のISO規格 [(e.g.)型(RFC2種依存、タイムゾーン付き時間型有り)](https://github.com/adobe/xmp-docs/blob/master/XMPNamespaces/XMPDataTypes/CoreProperties.md)、[主な変数](https://github.com/adobe/xmp-docs/blob/master/XMPNamespaces/dc.md) )の膨大な仕様の実装負担（私が面倒と思うだけ？互換性を保ちつつ必要十分な仕様だけ用いるようVRM仕様でKHR_XMPの利用範囲を定めてしまうのはどうか？邪悪？
 3. VRM固有のライセンス条項を独自名前空間等でKHR_XMPの仕様上定義できるか、そして定義すべきか。

があげられると思います。3についてはXMPのPRのｽﾚｯﾄﾞに凸して聞くのが早いと思いますが、私は外部の人間なので…。

**Comment by s-iwaki-d** [comment]
こちら検討させていただいたのですが、既にご指摘のあるとおりXHR_XMP拡張は求める用途に対して仕様が大きいこと、それに伴ってアプリケーション側の対応コストが上がることの懸念があり対応を見送ることにしました。ご提案ありがとうございます、そして対応が遅くなり申し訳ありませんでした。
