### ISSUE TITLE
Suggestion: Replace MToon with a vendor agnostic toon shader

### ISSUE THREAD

**Issue by jetkiwi** [vrm-c/vrm-specification#94]
### Description
While VRM itself is designed to be platform independent, the standard MToon shader relies heavily on Unity which make it hard to use it on any other platform.

### Proposed solution
Replace MToon with a platform independent toon shader, or rewrite MToon in GLSL.

### Other solutions considered
I considered making a custom implementation of MToon, but due to lack of documentation and specifications, this does not seem a viable solution.

**Comment by hiroj** [comment]
In vrm 1.0, separated MToon parameters into a single extension.
https://github.com/vrm-c/vrm-specification/tree/master/specification/VRMC_materials_mtoon-1.0_draft
