### ISSUE TITLE
Proposal: Define material specs as VRM independent extension

### ISSUE THREAD

**Issue by yutopp** [vrm-c/vrm-specification#95]
We propose these changes to resolve material definition problems in VRM.

- Define a spec and json schema for MToon shaders independently.
  - An extension name will be `VRM_material_mtoon`.
  - The definition will be clarified by @Santarh.
  - Extension data will not be included in `gltf.extentions.VRM.materials` but `gltf.materials.extensions`.
- Obsolete `gltf.extentions.VRM.materials` sections.
- Use material indices in glTF directly instead of material names to reference materials.

This proposal will resolve vrm-c/vrm-specification#94, vrm-c/UniVRM#172, vrm-c/vrm-specification#91, vrm-c/UniVRM#69 and vrm-c/UniVRM#64.

**Comment by FMS-Cat** [comment]
The discussion about it is being worked in 1.0 draft :tada:

**Comment by hiroj** [comment]
In VRM 1.0 it has been separated into Material Extensions.
