### ISSUE TITLE
VRM material parameter Color Property to export with Linear

### ISSUE THREAD

**Issue by hiroj** [vrm-c/vrm-specification#99]
### 内容
* MToon のColorプロパティは Linear Gamma が入り混じっているためこれをLinear に統一する　
* material拡張対応と同時に行う

### 関連
vrm-c/UniVRM#301
vrm-c/vrm-specification#95

**Comment by hiroj** [comment]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_materials_mtoon-1.0_draft/MToon_comparision.md

**Comment by FMS-Cat** [comment]
現状の1.0 MToonの仕様を見てみた限り、glTF側の仕様と同様に定義されている印象があります（よさそう）。

**Comment by hiroj** [comment]
https://github.com/vrm-c/vrm-specification/blob/master/specification/VRMC_materials_mtoon-1.0_draft/MToon_comparision.md
Colorとテクスチャのカラースペースの仕様は、Gltfの仕様に合わせる形になります。
